### ISSUE TITLE
Split webpack.config.js into webpack.config.dev.js and webpack.config.prod.js

### ISSUE THREAD

**Issue by lzhuor** [blockchain/blockchain-wallet-v4-frontend#1000]
## Description
Hi team,

I realized we're using a single webpack config across build environments - as in `webpack.config.js`. 

I propose to split it into two files - [`webpack.config.dev.js` and `webpack.config.prod.js`] then update npm tasks accordingly. 

It enables us to worry less about checking `isCIBuild` (basically separate of concern).

Please kindly let me know your thought. I have a working copy locally. I will clean it a bit and create a PR for your reference.

**Comment by schnogz** [comment]
This work has been on my wishlist for a while. Would love to see it get tackled! 

Since we don't use webpack in live environments, I think it would make sense if the files were named `webpack.dev.config.js` and `webpack.ci.config.js`.
