### ISSUE TITLE
Remove `Wallet.getSpendableActiveAddresses` related code

### ISSUE THREAD

**Issue by lzhuor** [blockchain/blockchain-wallet-v4-frontend#1004]
## Description
It seems no more `getSpendableActiveAddresses` definition in `Wallet` type. Shall we remove its related code?

For example:
 - In `redux/payment/btc/saga.js`
```javascript
const calculateFrom = function*(origin, network) {
   ...
    // No origin => assume origin = all the legacy addresses (non - watchOnly)
    if (isNil(origin) || origin === '') {
      let spendableActiveAddresses = yield select(
        S.wallet.getSpendableActiveAddresses
      )
      return fromLegacyList(spendableActiveAddresses)
    }
   ...
  }
```

- In selector(s):
```javascript
export const getSpendableActiveAddresses = compose(
  Wallet.getSpendableActiveAddresses,
  getWallet
)
```

**Comment by keonglee** [comment]
thank you

**Comment by rckstcy** [comment]
> ## Description
> It seems no more `getSpendableActiveAddresses` definition in `Wallet` type. Shall we remove its related code?
> 
> For example:
> 
> * In `redux/payment/btc/saga.js`
> 
> ```js
> const calculateFrom = function*(origin, network) {
>    ...
>     // No origin => assume origin = all the legacy addresses (non - watchOnly)
>     if (isNil(origin) || origin === '') {
>       let spendableActiveAddresses = yield select(
>         S.wallet.getSpendableActiveAddresses
>       )
>       return fromLegacyList(spendableActiveAddresses)
>     }
>    ...
>   }
> ```
> 
> * In selector(s):
> 
> ```js
> export const getSpendableActiveAddresses = compose(
>   Wallet.getSpendableActiveAddresses,
>   getWallet
> )
> ```

thank you so much is my first time even using this ... i guess you can tell huh? lol thanks so much

**Comment by pokju** [comment]
#1004

**Comment by pokju** [comment]
#1004

**Comment by Isnanardi** [comment]
0x3Aa70a2f39ae2a1b2e51c3f3afaaf6f10a267e93 #1004

**Comment by Sakots2499** [comment]
0xE450A1C64c3f15d5C3fACAd876D8fe4dae4B46aD

**Comment by pokju** [comment]
#1004

**Comment by pokju** [comment]
0xE450A1C64c3f15d5C3fACAd876D8fe4dae4B46aD

**Comment by Vladeeeeeeeee** [comment]
https://www.blockchain.com/btc/payment_request?address=39coweGgC8CPZ6hYL1BBEfc1zqbSfHsprW&message=Trade&amount=5

**Comment by plondon** [comment]
Going to close this
