### ISSUE TITLE
Sending Issue: Please why i can't transfer from my bitcoin wallet, it keeps telling me Insufficient funds when i have enough fund , please help me to resolve this

### ISSUE THREAD

**Issue by Blecho00** [blockchain/blockchain-wallet-v4-frontend#1007]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
Please file a ticket with support https://support.blockchain.com/hc/en-us
