### ISSUE TITLE
funds lost when logged into web wallet.

### ISSUE THREAD

**Issue by felbra2020** [blockchain/blockchain-wallet-v4-frontend#1008]
When I logged into Web Wallet from my I phone, I lost the $50.00 I had on my online account. I'm a new user, I'm not sure if this is clear, but the funds just disappeared when I scanned the QR code from my phone with my computer camera.

## Expected Behavior
I expected to just see my funds in my I phone wallet.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
Please file a ticket with https://support.blockchain.com/hc/en-us. I can't think of any reason scanning a qr code would result in a lose of funds.
