### ISSUE TITLE
The following wallet address is a scam through a bot in "Telegram" called @BTC_FAUCET_bot

### ISSUE THREAD

**Issue by MikeamusPrime** [blockchain/blockchain-wallet-v4-frontend#1016]
3AadAUCnbHuj3KYXZ5CJqNknnYqvKUFG1Z

Do not send them any money to "upgrade" any part of your service account status. I have confirmation of receipt of funds, but no action taken on their end. Even the Telegram app is now posting inside that bots chat after each message that it has been reported as a scam, and furthermore there is no way to contact the developers. I just wouldn't want anyone else to fall victim to this same issue.

https://drive.google.com/file/d/10KJ8vtn-wYlX74bLuzlkdfUC8c0zr3T0/view?usp=drivesdk

**Comment by plondon** [comment]
Thanks for reporting @MikeamusPrime
