### ISSUE TITLE
No Buy and Sell option for blockchain? HELP

### ISSUE THREAD

**Issue by lightningrod345** [blockchain/blockchain-wallet-v4-frontend#1028]
# 🐛 Bug Report 🐛

i cannot see the option for "buy and sell" on blockchain. Please help me

**Comment by plondon** [comment]
We're constantly working on adding new buy/sell partners. What region are you in?

**Comment by lightningrod345** [comment]
I’m in the America’s

**Comment by affenrahim** [comment]
Asean region..brunei

**Comment by lightningrod345** [comment]
Northeast sorry
