### ISSUE TITLE
1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY

### ISSUE THREAD

**Issue by mikeazucena4** [blockchain/blockchain-wallet-v4-frontend#1036]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by mikeazucena4** [comment]
![11007667_10152761309723107_683835230_n](https://user-images.githubusercontent.com/29907983/46364846-f0831b80-c644-11e8-840c-581c0c111fbc.jpg)

**Comment by schnogz** [comment]
❤️
