### ISSUE TITLE
verify identité issu withe web site

### ISSUE THREAD

**Issue by ahmedkisma** [blockchain/blockchain-wallet-v4-frontend#1041]
# 🐛 Bug Report 🐛

## Description
when i try to verify ma identité there some things wrong with your web site, i fill all information but they reject the verification 
![bitcoin](https://user-images.githubusercontent.com/37741128/46443422-78604700-c765-11e8-902f-0ccaa73f8fd5.JPG)

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
Please contact our support team.

**Comment by ahmedkisma** [comment]
is seems that is ok thanks pondon
