### ISSUE TITLE
Unable to make unlimited transaction through blockchain wallet api > function "Send To Many"

### ISSUE THREAD

**Issue by blockmine1** [blockchain/blockchain-wallet-v4-frontend#1042]
# 🐛 Bug Report 🐛
## Description
I am having issue while i am using send to many function of blockchain wallet api i am getting this error after some unconfirmed transactions 

1538659506265 - error: ERR_PUSHTX
1538659512650 - error: ERR_PUSHTX

## Expected Behavior
While it should send unlimited transaction from 1 address to many address of other bitcoin wallets. 

Please guide me what i am doing wrong that i am having this issue? 

currently i am using one wallet and it's one address. 

https://www.blockchain.com/btc/address/1DyXTgGjYgHBKj2R3U9GnvwKYQfxGcUwSE

this one address i use only to send funds to many from one wallet. 

and this wallet was generated through wallet api. so it's gave me one address. in wallets&addresses page.

Thanks

**Comment by blockmine1** [comment]
Is there any one to reply me on this isssue? because its very urgent for me,

**Comment by blockmine1** [comment]
I am using send to many function of blockchain wallet api and i am facing issue.

when upto 20 transaction done then after i get error in terminal that 

1538652825520 - error: ERR_PUSHTX
1538652826930 - error: ERR_PUSHTX


and until that upto 20 transactions get 1 confirmation on block i am unable to send any other transaction from send to many function from that wallet and it's specific address again. 

kindly help me regarding this. 

Thanks

**Comment by keonglee** [comment]
tq

**Comment by blockmine1** [comment]
> tq

This issue still not fixed for me,

**Comment by keonglee** [comment]
ok

**Comment by blockmine1** [comment]
Do you know about this issue? have you seen this before?

**Comment by ZlD238749725** [comment]
ยังใม่รู้เพาะมาเป็นครั้งแลก

**Comment by plondon** [comment]
The feature request is on our roadmap

**Comment by plondon** [comment]
https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/1341
