### ISSUE TITLE
Ordered coins from blockchain.com: Why does it take so long?

### ISSUE THREAD

**Issue by Niconoctem** [blockchain/blockchain-wallet-v4-frontend#1043]
# 🐛 Bug Report 🐛

## Description
I ordered bitcoins from the buy/sell feature and it says it will take nearly 30 days to receive the funds.

## Expected Behavior
Quick release of funds

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
It takes a while for the bank transaction to settle.
