### ISSUE TITLE
blockchain won't upload id

### ISSUE THREAD

**Issue by Ramstacar** [blockchain/blockchain-wallet-v4-frontend#1050]
# 🐛 Bug Report 🐛

## Description
I am attempting to upload my ID in blockchain wallet and when I click ON ID it says pending and does not give me the chance to upload 
## Expected Behavior
that it would load your ID
## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by rickybarber** [comment]
When I start verification and click on Drivers License the software immediately jumps to... 
Identity Verification Pending
You're almost there! The uploaded information is being reviewed. This should just take a few minutes.
Buy Limit: $0
Sell Limit: $0
Refresh Status
![capture](https://user-images.githubusercontent.com/44305118/47243390-6f9f8000-d3b7-11e8-89a3-45f1a8fecda6.JPG)

**Comment by franks6111** [comment]
It keeps asking for verification but then won't allow me to do anything I would like to get my limit so I can purchase and sell throug  blockchain

**Comment by schnogz** [comment]
Is anyone still having this issue? (@franks6111, @rickybarber, @Ramstacar)

Please respond with more error details or we will be closing this issue soon.

**Comment by essubroto** [comment]
For my country ID don't upport it

**Comment by essubroto** [comment]
For my country ID don't support it
