### ISSUE TITLE
E-mail notification does not work 

### ISSUE THREAD

**Issue by cmukjc** [blockchain/blockchain-wallet-v4-frontend#1056]
# 🐛 Bug Report 🐛

## Description
I set e-mail notification ON, but it does not seem to be working

## Expected Behavior
I expect to receive e-mail notification every time I receive coins. 

## Reproduction Steps
Go to setting and preference, then put ON the e-mail notification

## Screenshots/Logs
http://prntscr.com/l6fy4m

## Additional Information
None

**Comment by lckeong1623** [comment]
sorry,  because I on the work jod....please help me open my wallet

**Comment by McZenith** [comment]
Is this issue still available? I'd like to work on it.
