### ISSUE TITLE
remove blockchain account or change Backup Phrase!

### ISSUE THREAD

**Issue by newworkerr** [blockchain/blockchain-wallet-v4-frontend#1058]
hello!
i created a new blockchain account with my different email address, because someone told me he can connect his mining hardware antminer s9 to my blockchain account and then i can earn 30% each 48 hours!!!
i knew he is scammer but i just started playing with him what he is going to do with my empty wallet!
after that i created my account , he said give me your ID and password to access to my account to connect his hardware with blockchain account . i did it and then he wanted me to change my blockchain password! ( here i knew he exported my backup phrase as i guess!)
then he wanted me fund my wallet !!! 
i know he don't have my password right now because i changed my password , but he still have the backup phrase ! i just want to change it if it's not possible how to remove my blockchain account for this huge and important issue??

thanks a lot
alireza :)

**Comment by rckstcy** [comment]
send me your 12 word phrase and i will put it back to normal for you.  mail to rckstcy@protonmail.com

**Comment by MARINADJZ** [comment]
I ja sam imala takav slucaj ali ne mogu da promenim blockain novcanik niti lozinku pa trbam pomoc jer sam kupila bitcoine za 750$.....moze li neko da mi pomogne.

**Comment by plondon** [comment]
Don't send people your 12 word phrase

**Comment by plondon** [comment]
Just don't use that account and create a new one, a different backup phrase will be generated.

**Comment by MARINADJZ** [comment]
A STA JE SA NOVCEM KOJI SAM ULOZILA 750$,...JER ON OSTAJE NA STAROM....I PROPADA..HVALA,
