### ISSUE TITLE
descrip

### ISSUE THREAD

**Issue by sithip879** [blockchain/blockchain-wallet-v4-frontend#1060]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by chrismas25** [comment]
https://blockchain.info/payment_request?address=1CKhgyigMx1VEwY4JcDX1ALJPgbFGxpFuF&amount=0.000483&message=0x28Ac9d12F9A8A13785887528bb63E9Ae019BaAba
