### ISSUE TITLE
Can't sell my bitcoins

### ISSUE THREAD

**Issue by DamRann** [blockchain/blockchain-wallet-v4-frontend#1074]
When i try to sell my bitcoins, it just load when i clik "Submit".
I have try many times now, and if i just wait it log my out

**Comment by franks6111** [comment]
We need to have a support button on the blockchain site tried to enter my account so I can buy and sell directly and it's not complete and I've got no way they find the answers

**Comment by plondon** [comment]
@DamRann hmm is there any error in the console?

**Comment by DamRann** [comment]
Where?

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

________________________________
Fra: Philip London <notifications@github.com>
Sendt: Thursday, November 1, 2018 1:35:43 AM
Til: blockchain/blockchain-wallet-v4-frontend
Cc: DamRann; Mention
Emne: Re: [blockchain/blockchain-wallet-v4-frontend] Can't sell my bitcoins (#1074)


@DamRann<https://github.com/DamRann> hmm is there any error in the console?

**Comment by plondon** [comment]
https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers

**Comment by nobuyuki1965** [comment]
Yes

**Comment by schnogz** [comment]
Is this still an issue @nobuyuki1965 ?  Please update the ticket with relevant information or this will be closed.
