### ISSUE TITLE
Blockchain wallet

### ISSUE THREAD

**Issue by regent777** [blockchain/blockchain-wallet-v4-frontend#1088]
# 🐛 Bug Report 🐛      

 Hello, 

I can`t use  Blockchain Wallet Exchange, I'm not able to enter the amount of BTC or ETH. My account is verified.

Thank you !

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
Hi @regent777 I don't see any image in this thread.

**Comment by regent777** [comment]
Sorry...it was attached in email.
![screen shot 2018-11-07 at 02 01 02](https://user-images.githubusercontent.com/44797998/48145207-5a17ca80-e280-11e8-9db7-67c6a02d8305.png)

**Comment by plondon** [comment]
@regent777 thanks, based on this it looks like the wallet is having trouble getting your bitcoin cash balance. Just to confirm, do you see this balance in the top right? Additionally, do you see any errors in the console when going to the exchange tab? Specifically the multiaddr call?

**Comment by plondon** [comment]
Try clicking on the main balance, do you see btc/bch balances?

**Comment by regent777** [comment]
Yes,I see that..
![screen shot 2018-11-07 at 16 55 56](https://user-images.githubusercontent.com/44797998/48163581-09b76180-e2ae-11e8-9884-8c78f3a5574b.png)

**Comment by plondon** [comment]
Can you please open a ticket with support.blockchain.com, they will instruct you on sending screenshots of the web console during debugging your issue. That info should not be shared here.

**Comment by regent777** [comment]
Ok Philip..thank you very much for your effort.

Best regards!

**Comment by umarajib0** [comment]
#1500

**Comment by umarajib0** [comment]
- [ ] [
Duplicate of #](url)
