### ISSUE TITLE
Bug : Identity Verification Success!

### ISSUE THREAD

**Issue by taxtist** [blockchain/blockchain-wallet-v4-frontend#1107]
# 🐛 Bug Report 🐛
![2018-11-08 10 40 23](https://user-images.githubusercontent.com/18159654/48172327-d246c480-e342-11e8-8e79-9b3af31d84aa.png)
![2018-11-08 10 40 34](https://user-images.githubusercontent.com/18159654/48172328-d246c480-e342-11e8-8007-6f3d3acc45ed.png)
![2018-11-08 2 51 36](https://user-images.githubusercontent.com/18159654/48180225-fff13500-e365-11e8-8dad-575a4a1bbae6.png)

i have done : Identity Verification

but when i log in, homepage shows me need to Identity Verification

but i already did it,so i can't register my phone again

it drive me  crazy 

plz help 

reply to taxtist@gmail.com

thank you 

it is my e-mail address for BLOCKCHAIN

## Description
Provide a clear and concise description of the issue.

## Expected Behavior

Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.
![2018-11-08 2 51 36](https://user-images.githubusercontent.com/18159654/48180207-eea82880-e365-11e8-99f8-c5f4d45d3497.png)

**Comment by plondon** [comment]
Thanks for the report. Looking into your issue.

**Comment by plondon** [comment]
Just to make sure, you definitely only have one wallet? And it is the same wallet which you verified?

**Comment by taxtist** [comment]
yes !!!!!

what are you talking about ? 

i told you i have a e-mail from blockchain.com

there isn’t two e-mail from blockchain 

and i use only one e-mail address and only one phone

that is bug i am sure 

plz check this case quickly

thank you 

ps. i am an investor only buy stellar 

so there is no reason i use blockchain.com wallet before 

so i am very sure there is only one wallet id

**Comment by plondon** [comment]
How many emails do you have in your inbox with 'welcome to my wallet' as the subject?

**Comment by taxtist** [comment]
only one :-)

**Comment by taxtist** [comment]
if there is no way to fix it 

just delete my phone register 

i will re-register identity 

my account e-mail is taxtist@gmail.com

thank you for your help 

i already have a e-mail for XLM airdrop

there is only 2 weeks limit

plz help me :) thank you again

**Comment by taxtist** [comment]
![2018-11-09 2 37 03](https://user-images.githubusercontent.com/18159654/48245192-157d6200-e42d-11e8-842a-ecc33fdd6467.png)

**Comment by taxtist** [comment]
![2018-11-09 2 38 48](https://user-images.githubusercontent.com/18159654/48245223-3645b780-e42d-11e8-98ab-7fdd64aa0b67.png)

**Comment by taxtist** [comment]
![identity](https://user-images.githubusercontent.com/18159654/48245267-55444980-e42d-11e8-9761-337208584487.png)

**Comment by taxtist** [comment]
![blockchain](https://user-images.githubusercontent.com/18159654/48245295-7147eb00-e42d-11e8-9e33-373d7b0c919e.jpeg)

**Comment by taxtist** [comment]
thank you :-)

**Comment by vtheanh** [comment]
> I’ll raise with support. I can’t reset your status but hopefully they can help

help me .the same.i Identity Verification Success! but when i log in, homepage shows me need to Identity Verification in review. gmail me : phamvansung48208@gmail.com. id: 48ea4f4b-a7dc-486b-9761-1d881ba274d3.help me again

**Comment by vtheanh** [comment]
![image](https://user-images.githubusercontent.com/39077322/48590728-3553df00-e973-11e8-86b9-798e663c1a68.png)

**Comment by vtheanh** [comment]
> Tôi sẽ nâng đỡ với sự hỗ trợ. Tôi không thể đặt lại trạng thái của bạn nhưng hy vọng họ có thể trợ giúp

![image](https://user-images.githubusercontent.com/39077322/48590806-8bc11d80-e973-11e8-829b-c740fd8f1cb4.png)
