### ISSUE TITLE
identity verification for Indian, please add option for other govt ID like AADHAR , as everyone might not be having Passport

### ISSUE THREAD

**Issue by rakeshKMonline** [blockchain/blockchain-wallet-v4-frontend#1108]
# 🐛 Bug Report 🐛

## Description
for ID proof of Indian  national only passport appear
## Expected Behavior
drop down menu should also give option for more govt ID like AADHAR
## Reproduction Steps
add more option in govt ID type
## Screenshots/Logs
nr

## Additional Information
na

**Comment by plondon** [comment]
Unfortunately we had to turn off aadhar. Will reach out if it comes back though.
