### ISSUE TITLE
Fraud

### ISSUE THREAD

**Issue by Gordon5859** [blockchain/blockchain-wallet-v4-frontend#1111]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by Gordon5859** [comment]
Everyone's posing as a work for you. Everything is handed over to IP option, and they continue with a further investigation into collaboration with the police and Interpol. Please, I want my money back and my earnings and explanations, because I can be the salvation for them and for you if you give me back my money and my profits and I can be hell, believe me because there's been serious crimes done a lot. For your sake and their good money and send my earnings and contact me, I wish you well. Really.[
![joxi_screenshot_1541666435572 azzz](https://user-images.githubusercontent.com/44466677/48187889-a6284500-e33c-11e8-90fe-585a7a6e5943.png)
![joxi_screenshot_1541665383272 kg](https://user-images.githubusercontent.com/44466677/48187901-ade7e980-e33c-11e8-9676-0bbe39b330ab.png)
![joxi_screenshot_1541632702647](https://user-images.githubusercontent.com/44466677/48187938-c2c47d00-e33c-11e8-86ae-7839a480bb2b.png)
![joxi_screenshot_1541633139547](https://user-images.githubusercontent.com/44466677/48187972-d07a0280-e33c-11e8-8379-8d71f60fe3e4.png)

**Comment by Gordon5859** [comment]
I have a lot more evidence, saved from the first day, and I keep getting transactions, i.e. email that says transaction numbers and TD and TD. Please report to your email, goran5859@gmail.com. I only write the truth and give true evidence, because I want my money invested and I want my profit.

**Comment by plondon** [comment]
Sorry not sure this has anything to do with the blockchain wallet

**Comment by Gordon5859** [comment]
Goran Kuckovic вам је послао/ла имејл у Gmail поверљивом режиму:Re: [blockchain/blockchain-wallet-v4-frontend] Fraud (#1111)Ова порука је послата 08.11.2018. у 01.11.57 PSTМожете да је отворите кликом на линк испод. Овај линк функционише само за reply@reply.github.com.Прикажи имејлGmail поверљив режим вам даје већу контролу над порукама које шаљете. Подесите датум истека, онемогућите штампање или прослеђивање поруке и још много тога. Сазнајте вишеGmail: Google-ов имејлКоришћење подлеже Google политици приватностиGoogle LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USAПримили сте ову поруку зато што вам је неко послао имејл у Gmail поверљивом режиму.

**Comment by javedjakali786** [comment]
JUST I LOST MY money IN blockchain wallet. It was 800$, who accessed my wallet and who sent it. Its really farud. Even iam enabled 2fa security. Ans i have backup.pharse also. Plz take it serious or else people will call blockchain is scam. I have full evidence. Contact me javedjakali786@gmail.com
