### ISSUE TITLE
Restrict spending by geographic region

### ISSUE THREAD

**Issue by dpm39560** [blockchain/blockchain-wallet-v4-frontend#1117]
# Feature Request and Suggestion

## Description
Most crypto users remain in one geographic location. Many crypto hackers are from a different location than the authentic user. Implement a first-line-of-defense guard being a geographic region check whenever crypto spending is initiated from any wallet.

## Expected Behavior
A crypto user initiates a spending transaction from their wallet. The wallet then immediately checks the geographic region from which the transaction was initiated. If it is the same as the registered user's transaction, then allow the transaction to proceed with the next step. If the geographic region is different, then suspend the transaction and notify the authentic user. Users should be able to turn off this region checking feature, either manually or on a calendar basis, to provide for travel plans. 

Warnings should be issued to each user activating this feature outlining that there are ways (such as TOR) this measure could be circumvented, but the feature could be activated to add another level of security. 

## Reproduction Steps
N/A

## Screenshots/Logs
N/A

## Additional Information
None.

**Comment by schnogz** [comment]
Wonderful idea! We will take this back to the team and discuss further.

Thanks for the feedback.
