### ISSUE TITLE
Unable to verify identity with Drivers License -- "Oops something went wrong"

### ISSUE THREAD

**Issue by meatspoon** [blockchain/blockchain-wallet-v4-frontend#1118]
# 🐛 Bug Report 🐛

## Description
I have registered with blockchain.com, I have submitted my personal details and got to the point where it is asking for my drivers license or government ID.  On the "Verify Your Identity" page, it explains that I must submit ID.  I press the "Continue" button and get an "Oops, something went wrong" message.

I only have one email in my email account from blockchain with the title of "Welcome to my wallet".  I have received other emails from Blockchain: 
"Confirmed: you are on the list"
"verify your bank account on SFOX" which I did
"You can now sell bitcoin with your Blockchain wallet"
"Its your turn to claim your XLM"

So I have been working through all the steps, but I am getting that error when I go to submit my ID.  I have tried on Brave Browser as well as Chrome.

## Expected Behavior
I would expect to see a screen where I can upload pictures/scans of my ID.

## Reproduction Steps
Proceed through the registration and KYC steps until you are prompted to submit a DL or government ID.   Select "Continue" and notice the "Oops..." error.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.
![id submission error](https://user-images.githubusercontent.com/44905405/48278190-70ee2680-e412-11e8-922d-44dbfda322a6.jpg)

## Additional Information
Add any addition information that might be useful to our team.

**Comment by meatspoon** [comment]
Knock knock, anyone home?  There is no way to contact customer service on your site and apparently Blockchain isn't responding to bugs here.  How successful do you think this business will be if Blockchain can't distribute an air drop or accept driver's license scans?

**Comment by meatspoon** [comment]
The issue persists.  Any progress with the "backend?"  Spank that thing a
couple of times and get it in line.

**Comment by plondon** [comment]
Spanked

**Comment by meatspoon** [comment]
I hope your spanking has a positive delayed effect, because I am still
getting the error as described in the GitHub report.  Show that backend who
is boss, Philip!

**Comment by plondon** [comment]
Spanked again

**Comment by meatspoon** [comment]
Still nothing, man.  I appreciate your repeated spankings of the backend,
but I am still getting the same error message on multiple browsers.  Am I
the only person experiencing this issue?  Or is everyone who is trying to
be a new user dealing with this?  Has anyone been able to claim their XLM?

**Comment by plondon** [comment]
A very small percentage of users seem to be having the issue, still unsure as to why

**Comment by meatspoon** [comment]
Well, thanks for your effort.  If it helps at all, I am running Windows 7
64-bit and I have tried on Brave Browser as well as Chrome.

**Comment by plondon** [comment]
If you're good with chrome dev tools and https://github.com/zalmoxisus/redux-devtools-extension I could direct you to finding your user id which would help us with debugging. I know thats not super convenient but not sure there is another way.

**Comment by plondon** [comment]
Also requesting to see if we can use your guid to debug

**Comment by meatspoon** [comment]
What is a wallet guid and where can I find it?  I see that and want to
guess Graphical User ID or something?

**Comment by plondon** [comment]
The user id you use to login essentially, can also be found in settings > general

**Comment by meatspoon** [comment]
5e5aaaa7-021d-4f45-b290-105c68bef5db

Send that down to the nerdery and have 'em crunch some numbahs!

Thanks

**Comment by plondon** [comment]
Please don't post this in public forums, sorry I didnt stress that enough.

**Comment by Rexxarius** [comment]
Hello, @plondon, @AndreaPravato, @meatspoon.
I have a same issue.

First time I complete verification via PC (start of verification) and mobile phone (for making photo of ID and my selfie). 
I received mail from "blockchain.info" stated, that "You've been verified! Congratulations! You have been approved to exchange cryptocurrencies. We’re super excited for you."
But next day i found, that i "not verified" again (via website).
If i choose to do verification agian, i see "Oops something went wrong"...

...and my friend have this message too, but he never make KYC verification.

**Comment by plondon** [comment]
@Rexxarius can you email me philip@blockchain.com your guid please

**Comment by plondon** [comment]
@AndreaPravato can you please as well send your guid in an email

**Comment by plondon** [comment]
We've moved on to a different IDD provider, if this issue persist please ping me

**Comment by heidibug** [comment]
I am having an issue with this verification as well. How can I get Blockchain to upload my DL?

**Comment by meatspoon** [comment]
I too still have problems. The “thinking” animation is now different but it continues indefinitely and will not bring me to a screen that allows for the upload of my DL.

**Comment by heidibug** [comment]
> I too still have problems. The “thinking” animation is now different but it continues indefinitely and will not bring me to a screen that allows for the upload of my DL.
> […](#)
> Sent from my iPhone
> On Feb 3, 2019, at 2:48 PM, heidibug ***@***.***> wrote: I am having an issue with this verification as well. How can I get Blockchain to upload my DL? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by heidibug** [comment]
I have money pending in my wallet due to this. My money has been tied up for a month and I am getting no help. Not sure what else to do.

**Comment by AndreaPravato** [comment]
It's still not working for me either. Now the issue is different, as shown in the screenshot
![verification](https://user-images.githubusercontent.com/4329975/52276428-7811cb80-2952-11e9-891c-3774fbb19c2e.png)

**Comment by totallytot** [comment]
The same issue is actual for me too. @plondon do yo have any progress?

**Comment by nikitaratkevich** [comment]
@plondon Any news?

**Comment by plondon** [comment]
@AndreaPravato @totallytot @nikitaratkevich a few users experiencing the same issue. I think it has to do with removing the Region field, which is sometimes required and sometimes not. https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/1479/files#diff-f83f82bb1316702ae96b3728e13d2a55L446

**Comment by plondon** [comment]
Region was added back in staging, should be released to production shortly.

**Comment by nikitaratkevich** [comment]
Ok, please ping me when it's in prod.
As a QA Expert and user with this problem, I'll test.

**Comment by heidibug** [comment]
My funds are showing up now. I just don't know how to get them out. My computer doesn't have a camera. I am sure I will figure it out. But at least I can do bitcoin to bitcoin transfers now.


 

    On Thursday, April 4, 2019, 11:41:45 AM EDT, Nikita Ratkevich <notifications@github.com> wrote:  
 
 
Ok, please ping me when it's in prod.
As a QA Expert and user with this problem, I'll test.

**Comment by plondon** [comment]
Please try again

**Comment by nikitaratkevich** [comment]
@plondon 
Test Failed.
https://i.gyazo.com/c2f531381f5e61db897520d029b4a108.png
I tried in incognito mode and with old cache.
I see the same error.

**Comment by totallytot** [comment]
@plondon 
Still actual for me too:
![image](https://user-images.githubusercontent.com/25451877/55646204-40ed5880-57e3-11e9-8bb7-995c57c2328b.png)

**Comment by totallytot** [comment]
Hi @plondon, do you have any updates on this matter? The issue is still reproducible, but as I can see the bug is closed.

**Comment by plondon** [comment]
We have added verbose logging:

1. Go to: https://login.blockchain.com/open/log-level?level=verbose
2. Login
3. Reproduce the error
4. send screenshots of console log

**Comment by plondon** [comment]
Better to send screenshots directly to user ops instead of posting publicly in github as well.

**Comment by nikitaratkevich** [comment]
Could you share ops email? There is no contact us link on the website

**Comment by plondon** [comment]
support.blockchain.com

**Comment by totallytot** [comment]
> We have added verbose logging:
> 
> 1. Go to: https://login.blockchain.com/open/log-level?level=verbose
> 2. Login
> 3. Reproduce the error
> 4. send screenshots of console log

done

**Comment by Galenzo** [comment]
> We have added verbose logging:
> 
> 1. Go to: https://login.blockchain.com/open/log-level?level=verbose
> 2. Login
> 3. Reproduce the error
> 4. send screenshots of console log

Done

**Comment by lukaszszczesniak** [comment]
> > We have added verbose logging:
> > 
> > 1. Go to: https://login.blockchain.com/open/log-level?level=verbose
> > 2. Login
> > 3. Reproduce the error
> > 4. send screenshots of console log
> 
> Done
> 
> About my problem
> 
> Got an email from Blockchain.com "Congrats, your identity is verified." That was weeks ago.
> 
> However, I still see a big sign "Verify my Identity" button within Blockchain when I log in. For me, now, when I go to Blockchain.com -> Settings -> Profile -> "Verify My Identity" button -> I get this message: "Oops, something went wrong here! Please click hereto refresh." ... and no ... nothing happens when I click 'here' to refresh.
> 
> ![1](https://user-images.githubusercontent.com/50155799/56996837-8452a100-6bae-11e9-955b-189203e0e435.png)
> ![2](https://user-images.githubusercontent.com/50155799/56996838-8452a100-6bae-11e9-8d42-1d4b5f99bcef.png)
> ![3](https://user-images.githubusercontent.com/50155799/56996840-8452a100-6bae-11e9-9b42-a34fecef25c8.png)
> ![4](https://user-images.githubusercontent.com/50155799/56996841-8452a100-6bae-11e9-947d-18096a28ce80.png)

I have the same problem!

**Comment by thoroc** [comment]
Friend having the same issue from his laptop on both Chrome and Edge (both on latest version). Not great.

**Comment by michalcichon** [comment]
I get the same error on the UI. I'm not sure if the factor is the same but I've noticed that the `veriff` endpoint gives me this kind of response:

```
{
	"id" : "{{there-was-some-id-here}}",
	"code" : 70,
	"type" : "CONFLICT",
	"description" : "User is not allowed get credentials"
}
```

Maybe it will throw some light on it.

**Comment by plondon** [comment]
Thanks @michalcichon! Let me bring this back to a few developers on the BE team to see what they can find.

**Comment by Merabm** [comment]
I've got the same problem, I think the problem is that my camera when I verified wasn't as good as it needs. can u help?

**Comment by Janpr99** [comment]
Getting the same issue...

**Comment by guy-blockchain** [comment]
> I get the same error on the UI. I'm not sure if the factor is the same but I've noticed that the `veriff` endpoint gives me this kind of response:
> 
> ```
> {
> 	"id" : "{{there-was-some-id-here}}",
> 	"code" : 70,
> 	"type" : "CONFLICT",
> 	"description" : "User is not allowed get credentials"
> }
> ```
> 
> Maybe it will throw some light on it.

This is caused from a user hitting the `/kyc/credentials/{$PROVIDER}` endpoint. When `user.kycState` is NOT set to NONE.

**Comment by guy-blockchain** [comment]
Here are some of the logs:

**Comment by guy-blockchain** [comment]
```
"[15:00:48.739] [WARN] [XNIO-1 task-37] [KycCredentialHandler] [470da8ed2008] User 338ea06f-21f5-4718-b2bd-470da8ed2008 should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:48.901] [WARN] [XNIO-1 task-129] [KycCredentialHandler] [3c732852042c] User 141f5b98-58c5-4c7c-b085-3c732852042c should be in NONE state to be able to create session, but state is UNDER_REVIEW"
"[15:00:49.687] [WARN] [XNIO-1 task-36] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:49.867] [WARN] [XNIO-1 task-131] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:49.936] [WARN] [XNIO-1 task-182] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:50.618] [WARN] [XNIO-1 task-82] [KycCredentialHandler] [4063b8a84c1b] User 5af5628b-5a28-4d97-921a-4063b8a84c1b should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:51.462] [WARN] [XNIO-1 task-47] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:49.282] [WARN] [XNIO-1 task-53] [KycCredentialHandler] [4bf0157851b7] User fa62e6a4-6000-43b5-8ab3-4bf0157851b7 should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:50.311] [WARN] [XNIO-1 task-106] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:51.167] [WARN] [XNIO-1 task-60] [KycCredentialHandler] [4bf0157851b7] User fa62e6a4-6000-43b5-8ab3-4bf0157851b7 should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:51.218] [WARN] [XNIO-1 task-163] [KycCredentialHandler] [0862908c871b] User e5b19700-3494-41e3-ab9b-0862908c871b should be in NONE state to be able to create session, but state is UNDER_REVIEW"
"[15:00:51.357] [WARN] [XNIO-1 task-103] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:50.137] [WARN] [XNIO-1 task-39] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:50.405] [WARN] [XNIO-1 task-139] [KycCredentialHandler] [e568e6cd164b] User d5408a1e-2cbd-461f-b95a-e568e6cd164b should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:50.537] [WARN] [XNIO-1 task-150] [KycCredentialHandler] [e56c0294b798] User f9e70907-77f3-4b22-9389-e56c0294b798 should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:51.230] [WARN] [XNIO-1 task-147] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:51.740] [WARN] [XNIO-1 task-190] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:52.121] [WARN] [XNIO-1 task-102] [KycCredentialHandler] [156e70bb6bc8] User be150eae-16b8-4dcc-9d17-156e70bb6bc8 should be in NONE state to be able to create session, but state is PENDING"
"[15:00:53.896] [WARN] [XNIO-1 task-32] [KycCredentialHandler] [e56c0294b798] User f9e70907-77f3-4b22-9389-e56c0294b798 should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:51.638] [WARN] [XNIO-1 task-122] [KycCredentialHandler] [68931516431d] User 43c88bfa-5d65-4005-9bb2-68931516431d should be in NONE state to be able to create session, but state is VERIFIED"
"[15:00:52.134] [WARN] [XNIO-1 task-168] [KycCredentialHandler] [156e70bb6bc8] User be150eae-16b8-4dcc-9d17-156e70bb6bc8 should be in NONE state to be able to create session, but state is PENDING"
"[15:00:52.308] [WARN] [XNIO-1 task-186] [KycCredentialHandler] [e56c0294b798] User f9e70907-77f3-4b22-9389-e56c0294b798 should be in NONE state to be able to create session, but state is VERIFIED"
```

**Comment by Merabm** [comment]
Thank you I already solved this problem

**Comment by CaptiveON** [comment]
> "[15:00:50.405] [WARN] [XNIO-1 task-139] [KycCredentialHandler] [e568e6cd164b] User d5408a1e-2cbd-461f-b95a-e568e6cd164b should be in NONE state to be able to create session, but state is VERIFIED"

Yes that makes sense!!! If a user's claim is pending, verified or under review... then he's getting the problem with no proper message at front end. Thanks !

**Comment by CaptiveON** [comment]
Getting the same issue!!!
![Screenshot_4](https://user-images.githubusercontent.com/50413233/57382339-35b49080-71c6-11e9-9269-1757eb33f122.png)

**Comment by Galenzo** [comment]
> > We have added verbose logging:
> > 
> > 1. Go to: https://login.blockchain.com/open/log-level?level=verbose
> > 2. Login
> > 3. Reproduce the error
> > 4. send screenshots of console log
> 
> Done
> 
> About my problem
> 
> Got an email from Blockchain.com "Congrats, your identity is verified." That was weeks ago.
> 
> However, I still see a big sign "Verify my Identity" button within Blockchain when I log in. For me, now, when I go to Blockchain.com -> Settings -> Profile -> "Verify My Identity" button -> I get this message: "Oops, something went wrong here! Please click hereto refresh." ... and no ... nothing happens when I click 'here' to refresh.
> 
> ![1](https://user-images.githubusercontent.com/50155799/56996837-8452a100-6bae-11e9-955b-189203e0e435.png)
> ![2](https://user-images.githubusercontent.com/50155799/56996838-8452a100-6bae-11e9-8d42-1d4b5f99bcef.png)
> ![3](https://user-images.githubusercontent.com/50155799/56996840-8452a100-6bae-11e9-9b42-a34fecef25c8.png)
> ![4](https://user-images.githubusercontent.com/50155799/56996841-8452a100-6bae-11e9-947d-18096a28ce80.png)

Any news?

**Comment by plondon** [comment]
@Galenzo. This means you are tagged for the airdrop and when youre account verification is finished you will get the airdrop.

I'll add some check to the code to make sure users don't think they have to re-verify or something.

**Comment by Galenzo** [comment]
> @Galenzo. This means you are tagged for the airdrop and when youre account verification is finished you will get the airdrop.
> 
> I'll add some check to the code to make sure users don't think they have to re-verify or something.

![image](https://user-images.githubusercontent.com/50155799/57414330-50a3f680-7200-11e9-91d3-feff7eada547.png)

Interesting, however my acc is verified already 2 weeks, meeh

**Comment by sebastianxcf** [comment]
Hi,
I'm facing the same error, I've claimed the XML after registration, I've received the email of success verification, but when I press the claim button I get the error of "something went wrong here! please click to refresh".

Any clues here?

Thanks in advance. 
Sebastian

**Comment by oskarlopez4** [comment]
Hello, I have the same error. Who can I contact?

**Comment by plondon** [comment]
@TheLeoB if you have time today can you check how the wallet handles:

1. a user becomes tier 2 but does not click on claim button
2. user signs in after becoming tier 2
3. user goes to xlm page and clicks claim xlm

**Comment by TheLeoB** [comment]
1. User clicks claim XLM
2. Directed to Doc Upload
3. Oops! error as described above

The wallet is tagged for airdrop though, and funds were received in testing env.

**Comment by TheLeoB** [comment]
I see the error as being described above, but users should still be tagged to receive airdrop.

**Comment by Galenzo** [comment]
> I see the error as being described above, but users should still be tagged to receive airdrop.

All my friends (5) got xlm at 10 minutes.We all did it at the same time, but only i waiting already about 2 weeks.

**Comment by TheLeoB** [comment]
Has your profile already been verified? 

If so, the airdrop happens in batches. If you haven't received it - you may be in the next batch.

**Comment by Galenzo** [comment]
Yes, my profile is verified. But isn't it strange that all my friends got it in moment, but i not?

**Comment by CaptiveON** [comment]
> Has your profile already been verified?
> 
> If so, the airdrop happens in batches. If you haven't received it - you may be in the next batch.

Is it normal to take more than 3 weeks to be verified at golden level? I'm seeing my Golden Level "In Review" for more than 3 weeks now. I didn't receive any kind of mail either. Sorry to write here because no one is replying on specified issue's thread. Kindly tell me what to do. Thanks!

**Comment by Illibes** [comment]
hah, lol, I am waiting for it from the end of december. The first letter I get from blockchain was invalid. I was waiting for new, but nothing happens. And only now when I try again to do the same with the first letter - I have got the same problem as U..)
Was write to support center, but I don't know..I was verified about 2 months ago and wtill waiting..(
By the way - sorry for my "great" level of English education :D

**Comment by Illibes** [comment]
I am already have gold level from December.  And have got the same problems as other. Can somebody tell me what to do? Just wait, or something? Thatnk U for answer in advice

**Comment by nikitaratkevich** [comment]
I can't do verification because I see the same error on the verification screen.
Support guys has ignored my email.
7 months guys cannot fix this blocker. Nice service!

**Comment by Illibes** [comment]
Hah, Welcome to the club, body. 
Зашибись, конечно

**Comment by jakubgrzybek** [comment]
I got mail with verification from weird adress... (Coinify.com). Is it correct? I passed tier 2 and got verified, but when I press claim free xlm it shows again to verify myself and then "oops sth went wrong". I am waiting almost 3 weeks for my drop :/

**Comment by Galenzo** [comment]
> Hah, Welcome to the club, body.
> Зашибись, конечно

Сидим, ждем, ничего

**Comment by Illibes** [comment]
В адрессной строке "/issues/1118", у разрабов, видимо есть куда более важные задачи, так что да, сидим, ждем..

**Comment by jidsfotech** [comment]
Please has any one been able to resolve this issues 
![Untitled](https://user-images.githubusercontent.com/26555105/57935098-f3bbd680-78b8-11e9-9d77-d8d774066700.png)
its been weeks now and Im stuck on that page 

{"id":"errased-by-me",
"code":12,
"type":"UNKNOWN_USER",
"description":"Unknown User"
}
 this is from chrome console, Please i need a way to get this issues resolved

**Comment by Galenzo** [comment]
There is still no solution of our problem...

**Comment by jidsfotech** [comment]
That's rather sad.. i do hope i  dont miss out in the free air drop because of this issues

**Comment by danynho** [comment]
I have same problem, what i can do ?
![image](https://user-images.githubusercontent.com/34445615/57943362-1f988580-78d4-11e9-94cc-516b81a5f64f.png)

**Comment by rascal-pl** [comment]
Same here. I tried on 2 different accounts.

**Comment by Galenzo** [comment]
I do not understand why you do not want to solve this problem. You cannot recognize that if a person does not have this error, he receives money immediately. Those who have a mistake, either do not come, or come in a couple of months. So hard to solve this problem?

**Comment by Galenzo** [comment]
Most interestingly, I caught this bug because of the lagging of the site. There was a day when the site had failed authorization and registration. All the friends who registered the next day got the money right away: /

**Comment by Galenzo** [comment]
@plondon

**Comment by piotr-koca** [comment]
I have the same problem when trying to claim XLM.

I have successfully finished verification by submitting the photo and id/driver license. There is still a button to claim XLM, but when I press it it redirects me to finish verification process. When I try to do it the same error as others already pointed out occurs.

```
{
    "code": 70,
    "description": "User is not allowed get credentials",
    "id": "[REDACTED]",
    "type": "CONFLICT"
}
```

This happens then this URL is called:

https://api.blockchain.info/nabu-gateway/kyc/credentials/veriff?api_code=[REDACTED]&ct=1558297918948

I have submitted support ticket but did not get any answer except for some auto responder.

**Comment by WelingtonCarvalho** [comment]
Got the same issue

**Comment by AdnanAhdan1** [comment]
I'm facing the same problem..
![qqqqqqqqqqqqqq](https://user-images.githubusercontent.com/33714316/58345149-22195300-7e71-11e9-9a0c-329f3f801e63.JPG)

I tried many browser PC, laptop and mobile also but facing the same problem.

 if anyone who has solved the issue by trying another way, please share it.
I'll be glad for your kind.
thank you.

**Comment by CaptiveON** [comment]
The problem still persists as well as I don't think that I'm gonna get the Gold Level approval like ever!

**Comment by Galenzo** [comment]
> Got the same issue
> ![image](https://user-images.githubusercontent.com/26684709/58314519-0a48bd00-7de6-11e9-9c4c-0071befa8cba.png)

Waiting for help already 2 months, no answer from blockchain...

**Comment by Rosiebet777** [comment]
I cant verify mine also can i get help with this?

**Comment by Rosiebet777** [comment]
I cant verify mine also can i get help with this?

**Comment by Rosiebet777** [comment]
I've verified mine.....but under the buy and sell section after i put in my ssn and dob i get the message......



Unfortunately there was a problem verifying your identity click here to start over

**Comment by Mohdngah** [comment]
as a owner or funder of crypto asset I am very disappointed with all block game games. especially in the case I want some bitcoin to get into my wallet because my wallet is still 0 and nothing. with variefty which the world is aware of and knows the level of security  the highest on the data of a member or owner ie first emeil / no phone / first name and last name and date of birth. and this is obviously clear and legitimate evidence not only in united kingdom.united state and malaysia but also in the world know this is treasure and  my fund which is traded all over the world. why should I trouble me as the owner of all my crypto and my money. how many times i want my variefty in this. does not it violate the world or there is shrimp behind all this. enough with the profit you get from the results and capital  I just want the convenience to transfer all of my bitcoins into any of the wallets I list this is the right  yes and i need to use it.

**Comment by Mohdngah** [comment]
as a owner or funder of crypto asset I am very disappointed with all block game games. especially in the case I want some bitcoin to get into my wallet because my wallet is still 0 and nothing. with variefty which the world is aware of and knows the level of security  the highest on the data of a member or owner ie first emeil / no phone / first name and last name and date of birth. and this is obviously clear and legitimate evidence not only in united kingdom.united state and malaysia but also in the world know this is treasure and  my fund which is traded all over the world. why should I trouble me as the owner of all my crypto and my money. how many times i want my variefty in this. does not it violate the world or there is shrimp behind all this. enough with the profit you get from the results and capital  I just want the convenience to transfer all of my bitcoins into any of the wallets I list this is the right  yes and i need to use it.

**Comment by Mohdngah** [comment]
as a owner or funder of crypto asset I am very disappointed with all block game games. especially in the case I want some bitcoin to get into my wallet because my wallet is still 0 and nothing. with variefty which the world is aware of and knows the level of security  the highest on the data of a member or owner ie first emeil / no phone / first name and last name and date of birth. and this is obviously clear and legitimate evidence not only in united kingdom.united state and malaysia but also in the world know this is treasure and  my fund which is traded all over the world. why should I trouble me as the owner of all my crypto and my money. how many times i want my variefty in this. does not it violate the world or there is shrimp behind all this. enough with the profit you get from the results and capital  I just want the convenience to transfer all of my bitcoins into any of the wallets I list this is the right  yes and i need to use it.

**Comment by Mohdngah** [comment]
as a owner or funder of crypto asset I am very disappointed with all block game games. especially in the case I want some bitcoin to get into my wallet because my wallet is still 0 and nothing. with variefty which the world is aware of and knows the level of security  the highest on the data of a member or owner ie first emeil / no phone / first name and last name and date of birth. and this is obviously clear and legitimate evidence not only in united kingdom.united state and malaysia but also in the world know this is treasure and  my fund which is traded all over the world. why should I trouble me as the owner of all my crypto and my money. how many times i want my variefty in this. does not it violate the world or there is shrimp behind all this. enough with the profit you get from the results and capital  I just want the convenience to transfer all of my bitcoins into any of the wallets I list this is the right  yes and i need to use it.

**Comment by Mohdngah** [comment]
as a owner or funder of crypto asset I am very disappointed with all block game games. especially in the case I want some bitcoin to get into my wallet because my wallet is still 0 and nothing. with variefty which the world is aware of and knows the level of security  the highest on the data of a member or owner ie first emeil / no phone / first name and last name and date of birth. and this is obviously clear and legitimate evidence not only in united kingdom.united state and malaysia but also in the world know this is treasure and  my fund which is traded all over the world. why should I trouble me as the owner of all my crypto and my money. how many times i want my variefty in this. does not it violate the world or there is shrimp behind all this. enough with the profit you get from the results and capital  I just want the convenience to transfer all of my bitcoins into any of the wallets I list this is the right  yes and i need to use it.

**Comment by Mohdngah** [comment]
as a owner or funder of crypto asset I am very disappointed with all block game games. especially in the case I want some bitcoin to get into my wallet because my wallet is still 0 and nothing. with variefty which the world is aware of and knows the level of security  the highest on the data of a member or owner ie first emeil / no phone / first name and last name and date of birth. and this is obviously clear and legitimate evidence not only in united kingdom.united state and malaysia but also in the world know this is treasure and  my fund which is traded all over the world. why should I trouble me as the owner of all my crypto and my money. how many times i want my variefty in this. does not it violate the world or there is shrimp behind all this. enough with the profit you get from the results and capital  I just want the convenience to transfer all of my bitcoins into any of the wallets I list this is the right  yes and i need to use it.

**Comment by kopsa95** [comment]
https://github.com/orestis987/theremin/blob/92a4f3bf4bb71909a9426b1bc2f51b4b9b25e87c/rhasberry.py#L7

**Comment by kopsa95** [comment]
`https://github.com/orestis987/theremin/blob/92a4f3bf4bb71909a9426b1bc2f51b4b9b25e87c/rhasberry.py#L7`

**Comment by kopsa95** [comment]
[https://github.com/orestis987/theremin/blob/92a4f3bf4bb71909a9426b1bc2f51b4b9b25e87c/rhasberry.py#L7](url)

**Comment by kopsa95** [comment]
### https://github.com/orestis987/theremin/blob/92a4f3bf4bb71909a9426b1bc2f51b4b9b25e87c/rhasberry.py#L7

**Comment by kopsa95** [comment]
https://github.com/orestis987/theremin/blob/92a4f3bf4bb71909a9426b1bc2f51b4b9b25e87c/rhasberry.py#L7

**Comment by kopsa95** [comment]
https://github.com/orestis987/theremin/blob/92a4f3bf4bb71909a9426b1bc2f51b4b9b25e87c/theremin.txt#L2

**Comment by AwesomeAde** [comment]
> I've verified mine.....but under the buy and sell section after i put in my ssn and dob i get the message......
> 
> Unfortunately there was a problem verifying your identity click here to start over

i'm having the same issue, have you find a solution yet?

**Comment by cofi002233** [comment]
Same problem here, I see this has been going on for a while. Can't believe it hasn't been fixed.

**Comment by Niku7a** [comment]
Same problem here, when can we get our airdrop? :(

**Comment by AwesomeAde** [comment]
I didn’t get it either. It’s suppose to arrive automatically after identity
is verified

**Comment by jakubgrzybek** [comment]
I am waiting about 2 months now.. I gave them my ID card so it’s not fair to not get the airdrop...

> Wiadomość napisana przez AwesomeAde <notifications@github.com> w dniu 05.06.2019, o godz. 09:03:
> 
> I didn’t get it either. It’s suppose to arrive automatically after identity
> is verified
>

**Comment by AwesomeAde** [comment]
Their customer support is very poor. I’ve contacted them for about two
weeks now but nothing from them

**Comment by Otoriku** [comment]
Got the same problem, verified with Driver license and getting the error

**Comment by Fitsaq** [comment]
Этот баг так и будет висеть?
У меня точно такая же проблема а кошелек заново не создашь...

**Comment by sirks** [comment]
I have been blockchain.info client since BTC price was below 100USD. Maybe there is some issues with old customers?

**Comment by purestmoney** [comment]
i have several coins for sale.. contact  purestmoney@gmail.com

**Comment by bgwardi** [comment]
I no understand, please halp me

**Comment by purestmoney** [comment]
what is it you do not understand
    On Thursday, August 1, 2019, 02:35:47 AM GMT+1, bgwardi <notifications@github.com> wrote:  
 
 
I no understand, please halp me

**Comment by ariajack** [comment]
Apa sudah ada yang menemukan solusi atas masalah ini?

**Comment by purestmoney** [comment]
Bitcoin Private Miner.exe - AnonFile


| 
| 
|  | 
Bitcoin Private Miner.exe - AnonFile


 |

 |

 |




    On Friday, August 9, 2019, 05:06:10 AM GMT+1, ariajack <notifications@github.com> wrote:  
 
 
Apa sudah ada yang menemukan solusi atas masalah ini?

**Comment by Jimbo113** [comment]
I have the same issue .. 7.9.19

**Comment by yvemhl** [comment]
Jag har samma problem med verifieringsidentiteten"oj, något gick fel". Det går inte att verifiera sin identitet och jag har prövat i fler veckor. Finns det något annat sätt att verifiera sig på?
Köpte Bitcoin i februari 2018 och jag kan bara "titta bara" på beloppet, men inte några bitcoin. Varför kan  jag "titta bara" på beloppet men inte antalet Bitcoin? Nu tänkte jag sälja dem men det går inte för dem är inte tillgängliga. Varför är dem inte tillgängliga? Är det för att man inte kan verifiera sig? Skickat flera mail till supporten men dem vill inte svara. Tråkigt, tråkigt!!


![20190828-dokument behövs-1](https://user-images.githubusercontent.com/54794847/64478650-83103100-d1ab-11e9-8ee3-e65165375393.PNG)
![20190828-hoppsan något gick fel-3](https://user-images.githubusercontent.com/54794847/64478652-83103100-d1ab-11e9-8a49-0f790ba8fd9a.PNG)
![20190828-verifieringsinformation-2](https://user-images.githubusercontent.com/54794847/64478653-83a8c780-d1ab-11e9-9860-359c62e10205.PNG)

**Comment by milionariosnet2050** [comment]
hi admin help GOLD LEVEL In Review verification pendent ?

**Comment by milionariosnet2050** [comment]
Pending KYC Enrollment Pending

**Comment by smitherstyle** [comment]
I am having the same issue but I never got the option to upload my DL and it said that my ID couldn't be verified after linking the app on my phone to the exchange during the first time logging in...
