### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Mondei1** [blockchain/blockchain-wallet-v4-frontend#1124]
# Feature Request and Suggestion

## Description
I wish there is a dark mode. I'm this type of human who likes applications and websites in dark. I know someone in the Blockchain team suggest that, I just know ^^. My Firefox and operating system (Elementary OS) is in dark and everything else, so it would be nice If blockchain is that too. I think this is not so complicated to implement. 

Currently there is that "Invert" mode but I just don't like it. 

## Additional Information
If you keep that "Invert" mode, just one more thing: When you hover over the text in the left panel, it disappears, because it changes the color to black.

P.S.: Why are there so many nonsense issues here?

**Comment by plondon** [comment]
Thanks for the request. If you're interested in helping out you can send us the colors you want for dark mode. Color palettes are here: https://github.com/blockchain/blockchain-wallet-v4-frontend/blob/development/packages/blockchain-info-components/src/Colors.

You can create one called DarkMode.js and use whatever dark mode color palette you prefer. Let me know if you have questions/need help.

**Comment by Mondei1** [comment]
I'll work on this ^^. Just setup the development server quick and then I will notify you when I'm done. I'll create a pull request for this later. Maybe I can help in future too!

**Comment by Mondei1** [comment]
This is how it looks like now:
![Current look](http://i.imgur.com/W0oENjc.png)
I'm not finished yet. There are some color's that I'm not agree with yet. What's your opinion? Just say it, I'm not a UI designer, so I know it's ugly or kind of ( ͡° ͜ʖ ͡°)

**Comment by plondon** [comment]
🔥 🔥 🔥 🔥 🔥

**Comment by plondon** [comment]
Ugh I don't know why those scrollbars show up for some people, they don't for me on my macbook pro

**Comment by Mondei1** [comment]
@plondon Really? Cool ^^. I'm using Firefox in Linux and I don't know If it's in Chrome too, I'll test it tomorrow.

**Comment by plondon** [comment]
Might be a firefox thing, I'll take a look

**Comment by Mondei1** [comment]
Or so. One thing anyway: These two buttons in the left bottom corner "Security Center" and "Settings" gets off screen like you can see on my screenshot. I think it's because these two alerts shows up. And the theme selector dropdown goes off screen two. But one click on a item in the left sidebar fix it and the another one broke it again. Just saying. Is maybe something for a other issue.

**Comment by Mondei1** [comment]
I have an idea. In ProtonMail you have the ability to import your own theme and looks like that:
![ProtonMail example](http://i.imgur.com/I2gNF1N.png)
Then users can import CSS code from other users and apply them and the dashboard adapts to it. I think this would be better because each person likes something else and I think that only a few people would report this here on GitHub for an other theme pack. In this case it would be that JSON object instead of CSS but the concept is the same. What do you think?

**Comment by plondon** [comment]
It is a cool idea and we've thought about it before, the problem is we need to very carefully monitor all of the code that is exposed to the wallet client. Otherwise user's could be prone to attackers obtaining their private keys and mnemonic. So I don't think allowing users to import JSON w/o some very serious restricting and type checking is a good idea.

I'm more than happy with people contributing this way though!

**Comment by plondon** [comment]
Ooo, thanks for the typo fix!

**Comment by plondon** [comment]
Can you make a PR and I'll include it in the next release (a few days)

**Comment by Mondei1** [comment]
Sure but there are some issues with that theme like I mentioned. Can you help me there?

**Comment by Mondei1** [comment]
I'll just move the dark theme into the `DarkMode.js` and replace the `Default.js` with the default values and create a PR then. You guys just have to implement the code, so users can choose the theme. And there are some issues like I said where I don't know how to fix.

@plondon Thanks for following me :smiley:

**Comment by dewsoda1** [comment]
pengeam23@gmail.com

Pas = Wesa1234$



Ooo, thanks for the typo fix!
>
>

>

**Comment by plondon** [comment]
@dewsoda1 why are you leaving your password out in the public?

**Comment by Mondei1** [comment]
I don't get it too...

**Comment by Mondei1** [comment]
It's merged now, so this is here is done.

**Comment by plondon** [comment]
Thanks again @Mondei1 !
