### ISSUE TITLE
I can't sent bch out right now

### ISSUE THREAD

**Issue by weiyanwuda** [blockchain/blockchain-wallet-v4-frontend#1125]
# 🐛 Bug Report 🐛
BCH node crash
## Description
I think you guys BCH node has been failed, but you guys didn't notice
## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by aleksfomm** [comment]
I confirm this issue too!
Sending BCH unsuccessfull, I got message: Your bitcoin cash transaction failed to send. Please try again.
And I no received BCH today (11/11/2018), but I see 71 Confirmations for this transaction on the bitcoincash.blockexplorer.com and no this money on blockchain wallet!

**Comment by schnogz** [comment]
Thanks for reporting.  Our BCH nodes are back in sync and send is now operational.

**Comment by gitchand** [comment]
An error occured:
16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26
While pushing a bch transaction.
