### ISSUE TITLE
Why steal my money straight from my wallet? blockchain hacked? How can I get my money back?

### ISSUE THREAD

**Issue by kslabs** [blockchain/blockchain-wallet-v4-frontend#1126]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by javedjakali786** [comment]
JUST I LOST MY money IN blockchain wallet. It was 800$, who accessed my wallet and who sent it. Its really farud. Even iam enabled 2fa security. Ans i have backup.pharse also. Plz take it serious or else people will call blockchain is scam.

**Comment by javedjakali786** [comment]
I have all evidence. My mail id is javedjakali786@gmail.com
