### ISSUE TITLE
Blockchain wallet freezes my browser

### ISSUE THREAD

**Issue by aleksfomm** [blockchain/blockchain-wallet-v4-frontend#1128]
# 🐛 Bug Report 🐛

## Description
Hello!
When I login to my blockchain wallet, it freezes my Firefox browser (CPU usage up to 100%).
I use last version of this browser.
Also I tryed login to my wallet on other computer, but got similar result (freeze browser, high CPU usage).
Please see screenshot attachment.
Why it happens? How fix it? What browsers or system settings do you recommend for using blockchain wallet? Is it hide cpu mining?!
Best Regards,
Max

## Expected Behavior
How fix it? What browsers or system settings do you recommend for using blockchain wallet?

## Reproduction Steps
Just login to wallet via browser!

## Screenshots/Logs
https://i.postimg.cc/BvLsYVGH/blockchain-freeze.png

## Additional Information
Previous versions of web wallet was work good!

**Comment by aleksfomm** [comment]
For Dashboard page or TRANSACTIONS pages - high CPU usage (100%).
For Settings page or Exchange page - normal CPU usage.

**Comment by aleksfomm** [comment]
Another example browser freeze:
Firefox v50.1.0, Windows XP SP3
https://i.postimg.cc/h4V4CymF/freeze.png

**Comment by aleksfomm** [comment]
It seems that during my own experiments, I discovered what influences the high CPU usage.
If developers are interested, I will write the details.

**Comment by aleksfomm** [comment]
Do you accept issues or details, comments, etc. in Russian?

**Comment by aleksfomm** [comment]
@ tony-blockchain
Проблема в том, что раньше после авторизации на сайте blockchain.com успешно осуществлялся вход, открывалась страница Dashboard и можно было работать.
Теперь после входа и открытия страницы Dashboard происходит резкое увеличение нагрузки на CPU и, соответственно, браузер «замерзает», не реагируя на клики.
Первоначально я столкнулся с этим на компьютере с Windows XP SP3, браузер Firefox 50.1.0. Это наглядно видно на скриншоте: https://i.postimg.cc/h4V4CymF/freeze.png

Предположив, что проблема в браузере, я проверил вход на blockchain.com с того же компьютера из других браузеров: Google Chrome 49.0.2623.112m и Yandex 17.4.1.758
Эффект заморозки браузера точно такой же – загрузка CPU до 100% процессом браузера и приходится удалять процесс браузера через системный «Диспетчер задач».

Далее, я предположил, что кроме версии браузера, проблема возможна из-за старой версии операционной системы (Windows XP SP3).
Взяв другой, более современный компьютер с Windows 7 SP1 (x86), я установил самую последнюю на тот момент версию Firefox 63.0.1 (сейчас 63.0.3), но и это не решило проблемы, браузер точно также завис на страницы Dashboard после авторизации на сайте blockchain.com. 
Скриншот из Windows 7: https://i.postimg.cc/BvLsYVGH/blockchain-freeze.png

На этом этапе я попытался выяснить, есть ли какие-то системные требования или какие-либо рекомендации по особым настройкам браузера для работы с сайтом blockchain.com, но ни в разделе помощи на сайте, ни в официальном блоге, ни на различных форумах в интернете не нашёл информации об этом.
Я подумал, что мне могут помочь в тех.поддержке support.blockchain.com и задал вопрос (Запрос #682573 от 28.11.2018 17:53). Но, спустя примерно сутки, мой запрос просто закрыли без комментариев, установив статус запроса «Выполнен» и никакого ответа не сообщили. Мой второй запрос об этом (Запрос #701760 от 13.11.2018 21:15) тоже остался без ответа и тоже был закрыт со статусом запроса «Выполнен».

Далее, я вспомнил, что иногда некоторые сайты при заходе на них из неподдерживаемых версий браузеров, сообщают, какую минимальную версию следует использовать.
Я решил проверить это и зашел на blockchain.com из встроенного в Windows 7 браузера Microsoft Internet Explorer 11.0.9600.17280 (версия обновления 11.0.12).
При нажатии на сайте кнопке «Войти» сайт выдал мне ценную информацию: 
Your browser is not supported. Please update to at least Chrome 45, Firefox 45, Safari 8, Edge, or Opera.
Таким образом удалось получить сведения, которые указывают на то, что даже браузеры на компьютере с Windows XP должны работать нормально (Firefox 50.1.0 и Chrome 49.0.2623.112m).

Далее, после авторизации на сайте blockchain.com я обратил внимание, что страница Dashboard состоит из нескольких основных элементов:
1)	Баланс BTC, BCH, ETH, XLM
2)	График курса валют
3)	Список транзакций
При этом эти элементы загружаются не одновременно, а как бы последовательно. При этом список транзакций загружается в последнюю очередь и именно после этого браузер «замерзает» и происходит чрезмерная нагрузка на CPU.
Для подтверждения этого, я попробовал после открытия страницы Dashboard, но до загрузки списка транзакций, сразу перейти в какой-нибудь другой раздел, успев кликнуть по нему (например, в раздел Settings или Exchange). И – о чудо! – это получилось без проблем и никакой сверх-нагрузки на CPU не произошло. Для проверки я также успешно отправил немного криптовалюты.

После этого у меня появилось обоснованное предположение, что браузер зависает в момент получения списка транзакций. Это легко подтвердилось: находясь в разделе Settings своего кошелька, я попытался перейти на страницу Bitcoin в разделе TRANSACTIONS. И тут же получил загрузку CPU до 100%. Ожидание в течение 15 минут не дало результата – браузер завис, страница транзакций биткоина так и не открылась. Тоже самое произошло при попытке перейти на страницу Bitcoin Cash в разделе TRANSACTIONS. 

Далее, я предположил, что, возможно, проблема в большом количестве транзакций в моем кошельке (хотя не так уж часто им пользуюсь и транзакций там мало).
Хотел зарегистрировать новый кошелек и посмотреть, будет ли там проблема с зависанием браузера, но потом вспомнил, что у меня уже есть ещё один кошелек blockchain.com, которым я давно не пользовался. Успешно авторизовавшись в нем, я без всяких проблем прошелся по всем разделам, включая Dashboard и TRANSACTIONS для Bitcoin и Bitcoin Cash. Список транзакций успешно открывался, нагрузка на CPU не превышала нормальных значений и ни разу не доходила до 100%.

Далее, я попытался выяснить, какой именно процесс вызывает зависание браузера.
С помощью «Диспетчера задач» я посмотрел какой процесс (и его PID) наиболее нагружает CPU в момент перехода в раздел сайта TRANSACTIONS для Bitcoin и Bitcoin Cash. Это, конечно, оказался firefox.exe
По номеру процесса (PID) с помощью утилиты ProcessMonitor (Procmon.exe) я посмотрел, с какими именно параметрами запускается этот процесс firefox.exe.

Command line следующая:
"C:\Program Files\Mozilla Firefox\firefox.exe" -contentproc --channel="1016.13.1405078328\533192267" -childID 2 -isForBrowser -prefsHandle 2172 -prefMapHandle 2176 -prefsLen 1 -prefMapSize 222189 -schedulerPrefs 0001,2 -parentBuildID 20181030165643 -greomni "C:\Program Files\Mozilla Firefox\omni.ja" -appomni "C:\Program Files\Mozilla Firefox\browser\omni.ja" -appdir "C:\Program Files\Mozilla Firefox\browser" - 1016 "\\.\pipe\gecko-crash-server-pipe.1016" 2188 tab

Как видим, происходит вызов C:\Program Files\Mozilla Firefox\browser\omni.ja (в свойствах процесса, в строке path указан тот же путь). 

На странице для разработчиков есть описание структуры этого файла omni.ja:
https://developer.mozilla.org/en-US/docs/Mozilla/About_omni.ja_(formerly_omni.jar)
Файл omni.ja содержит различные ресурсы Firefox, в том числе модули для работы с JavaScript.

В результате я сделал следующий вывод: проблема нагрузки 100% на CPU возникает именно в момент получения списка транзакций. Причём, чем больше было транзакций, тем больше и дольше будет загружен CPU непонятной работой.
Основной вопрос: почему происходит повышенная нагрузка на CPU? Ведь нужно всего лишь запросить список транзакций из некоторой базы данных и вывести их на экран.  
Затрудняюсь сказать, с чем это связано, но, учитывая то, что при работе с сайтом blockchain.com используется JavaScript, предполагаю, что запросы происходят не совсем корректно.

Буду рад, если вышеописанное как-то поможет локализовать и решить проблему.
Если нужны какие-то дополнительные данные, напишите. Постараюсь их собрать.

**Comment by aleksfomm** [comment]
Здравствуйте! Появилось ещё одно предположение из-за чего происходит зависание браузера, особенно в момент получения списка транзакций.
На днях отправлял биткоины на другой свой кошелек blockchain.com и обратил внимание, что часть транзакций, относящихся к моему кошельку-отправителю, имеет большое количество выходов (получателей). 
Скорее всего это были транзакции с массовыми выплатами от различных биткоин-проектов (в частности, с кранов).
Может быть, я ошибаюсь, но появилась мысль, что когда кликаешь в кошельке на раздел TRANSACTIONS, движок сайта blockchain.com (или модуль, предназначенный для получения списка транзакций) начинает искать мои биткоин-адреса во всех имеющихся транзакциях. И это приводит к заморозке браузера, потому что это занимает много времени из-за того, что мои адреса присутствуют в транзакциях с множественными выплатами (там сотни адресов в одной транзакции).
Пример такой транзакции:
https://www.blockchain.com/en/btc/tx/246ebb33ddc32c278b0fbbc4adac8c59514a61b863611ea5f6f3580a8e5f8203
Более наглядно (для меня):
https://chain.so/tx/BTC/246ebb33ddc32c278b0fbbc4adac8c59514a61b863611ea5f6f3580a8e5f8203

Transaction Details:
# of Inputs: 1
# of Outputs: 978

Возможно, я не прав, так как не знаю логику работы сайта. Но если это возможно, проверьте, пожалуйста, может ли описанная ситуация влиять на скорость получения списка транзакций и на заморозку браузера. 
А если это действительно может иметь значение, то есть ли способ ускорить в кошельке получение списка транзакций такого типа (один вход - много выходов, один отправитель - много получателей)? Спасибо.

**Comment by tony-blockchain** [comment]
@aleksfomm thanks a lot for a detailed report!
Large amount of outputs is most probably why your tx list freezes instead of just being slow.

Real source of trouble is that tx list gets processed upon every redux state change.
Attached PR #1355 addresses the problem by moving the heavy processing to saga, which gets called exactly once per tx list load.
Will keep you updated when this problem is solved!

**Comment by plondon** [comment]
@aleksfomm Hi sorry for the delay but we just deployed a new wallet version, let me know if you're still experiencing the issue. Closing the issue.

**Comment by aleksfomm** [comment]
Hi! Wallet now works better.
Do you moved the heavy processing to saga, which gets called exactly once per tx list load (Attached PR #1355)?

**Comment by plondon** [comment]
Yup!
