### ISSUE TITLE
My identification is under review for long time

### ISSUE THREAD

**Issue by umarjan9858** [blockchain/blockchain-wallet-v4-frontend#1135]
#It shows  we have problem while verifying yout document you submitted for verification, our support team will contact you shortly . Plz help me

**Comment by schnogz** [comment]
Our support team is working diligently to get to all of these requests. They should contact you both in a few days. Thank you for your patience.

**Comment by juninho81** [comment]
o problema é que vcs deram apenas uma semana para receber os xlm veio o email do premio mais nao posso confirma meus documentos por causa que vcs deixaram em revisao
