### ISSUE TITLE
mail address error

### ISSUE THREAD

**Issue by ivanovkonstantin12** [blockchain/blockchain-wallet-v4-frontend#1137]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.
![image](https://user-images.githubusercontent.com/45007863/48421514-759e3c00-e77e-11e8-84cd-4e8d9c3b1976.png)

why does it indicate an error? how do I verify my Russian passport?

**Comment by plondon** [comment]
<img width="834" alt="screen shot 2018-11-19 at 10 15 26 am" src="https://user-images.githubusercontent.com/5640772/48715890-0f814100-ebe4-11e8-8911-540e78220204.png">

That zip worked for me so I am closing, please reopen if the issue persists with more information

**Comment by ivanovkonstantin12** [comment]
I did. Filled in all the fields, clicked the next button, but nothing
happens.

пн, 19 нояб. 2018 г. в 20:13, Philip London <notifications@github.com>:

**Comment by plondon** [comment]
Hmm. Can you open the network tab in your console and inspect the exact error?

Here's instructions on opening console in case: https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers

**Comment by ivanovkonstantin12** [comment]
I'm using the Russian Yandex browser, it is possible for this error?

пн, 19 нояб. 2018 г. в 20:21, Philip London <notifications@github.com>:

**Comment by plondon** [comment]
I don't think the browser is the issue here.

After entering your address manually and submitting is there any error or does the request just load infinitely?

**Comment by ivanovkonstantin12** [comment]
[image: image.png]


I click continue and nothing happens

пн, 19 нояб. 2018 г. в 18:33, Philip London <notifications@github.com>:

**Comment by ivanovkonstantin12** [comment]
[image: image.png]
[image: image.png]

пн, 19 нояб. 2018 г. в 18:33, Philip London <notifications@github.com>:

**Comment by ivanovkonstantin12** [comment]
/#/login/02061cc2-d7ad-4cdb-82ad-7922f6627180:20 Refused to execute inline
script because it violates the following Content Security Policy directive:
"script-src 'self' 'sha256-ZqcQrm/X6RZZpk9srkG8XMOtegGAsulDV3WuCH2U+90='".
Either the 'unsafe-inline' keyword, a hash
('sha256-yZmdgVvzROiMMhereftUxrofbQsrGpeQmdlyusoGIp4='), or a nonce
('nonce-...') is required to enable inline execution.

app.edbbbf5a67.js:1 =======================================================
app.edbbbf5a67.js:1  Wallet version 4.5.3
app.edbbbf5a67.js:1 =======================================================
app.edbbbf5a67.js:1  STOP!!
app.edbbbf5a67.js:1  This browser feature is intended for developers.
app.edbbbf5a67.js:1  If someone told you to copy-paste something here,
app.edbbbf5a67.js:1  it is a scam and will give them access to your money!
7[Intervention] Slow network is detected. See <URL> for more details.
Fallback font will be used while loading: <URL>
blockchain.info/wallet/02061cc2-d7ad-4cdb-82ad-7922f6627180?api_code=1770d5d9-bcea-4d28-ad21-6cbd5be018a8&ct=1542645894503&format=json&resend_code:1
Failed to load resource: the server responded with a status of 500 ()
horizon.stellar.org/accounts/GBGSYSDEW6OWH5EI634RF5ECNYE66O66KNCCE4IKDRJ5CTTNWMZLABPM/transactions?order=desc&limit=1&c=0.5918146541812308:1
Failed to load resource: the server responded with a status of 404 (Not
Found)
vendor.dbc771a845.js:34 Refused to apply inline style because it violates
the following Content Security Policy directive: "style-src 'self'
'nonce-93ed0d4c1281781061618941b8afe5a4'". Either the 'unsafe-inline'
keyword, a hash ('sha256-97o4u6NOOXKKCCQ/RV8J53F81vXBBOI8bZ5/3dfFuLs='), or
a nonce ('nonce-...') is required to enable inline execution.

e.attr @ vendor.dbc771a845.js:34
vendor.dbc771a845.js:34 Refused to apply inline style because it violates
the following Content Security Policy directive: "style-src 'self'
'nonce-93ed0d4c1281781061618941b8afe5a4'". Either the 'unsafe-inline'
keyword, a hash ('sha256-7wj/+4oyhC/Un8WKFeS81vcvueSVhV/Hk8Tuw/NlDC8='), or
a nonce ('nonce-...') is required to enable inline execution.

e.attr @ vendor.dbc771a845.js:34
vendor.dbc771a845.js:34 Refused to apply inline style because it violates
the following Content Security Policy directive: "style-src 'self'
'nonce-93ed0d4c1281781061618941b8afe5a4'". Either the 'unsafe-inline'
keyword, a hash ('sha256-xoNN63L9AAEOpg5YcXPLo/hZsa/ms6XGntW9P4Bv2J0='), or
a nonce ('nonce-...') is required to enable inline execution.

e.attr @ vendor.dbc771a845.js:34
vendor.dbc771a845.js:34 Refused to apply inline style because it violates
the following Content Security Policy directive: "style-src 'self'
'nonce-93ed0d4c1281781061618941b8afe5a4'". Either the 'unsafe-inline'
keyword, a hash ('sha256-7wj/+4oyhC/Un8WKFeS81vcvueSVhV/Hk8Tuw/NlDC8='), or
a nonce ('nonce-...') is required to enable inline execution.

e.attr @ vendor.dbc771a845.js:34
vendor.dbc771a845.js:34 Refused to apply inline style because it violates
the following Content Security Policy directive: "style-src 'self'
'nonce-93ed0d4c1281781061618941b8afe5a4'". Either the 'unsafe-inline'
keyword, a hash ('sha256-xoNN63L9AAEOpg5YcXPLo/hZsa/ms6XGntW9P4Bv2J0='), or
a nonce ('nonce-...') is required to enable inline execution.

e.attr @ vendor.dbc771a845.js:34
10Refused to apply inline style because it violates the following Content
Security Policy directive: "style-src 'self'
'nonce-93ed0d4c1281781061618941b8afe5a4'". Either the 'unsafe-inline'
keyword, a hash ('sha256-wVRVBkd2jaDMh2DVCDIh93vMtsiXAwJw15vIumLFhaw='), or
a nonce ('nonce-...') is required to enable inline execution.

horizon.stellar.org/accounts/GBGSYSDEW6OWH5EI634RF5ECNYE66O66KNCCE4IKDRJ5CTTNWMZLABPM?c=0.858869369890231:1
Failed to load resource: the server responded with a status of 404 (Not
Found)
horizon.stellar.org/accounts/GBGSYSDEW6OWH5EI634RF5ECNYE66O66KNCCE4IKDRJ5CTTNWMZLABPM/transactions?order=desc&limit=10&c=0.1506192477653705:1
Failed to load resource: the server responded with a status of 404 (Not
Found)
horizon.stellar.org/accounts/GBGSYSDEW6OWH5EI634RF5ECNYE66O66KNCCE4IKDRJ5CTTNWMZLABPM?c=0.7323404266384921:1
Failed to load resource: the server responded with a status of 404 (Not
Found)
api.blockchain.info/nabu-gateway/users/check:1 Failed to load resource: the
server responded with a status of 404 ()
2api.blockchain.info/eth/latestblock?api_code=1770d5d9-bcea-4d28-ad21-6cbd5be018a8&ct=1542646033476:1
Failed to load resource: the server responded with a status of 504 ()
/#/settings/profile:1 Access to fetch at '
https://api.blockchain.info/eth/latestblock?api_code=1770d5d9-bcea-4d28-ad21-6cbd5be018a8&ct=1542646033476'
from origin 'https://login.blockchain.com' has been blocked by CORS policy:
No 'Access-Control-Allow-Origin' header is present on the requested
resource. If an opaque response serves your needs, set the request's mode
to 'no-cors' to fetch the resource with CORS disabled.
api.blockchain.info/nabu-gateway/users:1 Failed to load resource: the
server responded with a status of 409 ()
vendor.dbc771a845.js:98 uncaught at createUser Object
log @ vendor.dbc771a845.js:98
6api.blockchain.info/nabu-gateway/users/current:1 Failed to load resource:
the server responded with a status of 401 ()

пн, 19 нояб. 2018 г. в 18:33, Philip London <notifications@github.com>:

**Comment by plondon** [comment]
```api.blockchain.info/nabu-gateway/users:1 Failed to load resource: the
server responded with a status of 409 ()
vendor.dbc771a845.js:98 uncaught at createUser Object
log @ vendor.dbc771a845.js:98
6api.blockchain.info/nabu-gateway/users/current:1 Failed to load resource:
the server responded with a status of 401 ()
```

**Comment by plondon** [comment]
Deleted your above comment because it contains your guid which you should not share. The issues is with the 409 from nabu-gateway

**Comment by plondon** [comment]
@tony-blockchain I think this is indicating you already have created an account?

**Comment by tony-blockchain** [comment]
@ivanovkonstantin12 Can it be that you already have initiated kyc on different account with the same mobile number?

**Comment by ivanovkonstantin12** [comment]
You mean I've already been verified ?

пн, 19 нояб. 2018 г. в 20:59, Tony Popov <notifications@github.com>:

**Comment by plondon** [comment]
Or you have _started_ the kyc process on another wallet. Is this your _only_ blockchain wallet?

**Comment by ivanovkonstantin12** [comment]
This wallet was for mail kost_scorpo@mail.ru. I created it long ago, maybe
I started the verification process. I recently changed my mail.

пн, 19 нояб. 2018 г. в 19:12, Philip London <notifications@github.com>:

**Comment by ivanovkonstantin12** [comment]
what am I supposed to do now? Help me

пн, 19 нояб. 2018 г. в 19:12, Philip London <notifications@github.com>:

**Comment by plondon** [comment]
Please file a ticket with support (http://support.blockchain.com), if you started the verification process on another wallet and then try to use the same information to verify on a separate wallet it won't work because that info is already associated with a different wallet.
