### ISSUE TITLE
why does my memo wallet address not have a memo? And I want to send a station but it always addresses incorrectly

### ISSUE THREAD

**Issue by scarecrow9** [blockchain/blockchain-wallet-v4-frontend#1140]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by scarecrow9** [comment]
Halo admin, maaf saya salah mengetik tentang "stasiun" ..
Yang saya maksud adalah tidak adanya memo di alamat dompet XLM saya?
Dan mengapa saya tidak mendapatkan bonus $ 25 dalam bentuk Stellar?
Terima kasih

Pada tanggal Sen, 19 Nov 2018 pukul 21.26 Philip London <
notifications@github.com> menulis:

**Comment by scarecrow9** [comment]
Hello admin, sorry I typed wrong about "station" ..
What I mean is the absence of a memo in my XLM wallet address?
And why haven't I got a $ 25 bonus in Stellar form?
thank you

Pada tanggal Sel, 20 Nov 2018 pukul 00.42 Sandro Sitanggang <
sandro.stg08@gmail.com> menulis:

**Comment by plondon** [comment]
> And why haven't I got a $ 25 bonus in Stellar form?

Did you:
1. join the waitlist
2. receive claim your xlm email
3. verify your identity
