### ISSUE TITLE
I am not recieve my XLM

### ISSUE THREAD

**Issue by sadness4me** [blockchain/blockchain-wallet-v4-frontend#1141]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by leandroxxx** [comment]
Hello, i have create my wallet, submited my docs and it is already verified but i dont received my xlm yet, my email is leandro6531@hotmail.com. Link of the proof: https://imgur.com/sw1y68V

**Comment by meiji488** [comment]
Wew

**Comment by vman211** [comment]
Me too
How get xlm??

**Comment by Amrik53** [comment]
💌

**Comment by rbzala987** [comment]
Hello, i have create my wallet, submited my docs and it is already verified but i dont received my xlm yet, my email is Rinkalzalavadiya468@gmail.com
Plz help me

**Comment by schnogz** [comment]
Here is a [document](https://support.blockchain.com/hc/en-us/articles/360019105991-I-have-a-Blockchain-wallet-Why-didn-t-I-get-XLM-) that outlines the full signup and airdrop process.  

Please ensure you have completed all tasks and meet the requirements to receive XLM. If you have, then there is a form at the bottom of the article to file another request with our support team.

Thanks for your patience 🙌

**Comment by rbzala987** [comment]
Hello, i have create my wallet, submited my docs and it is already verified but i dont received my xlm yet, my email is 
Rinkalzalavadiya468@gmail.com
