### ISSUE TITLE
my information has been still underview

### ISSUE THREAD

**Issue by in8426** [blockchain/blockchain-wallet-v4-frontend#1149]
Hello, I have not received XLM. I guess the reason why it happened is that my verification process has not done. So would you mind letting me know how long I need to wait for it? My wallet id is [ e0803e3b-a813-4853-ace7-3dd20bf8839c ]  
If you need something more , please tell me what's needed. I can give you more specific information about me if you want. Thank you for your sincerity and effort.

**Comment by schnogz** [comment]
Your verification is most likely under a manual review and should be processed soon as our teams are working diligently to get reviews done.  Here is a [document](https://support.blockchain.com/hc/en-us/articles/360019105991-I-have-a-Blockchain-wallet-Why-didn-t-I-get-XLM-) outlaying the process a little more clearly.

Thanks for your patience. 🙌

**Comment by schnogz** [comment]
If you havent received your airdrop within the next week. Please file a ticket without our support team [here](https://support.blockchain.com/hc/en-us/requests/new?ticket_form_id=360000210932).
