### ISSUE TITLE
Postcode lookup error on Identity Verify

### ISSUE THREAD

**Issue by atlounge** [blockchain/blockchain-wallet-v4-frontend#1151]
# 🐛 Bug Report 🐛

## Description
When selecting France in the list of countries, the filling of the postcode returns an error "Oops, address lookup failed. Try again?".
Even when filling manually the addresse details, it's impossible to validate the form because of the PostCode error.

## Expected Behavior
The postcode is recognized and the form can be submitted

## Reproduction Steps
Select France, type 06570 (or whatever french postcode with 5 digits - ex. 75000 paris or 06000 nice)

## Screenshots/Logs
![bc](https://user-images.githubusercontent.com/677049/48624401-99df6000-e9ac-11e8-89e9-1d75d933b2b1.jpg)

**Comment by atlounge** [comment]
ok, same as 1137, closing this one and adding data on the other one.

**Comment by plondon** [comment]
Thanks!
