### ISSUE TITLE
cannot get my Stellar at the following?

### ISSUE THREAD

**Issue by longho007** [blockchain/blockchain-wallet-v4-frontend#1154]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by helpme67** [comment]
GCHH5VSVLJRS4DIV6CTLPLB2FNHE3YBFRNG7K2JXCVU57ZXD5AD2XGOS

**Comment by schnogz** [comment]
Here is a document that outlines the full signup and airdrop process.

Please ensure you have completed all tasks and meet the requirements to receive XLM. If you have, then there is a form at the bottom of the article to file another request with our support team.

Thanks for your patience 🙌
