### ISSUE TITLE
Identity Verification (In Review)

### ISSUE THREAD

**Issue by mikeki0209** [blockchain/blockchain-wallet-v4-frontend#1156]
# 🐛 Bug Report 🐛

## Description
Identity Verification (In Review): 

## Expected Behavior
It's been over 5 hours under this condition " Identity Verification (In Review)".

## Screenshots/Logs
![capture](https://user-images.githubusercontent.com/36309430/48667323-0e3b0180-ea88-11e8-9a05-c7a6900f6f8a.JPG)

## Additional Information
I have two blockchain ID under same my email account.  this cause pending problem like this?

**Comment by mikeki0209** [comment]
In this case, can i receive some BTC on my btc wallet from the other one?

**Comment by prasadravindra** [comment]
My I'd in review plz activate my I'd my email: prasadguptaravindra@gmail.com

**Comment by prashantth** [comment]
My id in review plz activate my id my email
hvrkrr1@gmail.com

**Comment by schnogz** [comment]
Here is a document that outlines the full signup and airdrop process.

Please ensure you have completed all tasks and meet the requirements to receive XLM. If you have, then there is a form at the bottom of the article to file another request with our support team.

Thanks for your patience 🙌
