### ISSUE TITLE
Remove postcode requirement from non-postalcode countries

### ISSUE THREAD

**Issue by Wongang** [blockchain/blockchain-wallet-v4-frontend#1157]
# 🐛 Bug Report 🐛

## Description
In the country i leave there aint postcode so i have to feel the address manually 

## Expected Behavior
After i have filled all the provided items and select continue nothing happens there after

## Reproduction Steps
names 
Date of birth
Address 
and all there steps that follow

## Screenshots/Logs
I cant provide screen shots at the moment

## Additional Information
i would love to complete #step 1 and process to step 2

**Comment by plondon** [comment]
We will work on adding a list of countries that don't have postcodes so we don't require them uniformly based on this list https://gist.github.com/bradydan/e172c3f99e211e6e47ad84f08f83dfe3

**Comment by hangchibi** [comment]
I do not know my identity, please help me

**Comment by Wongang** [comment]
Greetings,
We are supposed to verify our identification as required by block chain, if
you say this will be sorted out in the future then how are we supposed to
complete the task at hand, i do not want to miss out on because my identity
is not verified
thanks

**Comment by Catwoman96** [comment]
hello, I beg to agree to my identity

Email: Ranggaprawira214@gmail.com

**Comment by artur17171** [comment]
hello, I beg to agree to my identity

Email: artur.vetroff2017@yandex.ru

**Comment by namthanh99** [comment]
hello my registration on the 17th, and so far not approved yet
thank you 
Your Wallet ID: 772df46d-0537-4f0e-8466-88aac4b642d6

**Comment by abedzell** [comment]
hello my registration on the 16th, and so far not approved yet
My email : meepoplayer13@gmail.com
Wallet id : 2e3835a3-4d92-438d-8d65-d7629d41b53a
Thanks

**Comment by fahriromadan** [comment]
> # 🐛 Bug Report 🐛
> ## Description
> In the country i leave there aint postcode so i have to feel the address manually
> 
> ## Expected Behavior
> After i have filled all the provided items and select continue nothing happens there after
> 
> ## Reproduction Steps
> names
> Date of birth
> Address
> and all there steps that follow
> 
> ## Screenshots/Logs
> I cant provide screen shots at the moment
> 
> ## Additional Information
> i would love to complete #step 1 and process to step 2### verifikasi akun blockhain fahriromadan@gmail.com

**Comment by fahriromadan** [comment]
plesae verifikasi akun blockhain wallet email: fahriromadan@gmail.com

**Comment by taduy1** [comment]
Please complete my KYC verification. I have done from 17/11 to now have no feedback. email: Taduy821993@gmail.com Please verify me.

**Comment by fahriromadan** [comment]
Please verifikasi me

Rab, 21 Nov 2018 pukul 23.01 taduy1 <notifications@github.com> menulis:

**Comment by DnHariz** [comment]
Hi admin I have waited a few days but my KYC has not been approved . In progres status . Please accept my kyc . I need XLM bounty :(
My email : dnhariz@gmail.com
My wallet id : c81239ed-d83f-4e9a-91ba-e400f9fd9262

**Comment by Wongang** [comment]
Hey admin I would love to complete my registration and acquire my bounty of
XLM Stella please make this happen for my part for the world

**Comment by taduy1** [comment]
To complete the airdrop we need you to provide your application password.
If the kyc information and application passwords are the same as on the
airpass you will be able to get it done immediately.

Vào 20:36, Th 5, 22 thg 11, 2018 Wongang <notifications@github.com đã viết:

> Hey admin I would love to complete my registration and acquire my bounty of
> XLM Stella please make this happen for my part for the world
>

**Comment by atlounge** [comment]
> We will work on adding a list of countries that don't have postcodes so we don't require them uniformly based on this list https://gist.github.com/bradydan/e172c3f99e211e6e47ad84f08f83dfe3

Great news, but can you also update countries WITH postcodes that are not recognized? eg. France
Regards

**Comment by Wongang** [comment]
how soon can we have this done, we don't want to see the airdrop for the
XLM stella coins
thanks

**Comment by Rakib432** [comment]
Please approve my identity
I wait a long time
I want trading in wallet

Email: yudiastr@gmail.com

Thanks

**Comment by plondon** [comment]
This is in our current sprint

**Comment by plondon** [comment]
Fixed in this PR

https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/1554
