### ISSUE TITLE
Please check my kyC

### ISSUE THREAD

**Issue by Sabhri** [blockchain/blockchain-wallet-v4-frontend#1162]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
Hello,

Thanks for getting in touch! It’s great to hear that you are interested in verifying your identity with us. Below I have outlined how long you should expect the verification process to take.

All information and documents are reviewed by our automated system and/or dedicated staff. If the information you’ve submitted is clear and consistent, the process will be much faster. Automated verification should take around 5 minutes, but could take 2 hours or longer. If there are problems with the automated verification and the application requires manual review, the process could take up to 3-5 business days. Unfortunately we’re not able to fast track any applications. We will keep you updated and contact you if we need any extra information.

Best regards, and thank you for using Blockchain as your wallet provider!
