### ISSUE TITLE
Identity Verification Under Review

### ISSUE THREAD

**Issue by kuliahbsiaja** [blockchain/blockchain-wallet-v4-frontend#1163]
Good morning 
why is my account not yet approved even though I have verified the data mine 
my name is Jamaludin without having a last name 
but on the form must make a last name 
so I filled it in Jamaludin Jamaludin 
please correct the form. because many people who don't have a last name, including me. 
then when I want to upload my selfie I forgot to hold my identity, please let me verify again. 
and please accept my request to verify the account. thank you

**Comment by CaptiveON** [comment]
Is it normal to take more than 3 weeks to be verified at Golden Level? Kindly help!

**Comment by kuliahbsiaja** [comment]
Help me

Pada tanggal Jum, 10 Mei 2019 09.20, CaptiveON <notifications@github.com>
menulis:
