### ISSUE TITLE
Saldo xlm belum masuk sudah 3 hari

### ISSUE THREAD

**Issue by YudiSa** [blockchain/blockchain-wallet-v4-frontend#1190]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by junaidi029** [comment]
My email : junaidisangbelatituhan@gmail.com
