### ISSUE TITLE
15 day no xlm airdrop 😴

### ISSUE THREAD

**Issue by bynbnsr1** [blockchain/blockchain-wallet-v4-frontend#1195]
I have 3 Weeks Awaiting, already verified and confirmed in the list, this Airdrop is fake?😡🤬😡

bynbnsr1@gmail.com 
Ty good works

**Comment by plondon** [comment]
Ty good works?

**Comment by plondon** [comment]
Did you receive claim your xlm email?

**Comment by bynbnsr1** [comment]
yes i bought



26 Kas 2018 Pzt 19:54 tarihinde Philip London <notifications@github.com>
şunu yazdı:
