### ISSUE TITLE
Hi, I have successfully created Blockchain Wallet, why have not I received the XLM in my Wallet yet? Please take a look, my Mail Wallet is: phannhut3773@gmail.com

### ISSUE THREAD

**Issue by Thuy86** [blockchain/blockchain-wallet-v4-frontend#1196]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by Thuy86** [comment]
Hi, I have successfully created Blockchain Wallet, why have not I received the XLM in my Wallet yet? Please take a look, my Mail Wallet is: phannhut3773@gmail.com

**Comment by Evan101A** [comment]
Hi, I have successfully created Blockchain Wallet and also verify my email id, kyc and phone verify.  why have not I received the XLM in my Wallet yet? Please take a look, my Mail Wallet is: a.h.evan103@gmail.com
