### ISSUE TITLE
Nothing Claim XLM

### ISSUE THREAD

**Issue by DnHariz** [blockchain/blockchain-wallet-v4-frontend#1202]
## 🐛Bug Report 🐛

Hei admin @plondon 
1 . I on wait list at 21 November 2018
 
![screenshot_2018-11-26-21-51-44-702_com google android gm](https://user-images.githubusercontent.com/45255913/49021828-18ff4000-f1c6-11e8-979a-5fe504f216e7.png)

2. I verifikasi KYC on 24 November 2018 
![screenshot_2018-11-26-21-46-41-616_com google android gm](https://user-images.githubusercontent.com/45255913/49021911-4350fd80-f1c6-11e8-9755-99a00502148a.png)

3 . Succes verifikasi I claim XLM bounty . My XLM on the way but I don't receive XLM and Don't receive email XLM claim  ! This so disapointed for me ! 
![screenshot_2018-11-26-21-47-26-260_piuk blockchain android](https://user-images.githubusercontent.com/45255913/49022258-fe799680-f1c6-11e8-9a89-4e84cf108631.png)

**Comment by hedy888** [comment]
Hello admin...i have same issue,,,
Can you help me?
