### ISSUE TITLE
Bitcoin wallet

### ISSUE THREAD

**Issue by vjik71** [blockchain/blockchain-wallet-v4-frontend#1204]
My wallet is empty. After the site has been reworked by your employees. Where did the bitcoin money go?

**Comment by Mondei1** [comment]
I'm not a part of the Blockchain team but I like to help. Did you wrote your 12 words down somewhere? I think it's a bug or something but in the worst scenario you can use your 12 words and import your wallet in [Electrum](https://electrum.org/) or in [other software wallets](https://bitcoin.org/en/choose-your-wallet). So your funds are definitely not gone.

But If you haven't, what did you tried to fix it? Refreshed the site or did you waited a day? Blockchain.com is definitely not able to remove funds from your wallet without you actually performed the action.

**Comment by plondon** [comment]
Like @Mondei1 said we don't have access to make transactions on your behalf.
