### ISSUE TITLE
4 day no xlm and airdrop email but my account has been verifikasi..

### ISSUE THREAD

**Issue by Aokizie** [blockchain/blockchain-wallet-v4-frontend#1206]
# 🐛 Bug Report 🐛

My email : faridm0028@gmail.com
![my balance xmr not come from 4 day ago](https://user-images.githubusercontent.com/45293991/49061588-ab91f480-f243-11e8-9d00-f89c3a2afd6f.png)
![this](https://user-images.githubusercontent.com/45293991/49061589-ac2a8b00-f243-11e8-9949-271deab843fc.png)

**Comment by Aokizie** [comment]
My email : faridm0028@gmail.com
ID : a5a7cda6-0ba0-4160-b599-66f0cb437942

**Comment by plondon** [comment]
You have not received claim your xlm email. Please wait for that email

**Comment by Aokizie** [comment]
okay sir
