### ISSUE TITLE
I registered my wallet. When I got Bitcoin, I ordered the copy address. But we didn't confirm the production address, we transferred the Bitcoin to that account. I haven't arrived yet. I don't know what to do, help. help me!

### ISSUE THREAD

**Issue by aa0135303** [blockchain/blockchain-wallet-v4-frontend#1220]
# 🐛Bug Report 🐛
***Do***
1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
Failure to follow the do's and don'ts will result in us closing the issue without further dialogue

**Comment by aa0135303** [comment]
帮帮我 我不知道怎么样才能获得我的比特币

**Comment by aa0135303** [comment]
能帮帮我吗 


我不知道怎么跟网站的人员取得联系， 我的比特币一直都没有收到我的钱包里面 它们都还在那个钱包生产的地址里面，我没有办法把它们变成我个人的


------------------ 原始邮件 ------------------
发件人: "Philip London"<notifications@github.com>;
发送时间: 2018年11月29日(星期四) 晚上8:54
收件人: "blockchain/blockchain-wallet-v4-frontend"<blockchain-wallet-v4-frontend@noreply.github.com>;
抄送: "奉命行事"<517371016@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [blockchain/blockchain-wallet-v4-frontend] I registered mywallet. When I got Bitcoin, I ordered the copy address. But we didn't confirmthe production address, we transferred the Bitcoin to that account. I haven'tarrived yet. I don't know what to do, help. help me! (#1220)




Failure to follow the do's and don'ts will result in us closing the issue without further dialogue
