### ISSUE TITLE
20 days No XLM

### ISSUE THREAD

**Issue by bynbnsr1** [blockchain/blockchain-wallet-v4-frontend#1224]
09 november airdrop wait list
Now 29 november 0 XLM

GA5TGER3D2OQ5CHM4FVC2FTVQP2PUNICCABVBLAQVA24JR2HPJMCXBCS

Fake promotions?
https://i.hizliresim.com/EmzyvA.jpg

**Comment by plondon** [comment]
https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A

**Comment by bynbnsr1** [comment]
Thanks bro..

U are the best

30 Kas 2018 Cum 00:36 tarihinde Philip London <notifications@github.com>
şunu yazdı:

**Comment by danielaronss** [comment]
How to get xlm bro? Im verif 12 days ago
