### ISSUE TITLE
Ücretsiz XLM Neden gelmiyor?

### ISSUE THREAD

**Issue by ismailataser** [blockchain/blockchain-wallet-v4-frontend#1228]
Hesabım onaylanmasına rağmen Ücretsiz XLM Hala gelmedi ! Artık hesabıma geçmesini talep ediyorum

**Comment by ismailataser** [comment]
Mail gelmiyor. Ama hesabım onaylı.


![ekran alintisi](https://user-images.githubusercontent.com/45488703/49291306-8d7dfb80-f4b2-11e8-831e-e95728537957.JPG)

Mail gelmedi. 
![232323](https://user-images.githubusercontent.com/45488703/49291323-9a9aea80-f4b2-11e8-9fde-48146e0aeef9.JPG)

**Comment by plondon** [comment]
https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A

**Comment by ismailataser** [comment]
"you have not been chosen to receive the airdrop YET. Please be patient we will be distributing in batches" 

Bana "Claim Your XLM" Adında başvurduğum halde email gelmedi. Sabırla bekleyeceğim. Umarım gelir. Teşekkür ederim :)

**Comment by plondon** [comment]
If you've clicked the link you will receive your XLM soon.

**Comment by ismailataser** [comment]
Bağlantıya tıkladım ama email gelmiyor.
