### ISSUE TITLE
XLM distribution is unfair

### ISSUE THREAD

**Issue by DnHariz** [blockchain/blockchain-wallet-v4-frontend#1239]
##BUG REPORT

## Description

Now you can see! Why I waited a long time but got nothing. if indeed XLM is only for certain people please make an announcement! I have complained about customer service but it hasn't been there but there is no answer. how can people waiting from the 27november get faster XLM! I have waited from 21 november but got nothing. please make an announcement that XLM is only for certain people. because it really disappoints your customers. long wait but NOTHING
## Screenshots/Logs
![screenshot_2018-12-03-13-29-57-640_com google android gm](https://user-images.githubusercontent.com/45255913/49357558-3bcbb000-f702-11e8-9a64-ff1a8fcc24f4.png)
![screenshot_2018-12-03-13-30-22-017_com google android gm](https://user-images.githubusercontent.com/45255913/49357568-45551800-f702-11e8-92a0-a6f343ea4273.png)
![Uploading Screenshot_2018-12-03-13-30-54-637_com.facebook.orca.png…]()

![Uploading Screenshot_2018-12-03-13-31-01-855_com.facebook.orca.png…]()
![screenshot_2018-12-03-13-31-10-263_com facebook orca](https://user-images.githubusercontent.com/45255913/49357603-5e5dc900-f702-11e8-8d43-36252c8ea2ee.png)
![screenshot_2018-12-03-13-31-19-775_com facebook orca](https://user-images.githubusercontent.com/45255913/49357613-6584d700-f702-11e8-9405-700d0bbae910.png)
![screenshot_2018-12-03-13-31-31-309_com facebook orca](https://user-images.githubusercontent.com/45255913/49357620-6e75a880-f702-11e8-9588-653ce7a9a662.png)
![screenshot_2018-12-03-13-31-33-682_com facebook orca](https://user-images.githubusercontent.com/45255913/49357631-75042000-f702-11e8-801f-17fd04084cf8.png)

@plondon

**Comment by plondon** [comment]
@DnHariz there are no 'Claim Your XLM' emails there
