### ISSUE TITLE
QR-Code and dark mode aren't best friends

### ISSUE THREAD

**Issue by Mondei1** [blockchain/blockchain-wallet-v4-frontend#1252]
# 🐛Bug Report 🐛

## Description
Today I tried the dark mode an there is one error. I'm unable to scan the QR-Code to receive funds with the mobile version because the app doesn't detect the QR-Code when there is a black background. 

## Expected Behavior
Should scan the QR-Code with the app or any other QR-Code scanner.

## Reproduction Steps
1. Login to your wallet
2. Go to Settings -> Preferences -> Themes and choose 'DarkMode'
3. Click on 'Request' on the top of the site
4. Click by 'Copy & Share Address' on 'QR Code'
5. Try to scan the code with the mobile app of Blockchain

## Screenshots/Logs
Click [here](https://mega.nz/#!OARUVCCY!DP6xocRHS3ZAMR-vuygknI5F-Y_7iQZqiTOAW1OKv9o) to watch the 20 second video on Mega.nz.

## My suggestion for fix
Simply but  a white or light gray shadow on the QR-Code, so that QR-scanners can see what a QR-code is and what not.

## Additional Information
I tried this with [Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) too. My theme, my fault, sorry ^^

**Comment by plondon** [comment]
The trick is to wrap the qr codes in 1px white borders, lmk if you want to make a PR otherwise I can do it sometime next week.

**Comment by Mondei1** [comment]
I'll take a look. I mean it's just CSS.

**Comment by Mondei1** [comment]
Oh sorry, I forgot it :cry:

**Comment by plondon** [comment]
No worries! Will be in next release
