### ISSUE TITLE
App cannot be served from non-whitelisted ip address

### ISSUE THREAD

**Issue by FrankoDanko** [blockchain/blockchain-wallet-v4-frontend#1278]
# 🐛Bug Report 🐛
## Description
Hello after (yarn) start the blockchain v4 wallet frontend it shows that:
 ｢wds｣: Project is running at http://localhost:8080/
and after building modules it shows:
｢wdm｣: Compiled successfully.

But i cant access the frontend via (serverip):8080.
Are there any solutions why i cant access ? I would be glad if there anyone can help me with this issue.
--------------------------------------
Debian GNU/Linux 8.11 (jessie)
Yarn version >= 1.12
Node version >= 10.2
installed necessary global packages

Yarn test output:
 | Test Suites: 107 passed, 107 total
 | Tests:       1204 passed, 1204 total
 | Snapshots:   79 passed, 79 total
 | Time:        276.146s
Done in 301.21s.

**Comment by plondon** [comment]
What is the error from the browser?

**Comment by FrankoDanko** [comment]
> What is the error from the browser?

There is no error code. Browser dont load anything.
Its shows like there no webserver configured.
Chrome Errocode: ERR_CONNECTION_REFUSED

**Comment by FrankoDanko** [comment]
Hello here i provide some screenshots.
Im sure that i access over http and not over https.
![1](https://user-images.githubusercontent.com/45827441/50010963-19b41680-ffbb-11e8-8838-01aac102847b.png)
![2](https://user-images.githubusercontent.com/45827441/50010973-1e78ca80-ffbb-11e8-9254-df4995bf5e48.png)

**Comment by plondon** [comment]
Can you access http://localhost:8080 (instead of your server ip?)

**Comment by FrankoDanko** [comment]
> Can you access http://localhost:8080 (instead of your server ip?)

No because the files are on the remote server.
I just found a fix. i replaced in some .js files "localhost" with "myserverip". Now i am able to access the website. 
But now i have another problem...
After filling out the Wallet Id and password i try to click on the Log-In button  but nothing happens.
And with nothing i mean nothing no browser authentication or somewhat.

**Comment by plondon** [comment]
Console screenshots, network error codes and responses, environment information please

**Comment by FrankoDanko** [comment]
Debian GNU/Linux 8.11 (jessie)
Yarn version >= 1.12
Node version >= 10.2

Console is the same as the screenshots above here is nothing changed. (except localhost = myserverip)

<img width="740" alt="screenshot_5" src="https://user-images.githubusercontent.com/45827441/50013487-8df1b880-ffc1-11e8-88b4-d39842d0aec4.png">

**Comment by plondon** [comment]
After speaking with a fellow dev, his suggestion was to try to use cors=true for those endpoints. Otherwise you may need an api key
