### ISSUE TITLE
Tor browser error on login

### ISSUE THREAD

**Issue by slrslr** [blockchain/blockchain-wallet-v4-frontend#1485]
[Download latest stable tor browser](https://www.torproject.org/projects/torbrowser.html.en#downloads) and try to login to wallet (via tor browser). It invite me to visit .onion address which does not load. When i somehow get to the login form on .com site (reloading page; or go to first signup form and then to login form), and submit the login form, it shows [this error](http://pastebin.com/aAD0CsrW)

**Comment by plondon** [comment]
Thanks for the report. I will investigate

**Comment by plondon** [comment]
The fix for the error in the ticket is coming in the next release, however I'm told our tor wallet isnt running anymore.

**Comment by slrslr** [comment]
It means that possibly within a few weeks i as a Tor browser user will not be prevented to use the .com wallet? (currently i can not use blockchain wallet at all in Tor browser, as described above)

**Comment by plondon** [comment]
Can you login on https://login.blockchain.com?

**Comment by slrslr** [comment]
Currently i switched OS and i am on Linux for next maybe a few weeks. Up to date 8.0.6 tor browser.

blockchain.com homepage Login button links to a https://login.blockchain.com/#/login URL which is a dead end, shows mentioned error "For improved security, please bookmark and access directly https://blockchainbdgpzk.onion/" (and .onion does not work as mentioned)

But when i manually input URL https://login.blockchain.com/ then the login form appeared and after submitting, there is [an error](https://pastebin.com/FFYA5RWX). When i click continue, it redirect me to mentioned dead end page https://login.blockchain.com/#/login

**Comment by abtif** [comment]
@plondon i cant login my account. When i login with my chrome browser. I receive the verification email. 
I click on it and it says error. Request timeout. Link expired. 

Support doesnt answer since 5 days. 

Please tell me how to fix this. I cant even login to send my btc.

**Comment by slrslr** [comment]
I am adding new information to my previous comment:
when i end up on https://login.blockchain.com/#/home i see incomplete wallet and "Something went wrong. Please refresh"
The developer console shows:
```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: 
      window.NONCE = '**CSP_NONCE**'
		.
TypeError: asm.js type error: Disabled by 'asmjs' runtime option
vendor.cbddccd9cd.js
=======================================================
app.d9566f2162.js:1:7335928
 Wallet version 4.13.8
app.d9566f2162.js:1:7335999
=======================================================
app.d9566f2162.js:1:7336052
 STOP!!
app.d9566f2162.js:1:7336123
 This browser feature is intended for developers.
app.d9566f2162.js:1:7336198
 If someone told you to copy-paste something here,
app.d9566f2162.js:1:7336267
 it is a scam and will give them access to your money!
app.d9566f2162.js:1:7336337
...
```

**Comment by essubroto** [comment]
Untuk masuk ke situs blockchain kadang memakai handpone dan kadang memakai komputer,  apakah itu berpengaruh pada kesalahan saat login?

**Comment by slrslr** [comment]
@blockchainjamie @guy-blockchain @jack-blockchain @tony-blockchain @jjBlockchain @plondon 
I see the problem continue in latest Tor browser on MS Windows and Blockchain wallet seems to be version 4.21.7
Please until this is fixed, at least remove mentioned redirect in case Tor browser is detected. Thus allowing Tor browser users to login. Thank you

**Comment by RScottLewis** [comment]
Does it fix this (See 500 error)?  I've had this account for quite a while. Unable to login.
[Error] Unrecognized Content-Security-Policy directive 'worker-src'.

[Error] Blocked a frame with origin "https://wallet-helper.blockchain.com" from accessing a frame with origin "https://login.blockchain.com". Protocols, domains, and ports must match.
	Q (js:41:1781)
	ab (js:73:338)
	addTracker (js:74:329)
	(anonymous function) (js:77:455)
	Global Code (js:78)
[Error] Failed to load resource: the server responded with a status of 500 () (2676b36e-f5c1-450d-a17d-37e25b2c0ae9, line 0)
[Error] Failed to load resource: the server responded with a status of 500 () (2676b36e-f5c1-450d-a17d-37e25b2c0ae9, line 0)
> Selected Element

**Comment by RScottLewis** [comment]
Ok, we added our server as an address. Could this have blocked all others?
Login attempt blocked
An attempt to access your My Wallet account has been blocked. For your own security please review the details below:

Time: 2019-09-13 14:31:46
IP Address: 69.117.184.9 (United States)
User Agent: Chrome
Reason: This wallet is restricted to another IP address. To remove this restriction, submit a 2FA reset request under Login Help. 

If this login attempt was made by you, this email can be safely ignored. If this attempt was not made by you, somebody may be trying to access your wallet and we recommend that you change your password as soon as possible.
