### ISSUE TITLE
WEB Login Problem 

### ISSUE THREAD

**Issue by poroxa** [blockchain/blockchain-wallet-v4-frontend#1616]
I can't login from web browser. I have access from mobile app, but every try to access from web is unsuccessful, acctually freezes/hangs... everything works fine, I can recieve verification mail, sms code but after clicking login button, it blinking and does not enter, just keeps it all day long... Tried different browsers, PC-s, Mobile browsers, IP-s... nothing works, Tried my friends account from My pc&browser and it works, mine not... IDK whats going on

**Comment by plondon** [comment]
Hey @poroxa. Can you provide some more details such as:

1. how old is your wallet?
2. how many imported addresses if any do you have?
3. how many btc accounts?
4. do you have any idea around when it stopped working?

Thanks

**Comment by poroxa** [comment]
1. about month or more
2. I have not imported adress
3. one btc account
4. I never tried to use web browser, always using mobile app, but accidiently I have some send erc20 and now want my private key, from app, it cant be possible, need web-login but cant

**Comment by plondon** [comment]
Hmm, quite strange.

Please try logging in with the following:
https://login.blockchain.com/#/open/log-level?level=verbose

The link will console.log errors, so hopefully whatever is happening will get caught there. Lmk if you need info about how to access your console etc.

Once you have some screenshots of all the console errors please file a support ticket and tell them to alert Phil London. I don't suggest posting the screenshots on github. Thanks

**Comment by poroxa** [comment]
I tried, of course, without success, but I have console screenshots, where I can to submit it? how can i open support ticket?

**Comment by plondon** [comment]
The log level flag won't fix the problem, but may help us diagnose.

Btw, do you have your recovery phrase?

**Comment by plondon** [comment]
https://support.blockchain.com

**Comment by poroxa** [comment]
heyyy, I can't open support ticket

**Comment by plondon** [comment]
Why not

**Comment by poroxa** [comment]
I replay u via mail about recovery phase, but not sure, you recieved it - I did it already with no luck

**Comment by poroxa** [comment]
Please, answer me via e-mail, I need help...
