### ISSUE TITLE
Date Input Box Component

### ISSUE THREAD

**Issue by mchlcrtz** [blockchain/blockchain-wallet-v4-frontend#1630]
# 🐛Bug Report 🐛

## Description
Date Input Box component experience when confirming personal details to get free XLM not ideal. 

## Expected Behavior
When entering a day and year, days start at 1 and have a range of 31 and years start at 19xx and end at 20xx. 

Selectors to change the day or year can change the year to increase the number and not just decrease the number (keyboard as well). 

When the input number selector is used, the input box displays whole numbers and not decimal. 

When decreasing the day, once the number reaches 10, the number does not go straight to 0 or empty but to single digits. 

When decreasing the year, once the decimal goes below 0, it does not affect the day input.

## Reproduction Steps
See the red box of the screen

<img width="1149" alt="Screen Shot 2019-05-18 at 12 36 05 PM" src="https://user-images.githubusercontent.com/34140729/57972550-56b97600-796a-11e9-9b5f-de05e15f3f5a.png">

shot

## Screenshots/Logs
See Attached
[Screen Recording 2019-05-18 at 12.27.29 PM.zip](https://github.com/blockchain/blockchain-wallet-v4-frontend/files/3194278/Screen.Recording.2019-05-18.at.12.27.29.PM.zip)

## Additional Information
There were no javascript errors in the console

**Comment by jakubusi** [comment]
Juj

**Comment by jakubusi** [comment]
Shit

**Comment by Milan-Popich** [comment]
Copyright Milan Popich all rights reserved
