### ISSUE TITLE
1 month no xlm airdrop 😴 

### ISSUE THREAD

**Issue by darkval99** [blockchain/blockchain-wallet-v4-frontend#1643]
I have been waiting for more than 1 month for the airdop but I do not get anything, I am approved with a gold level and the only text I have it's this : 
Hang tight, your XLM is on its way.

![Screenshot_5](https://user-images.githubusercontent.com/51228676/58692108-9767b500-8396-11e9-9f9b-00e5f227495f.png)

Email: blocktest99@gmail.com

**Comment by darkval99** [comment]
What ?

**Comment by plondon** [comment]
https://support.blockchain.com/hc/en-us/articles/360019105991-I-have-a-Blockchain-wallet-Why-didn-t-I-get-XLM-
