### ISSUE TITLE
Gold status approved!...or not? 

### ISSUE THREAD

**Issue by fe2pluss** [blockchain/blockchain-wallet-v4-frontend#1644]
# 🐛Bug Report 🐛
***Do***
1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.
Email:
RandiMLilly@mailsac.com

It says I am gold status approved yet I have not received the xlm Airdrop.  You have my sensitive information, so far it feels like a scam and if anything, motivates me to stay away from cryptocurrency-which I believe is opposite what you intended. 

What's the deal exactly?  Why haven't I received any responses to the tickets I've submitted?  I get it, $120,000,000 divided by $50 = a helluva lot of people to accommodate-however, this is a project YOU took on, not I.  I only did what was requested of me so as to receive the advertised airdrop.  Please don't treat us like we've made the mistake because so far the only mistake I feel we've done is to trust blockchain.com with our identities.  

I am using a shared device which has been used to sign up to block chain previously-could this be the cause? Do you need a video of me singing "O' blockchaintree, oh blockchaintree..." while holding up today's newspaper whilst hooked up to a lie detector and/or car battery?  Please give me a human response.  Thank you in andvance.

![Screenshot_20190530-210202](https://user-images.githubusercontent.com/50679481/58703546-df1e1a80-835d-11e9-9254-e2f502531c87.png)

**Comment by plondon** [comment]
https://support.blockchain.com/hc/en-us/articles/360019105991-I-have-a-Blockchain-wallet-Why-didn-t-I-get-XLM-

**Comment by fe2pluss** [comment]
I've already read that article dozens of times and it doesn't address the issue.  I am in fact in a supported region and j have been verified, but haven't received.
