### ISSUE TITLE
Verification my wallet.

### ISSUE THREAD

**Issue by eugenia1974** [blockchain/blockchain-wallet-v4-frontend#1648]
# 🐛Bug Report 🐛

## Description
I verified my wallet like 15 business day's ago and it's still "In Review" status.

**Comment by EvILsmILeee** [comment]
i w8 7days

**Comment by crazecdwn** [comment]
What is tht

**Comment by plondon** [comment]
I understand your frustration and I'm sorry, but there's nothing the developers on this project can do to help.

Please file a support.blockchain.com ticket
