### ISSUE TITLE
XLM DROP

### ISSUE THREAD

**Issue by PiNB00** [blockchain/blockchain-wallet-v4-frontend#1649]
# 🐛Bug Report 🐛

Today, opening my e-mail, I saw that there are two or more portagogli connected on Blockchain, maybe made by my children, wrongly.
Being the owner and having already verified the account thanks to the photos of the documents, I cannot receive the XLM DROP due to the external connection of other portfolios.
How can I eliminate them and keep mine as the only one?

**Comment by plondon** [comment]
Please open a ticket with support.blockchain.com
