### ISSUE TITLE
error during stellar verification

### ISSUE THREAD

**Issue by grace1919** [blockchain/blockchain-wallet-v4-frontend#1655]
after writing and verifying documents, I tried to get stellars but I encounter this error at the end as can be seen in the attached screenshot

![Screenshot (247)](https://user-images.githubusercontent.com/51399213/58939630-e9824f00-8777-11e9-9ee2-4fcea98b8643.png)

**Comment by grace1919** [comment]
I await explanations

**Comment by aniabzianidze** [comment]
i have the same problem. any solutions?

**Comment by MicrominesWallet** [comment]
I got verified and didn't receive any stellar. 
![Screenshot_6](https://user-images.githubusercontent.com/16358863/59077615-29d4f080-8890-11e9-8e2f-ed49c27c23c8.jpg)

**Comment by audrym** [comment]
I also have my account verified and I submit the same error.

Any solution

![image](https://user-images.githubusercontent.com/51472443/59084884-67eb0800-88c2-11e9-9fb1-6aec8e44db11.png)

**Comment by audrym** [comment]
My account appears verified, and when I try to order my stellar I get the error indicated above.

![image](https://user-images.githubusercontent.com/51472443/59085047-efd11200-88c2-11e9-8a24-ab43f3dd0500.png)
