### ISSUE TITLE
stellar lumens

### ISSUE THREAD

**Issue by daby33** [blockchain/blockchain-wallet-v4-frontend#1661]
Hello good Morning. I would like to know about the bonuses of my blocchaim wallet. About the donation of 25 U $ in stelar lumens. When will I receive it?

**Comment by asyachen** [comment]
Hi! I have no link to get bonuse of 25 dollars, can i get it and take bonuses?

**Comment by daby33** [comment]
Yes Yes. Why register in blockchaim, do you have whatsapp? Maybe I can guide you. I also have a telegram, and it's the same number: +5591985366117.
________________________________
De: asyachen <notifications@github.com>
Enviado: sexta-feira, 14 de junho de 2019 18:12
Para: blockchain/blockchain-wallet-v4-frontend
Cc: daby33; Author
Assunto: Re: [blockchain/blockchain-wallet-v4-frontend] stellar lumens (#1661)


Hi! I have no link to get bonuse of 25 dollars, can i get it and take bonuses?

**Comment by Marek19721972** [comment]
Mam pytanie kiedy otrzymam darmowe Stallery...dostałem 25$ w XLM,a miało  być 50$.Proszę o info.
