### ISSUE TITLE
Address Changing Not Good

### ISSUE THREAD

**Issue by beeres00** [blockchain/blockchain-wallet-v4-frontend#1670]
Please don't change our addresses make it static

**Comment by plondon** [comment]
BTC/BCH addresses change for each tx to increase your privacy.

With that said you can always:
1. create a pub/priv key pair via https://www.bitaddress.org
2. import the private key (wallet will figure out the public key)
3. receive and spend from this address, which is static

**Comment by plondon** [comment]
You can also always keep receiving to old addresses w/o any problems.
