### ISSUE TITLE
Identity verification 

### ISSUE THREAD

**Issue by VFN8** [blockchain/blockchain-wallet-v4-frontend#1675]
# 🐛Bug Report 🐛
***Do***
1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.
I am a verified block chain account holder. Buy sell limit is 10,000.00. Problem is when I attempt to add an account to fund purchases it is unable to verify my identity! It's as simple as your name, address, dob, and social security number. So what am I doing wrong here. I'd really like to purchase some crypto!!
## Expected Behavior
Explain what you would expect to happen.
I expect my identity to be verified since blockchain already did so with the account creation.
## Reproduction Steps
Enter detailed steps to reproduce the issue.
When I've filled in my info to add a acct. to fund purchases, I click on verify, and it says unable to verify.
## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by VFN8** [comment]
![Screenshot_20190618-095847](https://user-images.githubusercontent.com/51946543/59704139-46d2c300-91b0-11e9-8f08-db9998599ea4.png)

**Comment by VFN8** [comment]
I don't understand why is this closed, I did t get any help with the issue?

**Comment by plondon** [comment]
We are turning off this partner integration soon. There will be a different idv flow for buy/sell.
