### ISSUE TITLE
Error: Export usdt to bitcoin wallet address. 

### ISSUE THREAD

**Issue by hqs988** [blockchain/blockchain-wallet-v4-frontend#1679]
# 🐛Bug Report 🐛
***Do***
1. I export my 250 usdt to bitcoin address created in my blockchain wallet. 
2. I just found 0.05 $ in bitconin wallet.

what shall i do? 

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.
![1](https://user-images.githubusercontent.com/30251495/59753614-19bd0800-92b7-11e9-8200-a9080a34b9e6.PNG)

**Comment by khan19lc** [comment]
Yes parzh

**Comment by plondon** [comment]
Sounds like the issue is with #1
> I export my 250 usdt to bitcoin address created in my blockchain wallet.

How did you 'export' the 250 usdt?
