### ISSUE TITLE
Alert Phil London

### ISSUE THREAD

**Issue by poroxa** [blockchain/blockchain-wallet-v4-frontend#1694]
Hey, Phil... My issue still not fixed yet... I send you several e-mails, you did not answered... opened new ticket, after first answer, another helper disappeared like u... opened new one, again... same...
Can anyone help me?
I need to login via web browser, but still unable... I did everything you asked...

**Comment by plondon** [comment]
Hey, reaching out to support now.

**Comment by poroxa** [comment]
thanks, I just waiting them

**Comment by plondon** [comment]
May have to set up a timeframe tomorrow to get it done

**Comment by omari123** [comment]
thanks

**Comment by 2Valerich** [comment]
Спасибо

**Comment by plondon** [comment]
Issue resolved.
