### ISSUE TITLE
Не открывает Bitcoin баланс и wallet.

### ISSUE THREAD

**Issue by SamohvalovGMcR** [blockchain/blockchain-wallet-v4-frontend#1701]
Не открывает Bitcoin баланс и wallet.

Существует проблема с кошельком, и у этой страницы может быть ограниченная функциональность, например, могут не отображаться балансы.
Сообщение: Invalid Bitcoin Address

**Comment by plondon** [comment]
@tony-blockchain can you translate?

**Comment by plondon** [comment]
Translated via google. It may be an issue with an imported address, have you imported any public keys recently?

**Comment by SamohvalovGMcR** [comment]
long ago. Yes, it gave the error

**Comment by SamohvalovGMcR** [comment]
Случайно закрыл..

**Comment by SamohvalovGMcR** [comment]
how to fix?

**Comment by SamohvalovGMcR** [comment]
Так вы русский или нет?

**Comment by plondon** [comment]
Find the address in settings -> wallets and addresses and `archive` it

**Comment by SamohvalovGMcR** [comment]
tried. fail

**Comment by plondon** [comment]
Hmm, same error?

Can you use this link to login:
https://login.blockchain.com/#/open/log-level?level=verbose

Can you attach:
screenshots of the console
screenshots of the wallet with important information blacked out
any errors you see from the network

**Comment by SamohvalovGMcR** [comment]
press "Bitcoin", "Bitcoin Cash", "отправить", "получить" -  usual error page..

archive it - nothing changes.

**Comment by SamohvalovGMcR** [comment]
![image](https://user-images.githubusercontent.com/25407709/60422992-9a103100-9c06-11e9-8249-c078517c6f86.png)

**Comment by SamohvalovGMcR** [comment]
delete bad adress  - nothing changes 
archive all import adress - error abyss.. 
i wait small time verify.

**Comment by plondon** [comment]
Im surprised the issue persists with all imported addrs archived. Have you been using the wallet for a long time? Do you use it in conjunction with the API?

**Comment by plondon** [comment]
It would help to know the requests being made with the public keys to multiaddr, but you should not post them in this thread. You should open a support ticket and ask them to tag plondon

**Comment by SamohvalovGMcR** [comment]
after archive all imported adress and reload, all became normal. 
some had to be delete

**Comment by plondon** [comment]
Nice, closing
