### ISSUE TITLE
How do you collect or ask for payments on confirmations of a transfer?

### ISSUE THREAD

**Issue by Pohakanui** [blockchain/blockchain-wallet-v4-frontend#1714]
# 🐛Bug Report 🐛
***Do***
1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.
I am new and trying to teach myself with help from more knowledgeable cryppies

**Comment by ekene90** [comment]
Good transfer

**Comment by Pohakanui** [comment]
Sorry, I didn't get that?

**Comment by schnogz** [comment]
What exactly are you asking about?

**Comment by Pohakanui** [comment]
While looking at a blockchain, there are usually a ton of payouts from
wallets that have like 10k+ bitcoin...how do you get some from the button
that says request or donate on it, I've done a ton of requests, but never
was sent anything...how do you get in on getting a payout from like a
mining company?
