### ISSUE TITLE
[Feature] Support for Vivaldi browser

### ISSUE THREAD

**Issue by rivermont** [blockchain/blockchain-wallet-v4-frontend#1723]
When trying to access the wallet, the login page displays this error: `YOUR BROWSER IS NOT SUPPORTED. PLEASE UPDATE TO AT LEAST CHROME 45, FIREFOX 45, SAFARI 8, EDGE, OR OPERA.`

Vivaldi is a Chromium-based browser like Google Chrome, Microsoft Edge, and Opera. I am using version 2.5.1525.48 on Windows 10 64-bit.

**Comment by schnogz** [comment]
Thanks for the feedback/request.  I will look into allowing the browser now.

**Comment by schnogz** [comment]
Vivaldi will be available with our next release which will be within the next 2 weeks. Marking closed.
