### ISSUE TITLE
I tried to buy bitcoins and lost my money

### ISSUE THREAD

**Issue by darksky25** [blockchain/blockchain-wallet-v4-frontend#1730]
# 🐛Bug Report 🐛

I need help.
I intended to buy 100 euro worth of bitcoins in 7 June of 2019.
So i did the order and sent my money (bank transfer)
I waited several days and nothing happened. My money went through, i lost my 100,25 euros cause i needed to pay those extra 25 cents. And i didnt receive any bitcoins.
Its been 1 month and 2 weeks and i got no response on my request.
I would be chill, but the order expired i don't know why.
The order was sent in 7 June and the money went through on 9 June.
This is an extract of my bank account where it shows my bank transfer. It's in Portuguese but it shows the iban and the bank transfer.
And there is the bug i think.
![Sem Título](https://user-images.githubusercontent.com/53023311/61418057-2c941e00-a8f1-11e9-9fe0-b0eea86f0645.png)
![Screenshot_20190718-001146](https://user-images.githubusercontent.com/53023311/61418083-40d81b00-a8f1-11e9-9c6f-e52065ccb72a.png)

I need my money back or the amount of bitcoins i intended to purchase.
Thank you for your attention.

**Comment by plondon** [comment]
Let me reach out to coinify, who is our partner that handles buy/sell in the EU. You're saying you sent 100 EUR instead of 100.25 EUR?

**Comment by darksky25** [comment]
It was blockchain, blockchain did it all.
No, i sent 100.25 as it says.
My money went through but i never received my bitcoins.

**Comment by plondon** [comment]
<img width="189" alt="Screen Shot 2019-07-17 at 7 47 21 PM" src="https://user-images.githubusercontent.com/5640772/61419355-e8daed80-a8cb-11e9-8c8a-2045a60c3bda.png">
<img width="126" alt="Screen Shot 2019-07-17 at 7 47 30 PM" src="https://user-images.githubusercontent.com/5640772/61419356-e8daed80-a8cb-11e9-8f69-aadd8b696233.png">

Blockchain facilitates creating the trade, coinify does the rest. Anyway, I've reached out to them and will revert with their response.

**Comment by darksky25** [comment]
Just got my money back, i am very thankful!

**Comment by plondon** [comment]
Great. Sorry for the issue.
