### ISSUE TITLE
Stellar Airdrop Blockchain Giveaway for Gold Verification

### ISSUE THREAD

**Issue by jumahhassan** [blockchain/blockchain-wallet-v4-frontend#1731]
Hallo,
My Blockchain wallet has not received the reward for joining the Gold verification in form of XLM. 
I need clarity please.

**Comment by darksky25** [comment]
I think it takes some time, i didn't receive it either

**Comment by jumahhassan** [comment]
Do you think it's because the payaway target was reached or not yet?

**Comment by plondon** [comment]
Airdrop has been paused/ended https://twitter.com/blockchain/status/1151507561461485573

**Comment by darksky25** [comment]
But i've done mine in May 2 days after my friend did it. He received i didn't for example, and i told him about it even though he got it and i didn't cause i had a new id
