### ISSUE TITLE
Personal information verification save

### ISSUE THREAD

**Issue by mofengfs** [blockchain/blockchain-wallet-v4-frontend#1750]
I have a problem with the first wallet information: I wrote my Chinese in Pinyin, so I can't pass the verification. Then I created a new wallet, but I failed to save my personal information during the upgrade. How can I solve this problem?

**Comment by plondon** [comment]
Maybe create a new wallet and transfer funds?

**Comment by mofengfs** [comment]
> 也许创建一个新的钱包和转移资金？

My idea is the same as yours, but the problem is that the new wallet failed to save personal information when upgrading. Do I have to continue to create a new wallet and try my luck?

**Comment by plondon** [comment]
Theres no way to edit personal info, so if you entered it incorrectly then I guess the best option is to create a new wallet.

**Comment by mofengfs** [comment]
> Theres no way to edit personal info, so if you entered it incorrectly then I guess the best option is to create a new wallet.

I have tried to create multiple wallets, but always fail when saving personal information, oh my god

**Comment by mofengfs** [comment]
> 没有办法编辑个人信息，所以如果你输入不正确，我想最好的选择是创建一个新的钱包。
I can use the English name, but I am Chinese. The name on my ID card is Chinese.

**Comment by mofengfs** [comment]
> Theres no way to edit personal info, so if you entered it incorrectly then I guess the best option is to create a new wallet.

I can use the English name, but I am Chinese. The name on my ID card is Chinese.

**Comment by ekene90** [comment]
I have not received my XML

**Comment by ekene90** [comment]
I have not received my XLM
