### ISSUE TITLE
"Sorry, something went wrong with your trade", while trying to buy bitcoin 

### ISSUE THREAD

**Issue by fizkeris** [blockchain/blockchain-wallet-v4-frontend#1765]
# 🐛Bug Report 🐛
***Do***
1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Trying to buy bitcoins but get this message "Sorry, something went wrong with your trade"

## Expected Behavior
Buy bitcoin

## Reproduction Steps
Issue happening whether payment is made with debit card or bank transfer -- makes me believe it is a software issue

## Screenshots/Logs
See below the message received when trying to complete the purchase:
Sorry, something went wrong with your trade

## Additional Information
Really need help on this, thanks in advance.

**Comment by Mayankho** [comment]
Has this been solved yet? Really been "bugging" me lol

**Comment by schnogz** [comment]
Can you please add some more information to the ticket so we can properly debug?  Adding 
screenshots of the console or network errors would be a good start!

**Comment by Sicarii33** [comment]
![Screenshot_2020-02-08-00-55-47](https://user-images.githubusercontent.com/60806766/74080069-15905700-4a0e-11ea-834b-0fb118381ded.png)
![Screenshot_2020-02-08-00-57-52](https://user-images.githubusercontent.com/60806766/74080084-2ccf4480-4a0e-11ea-8e0c-0499b0f81cd7.png)

**Comment by Sicarii33** [comment]
I'm having the same issue.

**Comment by plondon** [comment]
Coinify is sunset so closing this.
