### ISSUE TITLE
"Failed to update email address." - no further explanation, address is valid

### ISSUE THREAD

**Issue by slrslr** [blockchain/blockchain-wallet-v4-frontend#1785]
Hello, on Windows with Firefox 60.*, i accessed blockchain.info wallet Version 4.21.7
I went to "Security center", selected to Change e-mail, pasted valid address: severalalphanumericcharacters@tutanota.de
The result: "Failed to update email address."
No explanation. My current e-mail address was not verified

**UPDATE**: despite that error, i have found several verification e-mails in my new e-mail address Inbox. So i clicked the confirmation link in e-mail. I reloaded wallet page, it needed relogin, go to "Security center" and see e-mail was updated. Good, all OK, BUT it is confusing that error, it should not be there, it should say "Verification e-mail was sent to address XY. Please check your e-mail."
And once i confirm, the wallet page should reflect new e-mail, instead of need to reload page/relogin and showing wrong error.

**Comment by Yokymia32** [comment]
Hey

**Comment by Yokymia32** [comment]
Send it again

**Comment by johnsonsan** [comment]
Fixed issue

**Comment by johnsonsan** [comment]
Sandezzy4@gmail.com

**Comment by muntasir2222** [comment]
Muntasir20.03.1991@gmail.com
