### ISSUE TITLE
Hi i am unable to withdraw all bitcoins from my imported bitcoin wallet address

### ISSUE THREAD

**Issue by github78900** [blockchain/blockchain-wallet-v4-frontend#1790]
![Screenshot_2019-08-29-10-52-55-972_com android chrome](https://user-images.githubusercontent.com/29977963/63913553-2f387600-ca4e-11e9-9ff0-9462a815b02e.png)
# 🐛Bug Report 🐛
***Do***
1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
Do you own the private key?

**Comment by github78900** [comment]
Yes I am unable to withdraw/transfer my bitcoin from imported wallet to
other my Blockchain wallets

**Comment by schnogz** [comment]
What is the error message when you try and send?

**Comment by github78900** [comment]
Unable to access request

**Comment by schnogz** [comment]
closing as scam.

**Comment by github78900** [comment]
Why shown insufficient funds

**Comment by github78900** [comment]
Please check attached screenshot

**Comment by github78900** [comment]
When I get bitcoin from Blockchain
