### ISSUE TITLE
Libertarian elect

### ISSUE THREAD

**Issue by superbowl0** [blockchain/blockchain-wallet-v4-frontend#1793]
I am having a problem with my btc from back in the day when there wasnt a private key or code provided my btc came on a feed that gave me as promotional btc when they were still trading pizza for them and they came really nice with address and that was it so now i have them on the blockchain as non spendable is this a unique way consider they were gift from broker and they dont have private keys back then with nobody knowing they were going to be valueable at all they werent even pink sheet fractions of cents...so now what# 🐛Bug Report 🐛
***Do***
1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by alirezamojtahed** [comment]
Ok
