### ISSUE TITLE
.onion link not working

### ISSUE THREAD

**Issue by 4ntil0l** [blockchain/blockchain-wallet-v4-frontend#1804]
`www.blockchain.com` <== this site works right
but when you try to login/singup it redirects you to the `https://login.blockchain.com/#/login`
the massage shown in that page is 
> For improved security, please bookmark and access directly https://blockchainbdgpzk.onion/

after waiting few seconds you see `blockchainbdgpzk.onion took too long to respond.` 
i live in iran and most of the sites are blocked here, so i use tor as a proxy witch works just fine but block chain is not working witch is kind of a pain.
id like to know why this is happening

**Comment by quyvnh27** [comment]
after waiting few seconds you see blockchainbdgpzk.onion took too long to respond.
i live in iran and most of the sites are blocked here, so i use tor as a proxy witch works just fine but block chain is not working witch is kind of a pain.
id like to know why this is happening

**Comment by 4ntil0l** [comment]
?

**Comment by Milan-Popich** [comment]
Here’s a idea. Release my API KEYS.

In Health,
Milan Popich

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Op zondag, september 15, 2019 1:00 PM, quyvnh27 <notifications@github.com> schreef:

**Comment by jowydon** [comment]
I need bitcoins

**Comment by 4ntil0l** [comment]
welp
