### ISSUE TITLE
Consuming blockchain-wallet-v4

### ISSUE THREAD

**Issue by zeyad82** [blockchain/blockchain-wallet-v4-frontend#1936]
Hello,

We have been using service-my-wallet-v3 and it's full of issues, can we use blockchain-wallet-v4 in production? Is it stable? I couldn't find any documentation for v4, can you please provide if there is any? 

Thanks.

**Comment by schnogz** [comment]
Thanks for bringing this issue to light.  As you are probably aware, V3 is no longer actively being developed and is being sunset.  We have noted your request are going to meet and discuss as a team in the next week.  We hope to have some guidance for you after that.

**Comment by zeyad82** [comment]
Could you please update me? @schnogz

**Comment by sidhujag** [comment]
also looking for this info, I noticed official wallet is running v4 now so I assume its stable but I do not see any code for server side API @zeyad82

**Comment by zeyad82** [comment]
You won't find it, they are not helpful. We ended up moving to Coinbase Wallet. @sidhujag
