### ISSUE TITLE
BTC not withdrawable

### ISSUE THREAD

**Issue by michaherrmann** [blockchain/blockchain-wallet-v4-frontend#1957]
This error is shown on the overview page. I have BTC in the wallet but the system does not pay out.

Does anyone know what this could be?

**Comment by schnogz** [comment]
Please include more information.

**Comment by michaherrmann** [comment]
The error ist shown in German Blockchain wallet dashboard in the overview.
"BTC not payable" or "BTC not withdrawable"
I have BTC and still can't send anything.
It looks like I can't use my BTC in the wallet anymore. But what do I do now?

**Comment by schnogz** [comment]
What is the specific error when you try and send your BTC?  Please include screenshots of the error as well as any information logged in the browsers developer console.

**Comment by michaherrmann** [comment]
![grafik](https://user-images.githubusercontent.com/57638959/68613830-ebd39c80-04bf-11ea-87a4-40caf613964f.png)

**Comment by michaherrmann** [comment]
This means that the BTC can no longer be used.

**Comment by schnogz** [comment]
Log into your wallet from a web browser, attempt to send your BTC and screenshot the error.

**Comment by michaherrmann** [comment]
OK, I'll try it tomorrow. I must leave the office now.
Thanks 
Michael

**Comment by plondon** [comment]
This looks like non spendable addresses by the way. i.e imported addresses that don't have a private key.

**Comment by schnogz** [comment]
Closing this issue.
