### ISSUE TITLE
Tor browser alpha: Login button does nothing. Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by slrslr** [blockchain/blockchain-wallet-v4-frontend#1958]
## Description
In Tor browser (alpha update channel) 9.5a2, based on firefox 68.2.0esr (UPDATE: it may be also probem on classic Firefox beta)
and in Tor browser stable channel 9.0.1
i see it is up to date and i access https://login.blockchain.com/#/login
i see Blockchain version 4.23.17
i submit login details and nothing happens. I check dev. console and it shows this message once login button is pressed:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://blockchain.info/wallet/sessions. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

other messages for same page load session is:

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). login.blockchain.com:20:1
> Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.

Please what is the workaround for this?

i think that the work around is to temporarily set (in about:config) the option [network.http.referer.XOriginPolicy](http://forums.mozillazine.org/viewtopic.php?p=14862724#p14862724) to 1

**Comment by DumpWisanu** [comment]
☺️

**Comment by slrslr** [comment]
@plondon @schnogz @prwelber @Lyncee59 @tony-blockchain @sixtedemaupeou @TheLeoB @salomegeo @pernas @jjBlockchain @all

6 months larer...
Firefox beta, Blockchain.com Version 4.32.4
after submitting login at https://login.blockchain.com/#/login

Cross-Origin request was blocked:
> Cross-Origin požadavek byl zablokován: Same Origin zásada nepovoluje načtení vzdáleného zdroje na https://blockchain.info/wallet/sessions. (Důvod: chybí hlavička CORS 'Access-Control-Allow-Origin').
