### ISSUE TITLE
I want to permanently delete my account blokchain

### ISSUE THREAD

**Issue by 8e4cdeb9-23ec-47e1-a785-2fa1d352ef65** [blockchain/blockchain-wallet-v4-frontend#1987]
I want to permanently delete my account

**Comment by 8e4cdeb9-23ec-47e1-a785-2fa1d352ef65** [comment]
Because I found I have two accounts

**Comment by schnogz** [comment]
Just move all funds out of the one you dont want and into the other.  We dont have the ability to view or delete "accounts"
