### ISSUE TITLE
Migrating to React-Redux v7.1 to enjoy Hooks API

### ISSUE THREAD

**Issue by lzhuor** [blockchain/blockchain-wallet-v4-frontend#2022]
Hi team,

Is there any plan of migrating `react-redux` to `v7.1`? So that we can use awesome hooks to reduce boilerplate code required for accessing store or dispatch actions. 

I can create a PR during my holidays in the next few weeks. It doesn't break any existing way of connecting to Redux which means `connect(mapStateToProps, mapDispatchToProps)` will still function. 

These things will need an upgrade:
1. connected-react-router
2. redux-form 
3. react-redux

I have made it happen for two of my projects using very similar setup as our repo.
![image](https://user-images.githubusercontent.com/14172220/70442564-934cea80-1ad1-11ea-8fdd-0428c283b42e.png) 

Best regards,
@lzhuor

**Comment by plondon** [comment]
Looks nice, will require a lot of work to switch over.

**Comment by plondon** [comment]
Our main focus right now in terms of tech debt is moving things over to TypeScript. Lmk if you'd like to help out with that!

**Comment by lzhuor** [comment]
Hi @plondon , it sounds cool. I checked out one of your PR about TS last year and found it has been merged. 👍

Glad to chat further to see which part I could help with!

**Comment by nguyendoanh99** [comment]
Hãy làm nó cân bằng trở lại giúp tôi cảm ơn bạn
