### ISSUE TITLE
i can not see my bitcoin in my wallet

### ISSUE THREAD

**Issue by time1907** [blockchain/blockchain-wallet-v4-frontend#2043]
I've been using a blockchain wallet for 6 years, but this is the first time I've had this problem. 
I've updated my phone and I've updated the blockchain but I still can't log in.
i can open web browser wallet. but i can not see my bitcoin. eth , stellar no problem. 
only bitcoins do not appear. 

[https://prnt.sc/qcrrd5](url)

**Comment by schnogz** [comment]
Please add more details and be more specific about your actual issue

**Comment by time1907** [comment]
I can't see the bitcoin balance in my wallet
(https://prnt.sc/qcrunh)
but the result is negative. 

When I enter the address section. I see this.
(https://prnt.sc/qcrv4k)

I can see the balance of the other coins.
I can't see my bitcoin balance. can't see transaction history
I've been having this problem for 2 day. can you please help me

**Comment by schnogz** [comment]
can you check for any javascript errors or network call failures and post screenshots?

**Comment by time1907** [comment]
i dont know, if you tell me how, i can send.

**Comment by time1907** [comment]
schnogz, please help me

**Comment by plondon** [comment]
https://support.blockchain.com will be much more helpful, please reach out to them.

**Comment by time1907** [comment]
> https://support.blockchain.com will be much more helpful, please reach out to them.

hi philip, The bitcoin balance in the wallet has not been visible for 21 days.
I sent all the screenshots they wanted but the problem was not solved. you have experienced similar problems before. you helped someone similar to my problem [https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/998] can you help me ?

**Comment by plondon** [comment]
Can you try recovering the wallet from your mnemonic?

**Comment by time1907** [comment]
i sent many screenshot.my ticket number:  REQUEST #1314232 can you check.  thank you

**Comment by time1907** [comment]
> Can you try recovering the wallet from your mnemonic?
getting error.

error notification: Error restoring your wallet

I opened the subject 20 days ago. schnogz friends did not help.

I haven't been able to reach my bitcoin wallet for 20 days. I can't view my balance.

Who will help me. I need an emergency and no one here helps.

I'm writing blocchain support a nobody responds.
Sometimes the answer comes. are working on.

I'm asking you. What would you do if this happens to you?
What would you do if you haven't been helped for 20 days?

**Comment by schnogz** [comment]
We updated one of our backends systems and it does not seem to support as many BTC xPubs and addresses to be queried with a single call as did our past system. Our backend team is working on a fix but I'm not sure when that will be deployed.   

It it important to know that your BTC inside your wallet is safe, it's just the call to get balances that is broken.

I am sorry for the inconvenience. I will reach out to you via our support system as well.
