### ISSUE TITLE
Instead of showing balance it's showing me error in my wallet

### ISSUE THREAD

**Issue by laslobit** [blockchain/blockchain-wallet-v4-frontend#2127]
More than 2 months my Bitcoins is not showing in my wallet showing 0 balance in account while i have good balance and i can't send BTC. 
I tried defferents browsers and devices. Problem with only my wallets. 

Screenshots:

https://ibb.co/c6CDbb2
https://ibb.co/ggXPkhX
https://ibb.co/H2YV38w
https://ibb.co/4TxgT3f

**Comment by laslobit** [comment]
I tried restore wallet, but i receive error: Error restoring your wallet.

**Comment by plondon** [comment]
I pinged a backend developer, it may be an issue with the number of addresses associated with one of your active xpubs

**Comment by laslobit** [comment]
> I pinged a backend developer, it may be an issue with the number of addresses associated with one of your active xpubs

Probably yes. Because i accept many payments via API.

**Comment by plondon** [comment]
I have a frontend PR open for handling this error, basically we need to tell our apis that we need to 

1. temporarily increase the limit of your request
2. create a new wallet account i.e "My Bitcoin Wallet 2" with a new xpub but with 0 addresses (well below the limit)
3. transfer your funds and archive the problematic wallet

Once funds are in the new xpub and addresses are below the backend limit functionality should be restored.

Here is the blocked PR for reference: https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/2011/

**Comment by laslobit** [comment]
Hello. 

Any news?

**Comment by laslobit** [comment]
My wallet is still not showing balance and i cant send tx.

**Comment by plondon** [comment]
Sorry for the late reply. So we have a few options:

1. Wait for a backend solution. The team is aware of this issue and it is their number 1 concern. There is no more work that can be done with the current code to improve xpub fetching performance. The backend team is working on an xpub caching solution that will allow fetching xpubs with large amounts of addresses. Even when that happens though, we still have an arbitrary limit on addresses in the backend, so https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/2011 will be used to address this, but thats not your issue.

2. Write a script that you can paste into your console which is something like:

```
1. derive addresses on receive chain in batches of 100 (?)
2. hit unspent with list, save result
3. repeat step 1 and 2 with next 100 (?) addresses
4. stop when /unspents returns empty list
5. repeat step 1 - 4 for change chain
6. create a new wallet for user
7. gather unspents and sign and publish tx to new wallet
8. make new wallet default
9. archive old wallet
```

Unfortunately, both will take time to implement. I'm sorry because I know this is not what you want to hear.

**Comment by laslobit** [comment]
How long i must wait for a backend solution?

**Comment by laslobit** [comment]
Update me please.

**Comment by laslobit** [comment]
Hello. 

Any news?

**Comment by laslobit** [comment]
Can you provide me this script?:) 

1. derive addresses on receive chain in batches of 100 (?)
2. hit unspent with list, save result
3. repeat step 1 and 2 with next 100 (?) addresses
4. stop when /unspents returns empty list
5. repeat step 1 - 4 for change chain
6. create a new wallet for user
7. gather unspents and sign and publish tx to new wallet
8. make new wallet default
9. archive old wallet

**Comment by laslobit** [comment]
It's your official position?
You confirm that you have technical issue because of which user's wallets will be blocked forever?

You said "wait". How long?

**Comment by alekiv** [comment]
Same issue here.
Requests via API also timeouts after 30 seconds, balances are null.

Support is also ignoring. Closing tickets as Solved without any comments
Ticket numbers:

1450246
1451073
1451080

**Comment by alekiv** [comment]
> More than 2 months my Bitcoins is not showing in my wallet showing 0 balance in account while i have good balance and i can't send BTC.
> I tried defferents browsers and devices. Problem with only my wallets.
> 
> Screenshots:
> 
> https://ibb.co/c6CDbb2
> https://ibb.co/ggXPkhX
> https://ibb.co/H2YV38w
> https://ibb.co/4TxgT3f

If you still didn't get your funds back then one option is to use extended private keys, which are  accessible via API. Import them to some wallet (eg. Electrum) and transfer funds to your address.

**Comment by laslobit** [comment]
Problem resloved.
