### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by wargo32** [blockchain/blockchain-wallet-v4-frontend#2195]
I want to know translation process. I want translate to Polish.

**Comment by plondon** [comment]
We rely on a third party to automatically translate our strings. Our polish strings are located here:

https://github.com/blockchain/blockchain-wallet-v4-frontend/blob/development/packages/blockchain-wallet-v4-frontend/src/assets/locales/pl.json

We have about 99% covg on our polish strings.

**Comment by wargo32** [comment]
And how with explorer and rest site?

Can I be invited to translation project?

**Comment by plondon** [comment]
Explorer is not an open source project like the wallet so unfortunately not.

**Comment by wargo32** [comment]
So how can I join to translation team of explorer? It is not problem it is not open-source.

**Comment by schnogz** [comment]
The explorer's translations were just updated, so everything should be already up to date.  Are you noticing anything specifically wrong with translations?

**Comment by wargo32** [comment]
Almost everything!

**Comment by schnogz** [comment]
Yeah most of the translations are done by machine and not humans, so they are probably not the best. we are conversing on the best way that you can help us out. we will follow up soon. Thanks for reaching out!
