### ISSUE TITLE
CSP blocking bitcoin transactions

### ISSUE THREAD

**Issue by tfwyouloveher** [blockchain/blockchain-wallet-v4-frontend#2215]
## Description

Can't send bitcoin from wallet due to CSP

## Expected Behavior

I expected the transaction to succeed and my bitcoin to send

## Reproduction Steps

1. Deposit bitcoin into wallet
2. Click "Send" button at top of page
3. Fill out information and post the transaction
4. Error in top right saying transaction failed

## Screenshots/Logs

![Screenshot from 2020-03-28 19-03-22](https://user-images.githubusercontent.com/16482173/77838322-e8b41280-7127-11ea-896f-bd39763c81e4.png)

There are two POSTs to `wallet-helper.blockchain.com`, both of which were blocked by CSP

## Additional Information

It was specifically a Bitpay transaction

Firefox 74.0
Ubuntu 16.04

**Comment by plondon** [comment]
@tfwyouloveher not sure this is related to a CSP error, although those are there.

You may be able to gather more information from the console on why the tx is failing by entering the app through the link: https://login.blockchain.com/#/open/log-level?level=verbose
