### ISSUE TITLE
Bug: Login requires SMS Code but never added mobile number or enabled 2FA in account

### ISSUE THREAD

**Issue by userag** [blockchain/blockchain-wallet-v4-frontend#2250]
After I click the Authorize Log In link in my email, I get the Login Approved page but then the Login page requires an SMS Code.

I never added a mobile number or enabled 2FA in my account. I always logged in with only my Wallet ID and Password. I've had my account since July 2015.

I submitted a support request about this on January 29 2020, at some point between that date and October 11 2019, there was an update that caused this bug. The support ticket number is 1353712

**Comment by plondon** [comment]
Have you tried resetting your 2fa?

**Comment by userag** [comment]
The reset worked but there's still the question of how this bug happened in the first place.

**Comment by schnogz** [comment]
It's really hard to say what happened given the security of our wallet and therefore lack of change history.  

You should definitely leave to 2FA on to ensure your account is secure.
