### ISSUE TITLE
Wallet is unavailable about 4 months. Support ignore me. My funds are locked.

### ISSUE THREAD

**Issue by laslobit** [blockchain/blockchain-wallet-v4-frontend#2257]
Hello. 

More than 4 months ago our Bitcoin wallet stopped working (Error: timeout). No balance showing, transactions and we cant send bitcoins. Our funds are locked.
We have ticket: 1312498 but in 4 months  problem was not solved.

@plondon , why you ignore me in #2127 ? 
Tell me approximate time reslove issue? A week, 1 months... how long?

**Comment by schnogz** [comment]
We are targeting a release this week that is showing about a 3x speed improvement in our staging environment. Hopefully this will address your issue 🙏  

We are also working on an additional caching layer for the backend that will definitely fix your issue but that change is still at least a few weeks out.

**Comment by schnogz** [comment]
Change has been released. Any update @laslobit ?

**Comment by laslobit** [comment]
Hello. Bitcoin wallet is still unavailable.

**Comment by alekiv** [comment]
Same issue here. API timeouts after 30 seconds

**Comment by laslobit** [comment]
Any update?:) @schnogz

**Comment by schnogz** [comment]
Sorry to hear that this is still an issue for you two. :(

The next backend release introduces a caching layer which should get the new system on par with the old and thus solve your issues.  We are hoping this will be released by the end of the month.

Again I apologize for the inconvenience.

**Comment by alekiv** [comment]
@schnogz, it is not for us two only. I hear more and more users complaining about same issue.

**Comment by alekiv** [comment]
> Hello. Bitcoin wallet is still unavailable.

cross post:

If you still didn't get your funds back then one option is to use extended private keys, which are accessible via API. Import them to some wallet (eg. Electrum) and transfer funds to your address.

**Comment by schnogz** [comment]
We just released a new backend with better caching.  Can you both please test now and let us know how it worked?  🙏 

@alekiv @laslobit

**Comment by laslobit** [comment]
Hello. 

Bitcoin wallet is still unavailable... error: timeout 
https://ibb.co/KqjzDVh

**Comment by schnogz** [comment]
Hey sorry, we had to rollback our backend due to an unforeseen issue. Hopefully we can redeploy with fix today. Will message you both then.

**Comment by schnogz** [comment]
Can you try now and let me know?

**Comment by schnogz** [comment]
Note, that it might take a few tries as we wait for the cache to be fully hydrated.

**Comment by schnogz** [comment]
Nevermind. We had to rollback changes again. Will keep you updated

**Comment by laslobit** [comment]
Really waiting :)

**Comment by RLlane2126** [comment]
true

**Comment by schnogz** [comment]
Okay. please try now @laslobit .  The first time may still fail if your xPub is really heavy.  However, the server will cache some the assets and then your next attempt should succeed.  Please give it a try and report back!

**Comment by laslobit** [comment]
Hello. About 10 attempts failed :(

**Comment by laslobit** [comment]
Any updates?

**Comment by alekiv** [comment]
![image](https://user-images.githubusercontent.com/9446663/79902507-47646780-841a-11ea-8246-37ca4b5cdc29.png)


@schnogz, refreshed page 5 times. Still can't get data from API. 30 seconds and 500 from multiaddr
869 addresses in my wallet

But for friends with less addresses it started to work.

**Comment by alekiv** [comment]
And after 6 ,. 7 refresh seems that cache warmed up and it started to work.
Good work!

**Comment by laslobit** [comment]
@alekiv But not for me)) very much attempts

**Comment by laslobit** [comment]
Its works!
Passed more than 4 months but its works)) Thanks blockchain team.

**Comment by alekiv** [comment]
@schnogz, one issue fixed, new introduced.
Because of caching layer more unhappy users are expected.

one example
![image](https://user-images.githubusercontent.com/9446663/79922057-e77eb880-843b-11ea-8964-c9a843567bfd.png)
 
w1 is actually empty, but it shows cached balance

**Comment by schnogz** [comment]
Awesome!!!!  🎉
