### ISSUE TITLE
After changing the password and adding second password, it asks for a second password which will not being recognised when the user tries to login again. 

### ISSUE THREAD

**Issue by chiholiu** [blockchain/blockchain-wallet-v4-frontend#2269]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
2. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.
**After changing the password and adding second password, it asks for a second password which will not being recognised when the user tries to login again.** 

## Expected Behavior
Explain what you would expect to happen.
**People should have the option to reset their password based on phone number (SMS) and EMAIL, so they got double checked on their validation without contacting the support team of Blockchain.** 

## Reproduction Steps
Enter detailed steps to reproduce the issue.
**Change your password and add a new second password, then try to login (after removing your password history of course) and enter your new password plus your second password and you will encounter this problem**

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.
![screencapture-login-blockchain-2020-04-17-13_45_03](https://user-images.githubusercontent.com/16224390/79567150-fc61f180-80b3-11ea-83ef-6fc51955219a.png)

## Additional Information
Add any addition information that might be useful to our team.
**Please help the end-user and be agile and quick. This is a fast-paced market and reviews online are not really positive, so fix this as quick as possible, else the list of negative comments will keep growing.**

**Comment by plondon** [comment]
We've removed adding second password in newer versions of the wallet.
