### ISSUE TITLE
BTC do not deposited to my Bitcoin Wallet.

### ISSUE THREAD

**Issue by laslobit** [blockchain/blockchain-wallet-v4-frontend#2294]
Hello.

More than 6 hours btc don't deposited on my bitcoin wallet (transcations are confirmed), no info in history.
Do you have some issue? Its no first time problem, but earlier the delay was not so long.

Thanks.

**Comment by laslobit** [comment]
Funds still not deposited to my BTC wallet.

**Comment by schnogz** [comment]
can you share the transaction hash?

**Comment by laslobit** [comment]
I tried to deposit myself but btc don't display on my wallet. When i sending btc from another wallet, blockchain wallet visually update, but balance not update and deposit address is not change.

**Comment by laslobit** [comment]
I create subwallet "2" and tried send btc to this wallet. Funds are deposited, but old wallet (default) still dont deposited new and previous transactions.
https://ibb.co/3yVyyTt

**Comment by laslobit** [comment]
Any news?

**Comment by schnogz** [comment]
Im sorry you are still having troubles with this.  You are a unique use case with so many addresses and large xpubs.  Can you send me an email (andrew@blockchain.com) and we can go from there?  I want to get some more information from your wallet but for privacy reasons don't want you posting here.

**Comment by laslobit** [comment]
Funds are deposited (yesterday). But how can I avoid similar problems in the future?

**Comment by alekiv** [comment]
@schnogz, laslobit is not uniq with issue.
Seems blockchain.com backend architecture doesn't support large xpubs.
Maybe it is worth to put disclaimer or introduce limits, which are clearly visible on page.

One option is to introduce paid plan for large xpubs as https://www.blockonomics.co/ does.
We understand that with large xpubs we create additional load on your backend. With paid plan maybe it will be possible to provide dedicated resources for such customers.


Related ticket #2299

**Comment by laslobit** [comment]
Yes, but this wallet i created few week ago. Wallet have >1k addresses. My previous wallet (4 months of balance unavailable) have >100k addresses. No similar problem was observed there.
