### ISSUE TITLE
multiaddr timeouts after 30 seconds

### ISSUE THREAD

**Issue by alekiv** [blockchain/blockchain-wallet-v4-frontend#2299]
## Description
Requests to multiaddr times out with 500 error code after 30 seconds. As result BTC wallet balances and addresses are not visible.

## Expected Behavior
Expecting to see balances, have ability to view addresses for Request or Send.

## Reproduction Steps
Open page; "Settings" -> "Wallet & Addresses"

## Screenshots/Logs
![image](https://user-images.githubusercontent.com/9446663/80511662-11c4fe80-8985-11ea-906a-26c29388b3fc.png)
![image](https://user-images.githubusercontent.com/9446663/80511769-391bcb80-8985-11ea-9bc9-a71167564ab2.png)

## Additional Information
This is same symptoms as before caching layer was introduced (#2257, #2127).
Issue is back again.

**Comment by alekiv** [comment]
on 10th retry it got "fixed"

**Comment by alekiv** [comment]
Still broken

![image](https://user-images.githubusercontent.com/9446663/80680475-830cca80-8ac7-11ea-9739-fe436ea55c9c.png)

**Comment by alekiv** [comment]
Fixed again. Thanks

**Comment by alekiv** [comment]
Issue is active again. Can't get wallet balances.

**Comment by plondon** [comment]
Hi @alekiv we're doing some maintenance on the be service recently. Will try to keep you updated on when your issue will be resolved.

**Comment by alekiv** [comment]
> Hi @alekiv we're doing some maintenance on the be service recently. Will try to keep you updated on when your issue will be resolved.

Thanks @plondon. I have long mail thread with Andrew about my case. There are some technical details.
Looking forward to maintenance completion and 💯 stable platform.

**Comment by alekiv** [comment]
Fixed again. Thank you
Closing the ticket.
