### ISSUE TITLE
I cant find my bitcoin in my wallet 

### ISSUE THREAD

**Issue by kamsoflash** [blockchain/blockchain-wallet-v4-frontend#2303]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
2. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by doge2021** [comment]
you may reach [blockchain recovery](https://btc2doge.com) to help

**Comment by marlando20** [comment]
@kamsoflash I can crack your password, if you want help to get your password recovered, contact me
[anywalletrecovery@gmail.com]
