### ISSUE TITLE
command: yarn start;   login page error

### ISSUE THREAD

**Issue by NicholasOliveira** [blockchain/blockchain-wallet-v4-frontend#2414]
preview: https://prnt.sc/sm07z2

**Comment by NicholasOliveira** [comment]
Ups! Algo não está certo aqui
Lamentamos, mas parece que algo não está inteiramente correto. Por favor, tente novamente ou entre em contacto com o suporte se o problema persistir.
Error Details
TypeError: Cannot read property 'interest' of undefined

    in Navigation (created by NavigationContainer)
    in NavigationContainer (created by ConnectFunction)
    in ConnectFunction (created by MenuLeft)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by MenuLeft)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by MenuLeft)
    in MenuLeft (created by MenuLeftContainer)
    in MenuLeftContainer (created by ConnectFunction)
    in ConnectFunction (created by WalletLayout)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by WalletLayout)
    in ErrorBoundary (created by ConnectFunction)
    in ConnectFunction (created by Route)
    in Route (created by withRouter(Connect(ErrorBoundary)))
    in withRouter(Connect(ErrorBoundary)) (created by WalletLayout)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by WalletLayout)
    in WalletLayout (created by Route)
    in Route (created by WalletLayoutContainer)
    in WalletLayoutContainer (created by ConnectFunction)
    in ConnectFunction (created by App)
    in Switch (created by App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by App)
    in MediaContextProvider (created by App)
    in ThemeProvider (created by CustomThemeProvider)
    in CustomThemeProvider (created by ConnectFunction)
    in ConnectFunction (created by App)
    in PersistGate (created by App)
    in IntlProvider (created by TranslationsProvider)
    in TranslationsProvider (created by ConnectFunction)
    in ConnectFunction (created by App)
    in Provider (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction
    in AppContainer

**Comment by pete-watters** [comment]
I attempted to reproduce this using the latest code and could not.

**Comment by plondon** [comment]
@NicholasOliveira the issue may be your wallet does not have an email associated w/ it?

**Comment by plondon** [comment]
@NicholasOliveira this should be fixed whether your have an email or not.
