### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by NicholasOliveira** [blockchain/blockchain-wallet-v4-frontend#2449]
# 🐛Bug Report 🐛
***Do***
Access to XMLHttpRequest at 'https://blockchain.info/wallet/sessions' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

works only on localhost, I tried to run via webpack-dev-server on my cell phone with ip 192 .... and it also didn't work

**Comment by schnogz** [comment]
What is your use case for uploading our wallet and deploying to a server? We already do that for you at blockchain.com/login

**Comment by NicholasOliveira** [comment]
Updated my comment lasted

in this use case i am trying to run on the webpack server after the local ip of my 19.168 network .... and access it via my cell phone connected to the same network where the localhost server is started

**Comment by schnogz** [comment]
Why don't you just access blockchain.com/login from your cell phone?  

We have very strict security measures in place to prevent scammers. Either you run the the wallet locally and access via localhost or you login via the link provided.
