### ISSUE TITLE
Please I want to get my password back

### ISSUE THREAD

**Issue by c644e6f2-6e30-4557-860e-aebcb4e35ed1** [blockchain/blockchain-wallet-v4-frontend#2719]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
2. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by doge2021** [comment]
can only bruteforce the password. blockchain.com does not hold the password

**Comment by shaubrel** [comment]
@c644e6f2-6e30-4557-860e-aebcb4e35ed1 
did you get access to your blockchain wallet problem, If not I can restore your wallet for you, contact me: [anywalletrecovery@gmail.com
