### ISSUE TITLE
Simply Query API 

### ISSUE THREAD

**Issue by Ruinous101** [blockchain/blockchain-wallet-v4-frontend#2758]
Hi, 

I'm not sure where to place this but was directed by blockchain.info support to report these errors on Github. 

Having issues with output errors with simple query for the following URLs
https://blockchain.info/q/eta
https://blockchain.info/q/hashrate
https://blockchain.info/q/interval

**Comment by schnogz** [comment]
Known issue that our backend team is working on resolving. Should be fixed in the near future.
