### ISSUE TITLE
Obtain wallet.aes.json via API call

### ISSUE THREAD

**Issue by sgpowers** [blockchain/blockchain-wallet-v4-frontend#2762]
Hi,

I am not certain that this is the correct place to post, but was pointed to github by support team.

I am hoping someone can point me to the solution of obtaining **wallet.aes.json** with mail and 2FA authentication, when the password is lost.

I discovered an API call within: https://github.com/3rdIteration/btcrecover/blob/master/extract-scripts/download-blockchain-wallet.py

However this does not appear to be working any longer.

Is this call method still allowed via the API?

Any help would be appreciated.

**Comment by schnogz** [comment]
When you attempt to log into your wallet, the client makes a call for the encrypted payload.  You can just copy that response and store in a file.

The call to inspect looks something like below
https://blockchain.info/wallet/4de1bbe2-11ba-4a76-a763-ee06c4ccabce?api_code=1770d5d9-bcea-4d28-ad21-6cbd5be018a8&ct=1605282145275&format=json&resend_code

The response will look like the following
<img width="977" alt="Screen Shot 2020-11-13 at 10 44 35 AM" src="https://user-images.githubusercontent.com/6364918/99091009-4e60ec00-259d-11eb-9dca-9d377350a8f6.png">

Just save the `payload` part of the response into a `wallet.aes.json` file and you have what you are looking for

**Comment by marlando20** [comment]
@sgpowers  if you want help to get your  backup recovered, send me email:
[anywalletrecovery@gmail.com]
