### ISSUE TITLE
NEW WALLET DOESNT SEND AUTHORIZATION EMAIL

### ISSUE THREAD

**Issue by themago** [blockchain/blockchain-wallet-v4-frontend#2940]
YOUR "FIXES" AFTER FEB18TH NO LONGER SENDS AUTHORIZATION EMAILS TO LEGACY WALLET ACCOUNTS FROM BLOCKCHAIN.INFO I HAVE NOT BEEN ABLE TO LOGIN TO MY WALLET IN OVER A WEEK BECAUSE OF THIS

**Comment by superesc** [comment]
I have the same issue!

**Comment by schnogz** [comment]
Sorry to hear this.  It appears we are having issues with our 3rd party email provider. Please raise a ticket with our support team for further assistance.
