### ISSUE TITLE
Importing of an old wallet.aes.json wallet doesn't work

### ISSUE THREAD

**Issue by feedmeapples** [blockchain/blockchain-wallet-v4-frontend#2952]
## Description
Importing of an old v3 `wallet.aes.json` file navigates to login page and not to the wallet itself, making it impossible to access the imported wallet

## Expected Behavior
After an import of `wallet.aes.json` file with a valid password, it should be possible to access this wallet. Either by navigating directly to it or by linking to an existing account

## Reproduction Steps
- Navigate to https://login.blockchain.com/wallet/import-wallet
- Drag-n-drop a valid v3 `wallet.aes.json` file
- Enter the wallet password in the password prompt
- Enter a new password in "Choose a New Password" prompt
- Pass the captcha check, press continue
- You will see "New Wallet Successfully Imported" message
Now it will navigate to the https://login.blockchain.com/#/login page (even if you were previously logged in)
- At this point is not possible to access the imported wallet

## Screenshots/Logs
1. import successful:
![image](https://user-images.githubusercontent.com/11838981/109405605-02a53900-7927-11eb-8552-35c7b58403de.png)
2. Then
![image](https://user-images.githubusercontent.com/11838981/109405619-1b155380-7927-11eb-8d9c-390506b9ffb6.png)

**Comment by schnogz** [comment]
Thanks for pointing out this bug.  We migrated it from a legacy codebase and didnt think about this redirect.  Will update it so that it shows you the new wallet GUID instead of redirecting

**Comment by schnogz** [comment]
in the meantime, here are the steps to get the GUID.  

1) open up browser developer tools, go to network panel, check the "preserve log" button.
2) go through the normal process presented on screen after which you will be redirected to the wallet login page.
3) if you now filter the network panel requests to "wallet/login" you will see a call that gets a 301 redirect. This request has your GUID on it.  Copy it and use it to login into your new wallet

![Screen Shot 2021-03-01 at 4 40 50 PM](https://user-images.githubusercontent.com/6364918/109563070-445fec00-7aad-11eb-8cc6-ba231702fbdd.png)

**Comment by schnogz** [comment]
Issue has been fixed with this [commit](https://github.com/blockchain/blockchain-wallet-v4-frontend/commit/a11f0bfe460a734ba0f53c94ac3dfa771b015401)
