### ISSUE TITLE
4.47.29 - can not login via Firefox 86: CORS Missing Allow Origin - Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by slrslr** [blockchain/blockchain-wallet-v4-frontend#2983]
Hello, 4.47.29
Firefox 86.0

https://login.blockchain.com/#/login

after submitting the form, the developer console shows:
```
XHRPOSThttps://blockchain.info/wallet/sessions
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://blockchain.info/wallet/sessions. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
and nothing happens with the form. I am trying also in Anonymous window where extensions should be disabled.

Regarding the first error line (red background, font):

POST | https://blockchain.info/wallet/sessions
```
POST
	https://blockchain.info/wallet/sessions
Status502
Bad Gateway

```

![Screenshot_2021-03-09_15-56-17](https://user-images.githubusercontent.com/6596726/110489963-be185b00-80e7-11eb-9876-5c8d303341c0.png)

**Comment by schnogz** [comment]
Are you still having this issue?  Are you on a VPN? What URL are you accessing the site through?

I am unable to reproduce this.

**Comment by slrslr** [comment]
@schnogz Yes, VPN, accessed the URL i have mentioned. It was a temporary issue, now i can login...
Though the site dev. console shows [bunch of errors](https://i.postimg.cc/0vBrscMW/Screenshot4-47-29-FF.jpg).
Either consider closing it, or if you need something, let me know please.

**Comment by plondon** [comment]
Let's close, thanks for the update.
