### ISSUE TITLE
Verification of Email address

### ISSUE THREAD

**Issue by wisefex** [blockchain/blockchain-wallet-v4-frontend#2997]
I tried verifying my email address in my Bitcoin wallet but to no avail. They say a code was send to my email but I can't find any code. I'm confused here, I don't know what to do anymore....I need to verify my email address in my Bitcoin, I need a help

**Comment by schnogz** [comment]
We addressed the email delivery issues.  Can you confirm if you are still not receiving the auth emails?

**Comment by wisefex** [comment]
Yeah, I can't receive email from my blockchain

**Comment by wisefex** [comment]
Confirm it automatically..

**Comment by kosp4n** [comment]
> Да, я не могу получать электронную почту от своего блокчейна
