### ISSUE TITLE
I can't see my balance in my wallet

### ISSUE THREAD

**Issue by regbf** [blockchain/blockchain-wallet-v4-frontend#3007]
# 🐛Bug Report 🐛
***Do***
I can't see my real balance, my account is blocked or buy crypts with you, can you help?
2. Fernandesruben8942@gmail.com

## Expected Behavior
Open my account and see my balance my savings and buy cryptocurrencies make transfers and receive it.
![Captura de ecrã 2021-03-04 124120](https://user-images.githubusercontent.com/80728726/111241835-d4e21480-85f5-11eb-8f1f-0d02dadd18a3.png)
![Captura de ecrã 2021-03-04 124031](https://user-images.githubusercontent.com/80728726/111241837-d57aab00-85f5-11eb-8062-9b5467258b59.png)
![Captura de ecrã 2021-03-04 123934](https://user-images.githubusercontent.com/80728726/111241838-d57aab00-85f5-11eb-9b20-d08eef683d57.png)
![Captura de ecrã 2021-03-04 124010](https://user-images.githubusercontent.com/80728726/111241839-d6134180-85f5-11eb-931d-86f6b315e558.png)
![Captura de ecrã 2021-03-04 123832](https://user-images.githubusercontent.com/80728726/111241841-d6134180-85f5-11eb-945d-41126cb24500.png)

**Comment by lgtm7555** [comment]
hii

**Comment by plondon** [comment]
Hmm, can you please file a ticket w/ support and then paste the ticket number here? We'll need to see what's happening in the console. I can assist you in more depth once you've opened the ticket, sorry for the inconvenience.

**Comment by regbf** [comment]
I already opened several tickets and i got answered today 
thank you for for attention.

**Comment by drewshaw8** [comment]
Had the same issue...try to use this link to contact  hope it works out for you

**Comment by drewshaw8** [comment]
I had the same issue...tried to email them no response...until I try this http://tiny.cc/rvrutz hopes it works out for you
