### ISSUE TITLE
Send to many Transaction

### ISSUE THREAD

**Issue by mostafashr** [blockchain/blockchain-wallet-v4-frontend#3048]
Is it possible to have multiple output addresses in single transaction? something like send to many in [service-my-wallet-v3](https://github.com/blockchain/service-my-wallet-v3).
Is it  still possible to use [service-my-wallet-v3](https://github.com/blockchain/service-my-wallet-v3) for bitcoin only transaction?

**Comment by plondon** [comment]
I don't know of any reason why it would _not_ work, but that library is pretty old at this point and no longer maintained. If you give it a shot and run into any errors let me know.
