### ISSUE TITLE
Secondary password Criteria

### ISSUE THREAD

**Issue by bslackp** [blockchain/blockchain-wallet-v4-frontend#3133]
First of all, I have tried to solve my query via Support but have no solution, so I have to create ticket here as its more tech side problem. 

In Mai 2016, I have created wallet and after week or so, Its started asking me **Secondary password** to access my wallet, which I believe never set. I have tried to contact support but no help as I got information that there are no data saved on Blockchain.info server. I told support to get back my Version V2 wallet but got replied that my wallet has been upgraded to Version V3. I don't know how this happened, as I am also software developer and I know what I am doing with my wallet. 

I assume, any how or unknowingly I set secondary password and now I can't decrypt or access wallet without it.  So, I am left with only option of Brute-forcing.  Now in my knowledge, I have never set any password and I have to brute-force my wallet, I need some kind of Help from tech team to reduce possibly combination of password by knowing regex allowed for secondary password. 

Can any one from team let me know, what **were** the criteria to set secondary password ? Like min-max length, allowed special character, capital , min numbers etc. ?? 

Thanks in advance.

**Comment by plondon** [comment]
Do you have the mnemonic? If you saved your mnemonic you do not need the second password.

**Comment by plondon** [comment]
> Can any one from team let me know, what were the criteria to set secondary password ? Like min-max length, allowed special character, capital , min numbers etc. ??

No criteria, anything is accepted.

**Comment by bslackp** [comment]
No, i dont have mnemonics..!! Its just randomly asking for secondary password..!! i have only main password. Tried all possibly way to decrypt it but no findings.!! Any how its possible to get wallet.aes.json file which could be generated before V3 upgrade ?? Actually tried to find it in Email but not there.

**Comment by plondon** [comment]
So you have not been able to access the wallet since 2016?

**Comment by bslackp** [comment]
no.. i tried to contact support many times.. but no one solved this issue.. they kept telling me that i set secondary password but in my knowledge i never set. I tried to create "wallet.aes.json" file using btcrecover and checked details about wallet. Wallet has double encryption with secondary password and version is V3. I do remember thats because iOS wallet forced user to upgrade to V3 but know sure what was wallet version when i created this wallet. 

 
![image](https://user-images.githubusercontent.com/43243291/116207427-28409a00-a740-11eb-8134-8d78d87df50a.png)

**Comment by schnogz** [comment]
Can you link your support ticket? I will follow up with you via email.

**Comment by bslackp** [comment]
Herr are my last 2 tickets..!! Please find it in attachment. Please go through all conversation to understand about it. 

![image](https://user-images.githubusercontent.com/43243291/116358333-d100ff00-a7fd-11eb-8608-6f2f33f8b266.png)

**Comment by bslackp** [comment]
Also check this out.. this guy had almost same kind of problem as mine https://www.reddit.com/r/Bitcoin/comments/6f0orq/i_upgraded_my_old_legacy_blockchain_wallet_into/

**Comment by bslackp** [comment]
> Our wallet will not request a secondary password w/o one being set up on the wallet.  Your wallet is version 3.0, which means the wallet was successfully accessed and upgraded after the HD upgrade in **August of 2016**. The only recovery method for the wallet is the 12 word back up phrase, if the wallet was not accessible or upgraded since the time of the upgrade then the wallet would not be version 3.0. However, since this wallet has been upgraded, you definitely had access to the wallet while the 12 word phrase was available. 

One of your support told me wallet has been upgraded in August 2016 but seriously ?? but asking me secondary password since 25.06.2016 when i successfully logged in and used wallet. Since then no solution.

**Comment by Ashutoshk1** [comment]
Hey , can anyone solve my issue too.I wrote my issue many time to support .But no one is responding.When I contacted through live chat,they simply say my password is wrong and can't be recovered.

 My issue is whenever I enter my password and try to login  , I see a message error in decryption and passes wrong.

But too be honest, my password is correct.The day before I was able to login.I saved my password to Google password manager.So,I am 100% sure my password is correct.I am sure this is technical issue which started probably since the day the website version was updated.Now, can anyone please fix this issue.

I also find on reddit many people facing the same issue.But the solution which they are providing is for engineers.I can't understand .

I am submitting the link here
https://bitcointalk.org/index.php?topic=3313785.0

**Comment by Ashutoshk1** [comment]
Hi please technical team

Please fix this.I am very frustrated.

**Comment by Ashutoshk1** [comment]
Hi can anyone reply please.I have amount in that.I wasn't knowing your blockchain website is so faulty.I didn't even backup 12 words phrase.I wasn't knowing even where can I get this.

**Comment by schnogz** [comment]
I followed up with you via our support ticketing system. Closing this ticket for now.

**Comment by Ashutoshk1** [comment]
> I followed up with you via our support ticketing system. Closing this ticket for now.

Ok let me delete my above comments due to privacy reasons...

**Comment by bslackp** [comment]
@schnogz i sent you Email.. can you respond on that..! Thanks

**Comment by Ashutoshk1** [comment]
I want to delete my comment from there

**Comment by bslackp** [comment]
@schnogz you wrote me 5 days ago and told me to Email but still no response. Not even ack mail..!! :/

**Comment by anywalletrecovery** [comment]
@bslackp your only option is to bruteforce the second password, i have done it before

**Comment by johnjames333** [comment]
@bslackp 
we have developed our own hardware for cracking  all versions of blockchain wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333 or gmail : walletsrecoveryservice@gmail.com

**Comment by richardsonn09** [comment]
@bslackp 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
