### ISSUE TITLE
Unable to login blockchain.com 

### ISSUE THREAD

**Issue by Ashutoshk1** [blockchain/blockchain-wallet-v4-frontend#3138]
Hi , I am unable to login despite entering correct password. It shows error in decryption, password wrong.Written for support but no response yet.

Please reply fast

**Comment by schnogz** [comment]
Then your password is probably incorrect. There is no way we can recover it or reset it.

Use your 12 word recovery phrase to recover your funds in the event you can't remember your password

**Comment by Ashutoshk1** [comment]
I don't have that.But my password is correct.But still shows that error.
May be that issue started since you updated your website 
Can't you fix that please?
