### ISSUE TITLE
Wallet reminder not working

### ISSUE THREAD

**Issue by Akrelion45** [blockchain/blockchain-wallet-v4-frontend#3190]
Pretty straight forward

I don't remember my wallet id. If I want to send my wallet id to my email address it's not working.

The error message is something like wallet guid could not be sent to your email.

https://login.blockchain.com/#/reminder

**Comment by pedroapfilho** [comment]
I was able to replicate this issue, I'll check it out and report back on Monday. Thanks for the report!

**Comment by schnogz** [comment]
This endpoint has been turned off momentarily due to abuse.  Please send me an email andrew[@]blockchain[dot]com with the email address in question and I can get you the info.
