### ISSUE TITLE
Login via mobile wallet option removed

### ISSUE THREAD

**Issue by wdcliett** [blockchain/blockchain-wallet-v4-frontend#3335]
Effective within the past 2 hours of my writing, the Login via Mobile option has been removed! In a case of pre-2014 account establishment, my personal account is now rendered inaccessible due to the lack of a fully functioning iOS app (it does not allow me to view my balance or utilize funds from my imported addresses) combined with this recent change. To make matters worse, the system is prompting me for 2FA which is currently disabled on my account!

It is urgent that you revert the current implementations until you have rectified other issues first! There are numerous reports within the iOS AppStore indicating this as well as other issues.

**Comment by wdcliett** [comment]
@schnogz @TheLeoB

**Comment by TheLeoB** [comment]
@wdcliett you should be able to see the 'Log In via Mobile App' now on the login page.
