### ISSUE TITLE
User Specific - Wallet login problem

### ISSUE THREAD

**Issue by abc1abc2abc3** [blockchain/blockchain-wallet-v4-frontend#3519]

**Comment by schnogz** [comment]
when was the last time you were able to log into the wallet?

**Comment by abc1abc2abc3** [comment]
That I don't remember exactly but please see the screenshot that that is my account only and I could login.

May be in april,  I logged in last time
![Screenshot_20210830-084554_Chrome](https://user-images.githubusercontent.com/83293968/131280394-706dc80e-0a4e-4b85-be96-5d3a0404e0c9.jpg)
![Screenshot_20210830-084554_Chrome](https://user-images.githubusercontent.com/83293968/131280410-ae5b5b18-ba85-4fd4-af64-2b50b944bb0a.jpg)

**Comment by abc1abc2abc3** [comment]
![Uploading Screenshot_20210830-084603_Chrome.jpg…]()

**Comment by abc1abc2abc3** [comment]
![Uploading Screenshot_20210830-084603_Chrome.jpg…]()

**Comment by abc1abc2abc3** [comment]
![Uploading Screenshot_20210830-084603_Chrome.jpg…]()

**Comment by abc1abc2abc3** [comment]
![Uploading Screenshot_20210830-085359_Gallery.jpg…]()

**Comment by abc1abc2abc3** [comment]
I also want to add some more information. Actually there was exchange account linked with that too.But once, when I changed their email than probably since than I am seeing password error issue.That day even blockchain website was also updated with new version.

**Comment by schnogz** [comment]
what error are you seeing exactly? please provide screenshots of the errors

**Comment by abc1abc2abc3** [comment]
![Uploading Screenshot_20210830-193231_Chrome.jpg…]()

**Comment by abc1abc2abc3** [comment]
![Screenshot_20210830-193231_Chrome](https://user-images.githubusercontent.com/83293968/131351682-562ce220-fb03-4c5a-b102-140f2f51e82f.jpg)

**Comment by abc1abc2abc3** [comment]
![Screenshot_20210830-193231_Chrome](https://user-images.githubusercontent.com/83293968/131351751-041c0f3b-31e0-417a-9178-a73abdc58c4a.jpg)

**Comment by abc1abc2abc3** [comment]
![Screenshot_20210830-193231_Chrome](https://user-images.githubusercontent.com/83293968/131351794-73b168e1-2558-4cf6-bfcf-9f77923c0f83.jpg)

**Comment by plondon** [comment]
There's nothing wrong with the wallet decryption process, so if the error is wrong password, the issue is wrong password.

Maybe you created multiple wallets by accident? Or changed your password? There's many things that could have happened, but it's not clear there's anything malfunctioning on the wallet side.

**Comment by abc1abc2abc3** [comment]
Thanks for your early response. Yes, I created multiple wallets but that shouldn't cause any password problem .Right? And regarding if this is incorrect. Than I believe strongly that is correct as it was already saved in my notepad file and stored safed.

Anyway thanks if nothing can be done.As requesting again and again for 6$ isn't worth the time spent in requesting.I already wasted like more than 10 hours on live chat support for no benefits or conclusion.

**Comment by abc1abc2abc3** [comment]
One more which I would like to add, that the possibility is that probably password got changed if not any issue in system.Than my question is how it can be if that was 2 F authenticated.On my mail I should have received another login details like country , ip address , android name.But I didn't received such.In fact , even login email hasn't been changed as I still receive authorization mail when I enter my email address

**Comment by abc1abc2abc3** [comment]
Also why authorisation email says accessed despite clicking on the link wrong password is shown and prevent login
![Screenshot_20210902-142803_Chrome](https://user-images.githubusercontent.com/83293968/131815079-34aa16fc-f856-425e-8d2a-ada2f518990c.jpg)

**Comment by abc1abc2abc3** [comment]
Sir, can you please explain this what might be the reason of last accessed notifications on mail  and wrong password issue.If password is really wrong than quite possible that got hacked and changed password. But here, I would like to question again , how it can be hacked if password was 2Factor authorized meaning without clicking the link manually by me , no one can hack and also I didn't got such mail

Sir please answer , is it any issue,  will I be able to login my account , are you working on this?

**Comment by abc1abc2abc3** [comment]
Sir, I request you to fix these issue.What kind of these issues are which affect only certain wallet to show correct  password as wrong.Abd if it is not any issue of system , than other reason is that got hacked. If so , than you claim that your system is very secure which can be hacked despite 2 F authorization enabled. I don't think this is secure.Infact website with no 2F feature are more secure than that, as it never got hacked. 

Hope anyone would either fix the issue or answer my question.

Atleast upgrade login method to make it simple to login with password reset facilitate.Nothing wrong will happen with password reset feature by sending verification code on mail as than I can access my account then probably.Anyway, your website security is not good already proveh with my 2 wallets.

**Comment by abc1abc2abc3** [comment]
Should I move on , or u are working on this issue.Atleast can you answer yes or no

**Comment by abc1abc2abc3** [comment]
Hi, what can't anyone answer?

**Comment by abc1abc2abc3** [comment]
May I get  answer, or anyone is working on wrong password error

**Comment by CBGusa** [comment]
It cost $100

**Comment by abc1abc2abc3** [comment]
What u mean by its cost?

**Comment by abc1abc2abc3** [comment]
If any more details you need, I agree to provide.

Actually there were about 3 non custodial wallets.One 
With 14baa135-6d22-42a6-8800-a792d6c4ea39 with about 6$ , 5.4$ in usdd and rest in eth and xlm
was linked with exchange account.Later I only changed email of exchange account and enable With 2F.As you know after 2 f login is only done by entering code from Google authentication app.Then once, what I did was , I Uninstalled the app. And after that , I couldn't have login exchange without contacting support.

After that day,  I also started seeing password error in non custodial also.Does changing exchange authorization process of email also affect non custodial?

Please answer this.And regarding other two wallets ,all those doesn't have any amounts.

And regarding linked exchange which was verified but I didn't submitted identity document as I wasn't interested in using exchange plus it had fund like 0.6 $ also didn't tried to contact further to support.Hence, it got rejected.


I think changing email of linked exchange might have done some authorization issue to non custodial in recognizing the password as I know I know my password plus it was saved on my Chrome browser plus notepad.How that can be wrong 

So, I request you to please check this and fix issue if any there.

**Comment by abc1abc2abc3** [comment]
Also when I try to login by password on app, it says pairing failed

**Comment by plondon** [comment]
> I think changing email of linked exchange might have done some authorization issue to non custodial.

This should not have any effect on how your wallet is encrypted/decrypted.

**Comment by abc1abc2abc3** [comment]
If you can't do anything just apologize for wasting my time  and money due to your poor security system which fail to recognize password or let any one hack even with 2 f authorisation enabled but don't simply close this ticket in the same chat support does after wasting so much time. 

I have every screenshot proof of password that was saved on Google Chrome for that wallet id and even copied on notepad.And above all I remember my password very well as it was my phone no only.
