### ISSUE TITLE
How to change email sender?

### ISSUE THREAD

**Issue by trustwalletvn** [blockchain/blockchain-wallet-v4-frontend#3532]
Hello
I’m build on Windows with  IntelliJ IDEA
Run perfect on localhost
But when i’m signup an account , i’m get  an email confirmation  from blockchain.com 
How to change to my email? And config email for smtp sender?
Also how to build other languages?
I see language file en.json 
Copy and translate to other languages but not showing 
Please help
Thank and regards

**Comment by schnogz** [comment]
its not possible to change the email provider. you'd have to write your own backend service to do this if so desired.
