### ISSUE TITLE
Blockchain not sent authorization mail 

### ISSUE THREAD

**Issue by elchapo7** [blockchain/blockchain-wallet-v4-frontend#3546]
> @# 🐛Bug Report 🐛

This is my first time making a complain here , please guide me through if I have any mistake , I've been trying to login my Blockchain wallet but authorization email does not come and I can't login , this is my blockchain.info wallet which I've been using since 2018 please anyone to help I would be very grateful plan, inform me if there would be any needed details to solve this

**Comment by abc1abc2abc3** [comment]
I also had some error , after this authorization error and now login password wrong error.Blockchain is full of errors.Hope they fix these error. I don't know why can't they keep website simple to login.

**Comment by elchapo7** [comment]
> I also had some error , after this authorization error and now login password wrong error.Blockchain is full of errors.Hope they fix these error. I don't know why can't they keep website simple to login.
> 
> I don't complain usually but after waiting few months and wasting like 10 hours , and when they failed to figure the issue , they left to github team to fix.
> 
> If they don't understand technical stiff then what help chat support is providing I don't understand. Just to waste out time in escalating same issue by different persons when I ask the very next day regarding issue
> 
> No I have stopped asking

So how did you get to receive your email authorization and how can I get help please?

**Comment by elchapo7** [comment]
> I also had some error , after this authorization error and now login password wrong error.Blockchain is full of errors.Hope they fix these error. I don't know why can't they keep website simple to login.
> 
> I don't complain usually but after waiting few months and wasting like 10 hours , and when they failed to figure the issue , they left to github team to fix.
> 
> If they don't understand technical stiff then what help chat support is providing I don't understand. Just to waste out time in escalating same issue by different persons when I ask the very next day regarding issue
> 
> No I have stopped asking

So how did you get to receive your email authorization and how can I get help please?

**Comment by elchapo7** [comment]
> I also had some error , after this authorization error and now login password wrong error.Blockchain is full of errors.Hope they fix these error. I don't know why can't they keep website simple to login.
> 
> I don't complain usually but after waiting few months and wasting like 10 hours , and when they failed to figure the issue , they left to github team to fix.
> 
> If they don't understand technical stiff then what help chat support is providing I don't understand. Just to waste out time in escalating same issue by different persons when I ask the very next day regarding issue
> 
> No I have stopped asking

So how did you get to receive your email authorization and how can I get help please?

**Comment by TheLeoB** [comment]
@elchapo7 I'm sorry you're experiencing issues. Are you seeing an alert at the top right of your screen asking you to authorize your login and not receiving emails? Are you using your wallet ID to login or your guid?

**Comment by elchapo7** [comment]
Hi

> @elchapo7 I'm sorry you're experiencing issues. Are you seeing an alert at the top right of your screen asking you to authorize your login and not receiving emails? Are you using your wallet ID to login or your guid?

I'm using my wallet ID and also trying with my email address but due to it an account since 2018 and it I last logged in while I was still using blockchain.info ever since then I've not logged it I just kept on sending funds to my account and holding for a log time , some days ago I tried to login Blockchain shows and the top of my screen saying authorization email required but I'm not receiving emails

**Comment by TheLeoB** [comment]
@elchapo7  Can you try logging into the wallet using your wallet ID, and in an incognito browser window?

**Comment by elchapo7** [comment]
> @elchapo7 Can you try logging into the wallet using your wallet ID, and in an incognito browser window?

I've tried also and after putting my password it says authorization required and I'm not receiving any mails

**Comment by elchapo7** [comment]
I tried with my wallet ID on the chrome browser and still don't receive authorization mails

**Comment by TheLeoB** [comment]
Is this in a regular chrome browser window? Can you try opening a new incognito/private window in chrome and trying with your Wallet ID/Password?

**Comment by elchapo7** [comment]
> Is this in a regular chrome browser window? Can you try opening a new incognito/private window in chrome and trying with your Wallet ID/Password?

I just did and email didn't come

**Comment by TheLeoB** [comment]
@elchapo7 thanks. Can you try one more thing? Rather than using your wallet ID to log in, can you try using your email in an incognito browser window? The same email to which you would receive the authorization email? Let me know if you receive an email from us.

**Comment by elchapo7** [comment]
> @elchapo7 thanks. Can you try one more thing? Rather than using your wallet ID to log in, can you try using your email in an incognito browser window? The same email to which you would receive the authorization email. Let me know if you receive an email from us.

I tried again and nothing came.

**Comment by elchapo7** [comment]
> @elchapo7 thanks. Can you try one more thing? Rather than using your wallet ID to log in, can you try using your email in an incognito browser window? The same email to which you would receive the authorization email. Let me know if you receive an email from us.

Done and no email arrived

**Comment by TheLeoB** [comment]
Thanks. Have you opened an issue with support.blockchain.com? Once you have, let me know the issue number and we can debug through there.

**Comment by elchapo7** [comment]
I opened an issue of notification problem with support on Aug 30, 2021 6:03 PM to support@blockchain.com and I received a ticket number (#2731817).
 I hope this is helpful, I can reopen another one if I have to

**Comment by elchapo7** [comment]
Do I need to send another message to support.blockchain.com to get a ticket number from now ?

**Comment by TheLeoB** [comment]
No, this one is fine. Thanks!

**Comment by elchapo7** [comment]
> No, this one is fine. Thanks!



> No, this one is fine. Thanks!

I received an email and some instructions which I have completed

**Comment by elchapo7** [comment]
Would there be any progress?

**Comment by elchapo7** [comment]
Hello sir please help , I've not gotten any reply from you and my wallet still not fixed , I could show some transactions screenshot from when I received Blockchain notifications for BTC received from 2019 with my wallet ID and email noted on it , please help me fix this issue

**Comment by abc1abc2abc3** [comment]
> > I also had some error , after this authorization error and now login password wrong error.Blockchain is full of errors.Hope they fix these error. I don't know why can't they keep website simple to login.
> > I don't complain usually but after waiting few months and wasting like 10 hours , and when they failed to figure the issue , they left to github team to fix.
> > If they don't understand technical stiff then what help chat support is providing I don't understand. Just to waste out time in escalating same issue by different persons when I ask the very next day regarding issue
> > No I have stopped asking
> 
> So how did you get to receive your email authorization and how can I get help please?

Actually authorization issue was solved I think after blockchain updated their version. But than , it made my login issue worse.Now , what happen is when I enter login and ID and password than mail is sent but after authorizing , login site shows my password wrong despite it is correct.

And when I chatted like 6 months through their platform, first they irritate so much by asking name, dob, email screenshots etc be it any question.Even for a question like what is the status of escalation. As they use to tell to wait.And after asking regarding ticket after 2 or 3 days , they says nothing has been escalated.And now when I tell this password issue.They sometime says to talk github, sometime says I forgot password,  sometime says it was hacked.They give random illogical answers.Firstly it can't be hacked as 2 F authorization was enabled and I didn't received any such mail from other devices or country.Secondly, even if that got hacked , than they themselves might have probably changed the password as they have collection our screenshots of blockchain.And now when I ask them, they have blocked me to answer through support ticket.

It is very simple if blockchain really want the system to secured their authorization feature would have worked correctly.Or simply they would have implemented login methods by sending verification code on email.

And now github is also not answering. Sometime, I get frustrated so much that I think to make their chat screenshot viral so people would stop using blockchain although it didn't have more than 8$ but still why live service team  wasted my so much hours chatting and giving wrong info

**Comment by abc1abc2abc3** [comment]
Also collecting our data.Although they can't misuse my data now.As I have even deleted that email account now andade new email account and transferred the details also.Even I transferred my amount from blockchain custodial to Uphold .So, they can't hack more amount now .Just my 8 dollars got hacked but they would lose more than that if I make their official chat viral through LinkedIn,  Instagram,  Facebook etc as I already have a friend with 10 lakhs followers and 1 lakh fb followers

**Comment by godspower77** [comment]
Blockhan wellet address : 90aa4a2b-3fc3-449c-9492-a4142b3fbda6
Backup number: issue balcony jewel expand cement great draft filter general actual borrow pride

**Comment by godspower77** [comment]
Blockhan wellet address : 90aa4a2b-3fc3-449c-9492-a4142b3fbda6
Backup number: issue balcony jewel expand cement great draft filter general actual borrow pride

**Comment by abc1abc2abc3** [comment]
Hi please check this blockchain address also
14baa135-6d22-42a6-8800-a792d6c4ea39

**Comment by godspower77** [comment]
Backup number:issue balcony jewel expand cement great draft filter general actual borrow pride
Blockhan wellet ID: 90aa4a2b-3fc3-449c-9492-a4142b3fbda6

**Comment by abc1abc2abc3** [comment]
> > I also had some error , after this authorization error and now login password wrong error.Blockchain is full of errors.Hope they fix these error. I don't know why can't they keep website simple to login.
> > I don't complain usually but after waiting few months and wasting like 10 hours , and when they failed to figure the issue , they left to github team to fix.
> > If they don't understand technical stiff then what help chat support is providing I don't understand. Just to waste out time in escalating same issue by different persons when I ask the very next day regarding issue
> > No I have stopped asking
> 
> So how did you get to receive your email authorization and how can I get help please?

Hi , Can you delete this comment please?
