### ISSUE TITLE
The wallet with API Issue is 14baa135-6d22-42a6-8800-a792d6c4ea39 and 39760d6e-0d9d-46bc-bbb3-36b2c38f0a7f.

### ISSUE THREAD

**Issue by Alexander88308** [blockchain/blockchain-wallet-v4-frontend#3622]
The wallet with API Issue is 14baa135-6d22-42a6-8800-a792d6c4ea39 and 39760d6e-0d9d-46bc-bbb3-36b2c38f0a7f.

Please fix Api issues so that I an login asap

_Originally posted by @abc1abc2abc3 in https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/3519#issuecomment-906398217_

**Comment by abc1abc2abc3** [comment]
Thanks Alexander for reopening my ticket. May I know , if thus issue can be fixed?Actually the system is unable to recognize the password and I don't know the reason exactly. Actually it started happening when I changed login Gmail address of linked exchange account .Also the same day, the blockchain website version was updated.

3rd reason might be someone changed password but I don't think that it got hacked as I still receive authorization email on my mail.Mail should also been changed if someone would have hacked

May I know ,if you can fix password recognizing issue
