### ISSUE TITLE
Please enable login by email method to non custodial 

### ISSUE THREAD

**Issue by abc1abc2abc3** [blockchain/blockchain-wallet-v4-frontend#3666]
Please enable login by email method to non custodial  also.Why such facility to only exchange account ?please implement for non custodial also so that I can login.And if cannot implement that method.May I know why ?As infact with 12 word recovery feature also is creating many issues.Like cannot recognize passwords if created multiple wallets and linked with exchange. And when exchange login email gets charge than it affects linked non custodial also as linked non custodial stop recognizing password .Not sure with other wallets.But the two wallets which I am facing passwords issue were linked with exchange and after I changed login email of linked exchange since then I believe such issue started.

Also there is no use of 12 word recovery phrase as you don't educate about this feature.i didn't had any idea.Infact I was sure that it cannot be hacked as it was 2 F authenticated.

Just believe me anywhere your security system has bug either in recognizing password most probably and if my account were hacked than again yiu should be blamed fof such faulty authorization feature as I never allowed any other person to login.Infact I didn't received other mail from other countries attempting to login my account.

And regarding password also I am sure, that I know my password as it was saved on my Chrome plus I was able to login even on laptop.Only possible if I know that.

My two non custodial wallets have login issue.Although not much amount amount.

But still I want to access.

Also would request to fix this issue so that I an login or implement email method to login

That's it

**Comment by abc1abc2abc3** [comment]
Please tell, when it will be solved as I am trying again and again but system is showing wrong password error

**Comment by abc1abc2abc3** [comment]
Atleast clear this out , will that issue ever be fixed or should i stop wasting my time trying to login.

**Comment by plondon** [comment]
Is it possible that you are using the wrong password to try to login to the wallet? Maybe the password you made for the exchange account?

**Comment by abc1abc2abc3** [comment]
No I am using correct password. And why only linked one is only having such issues.I also doubting may be I might be using wrong password,  but I believe strongly now that is some system issue only as first it shown some error while login and since next time password issue arised.

And regarding password, just want to say that it is already saved on my notepad,  also on chrome password manager and I myself remember also.

Anyway,  i am frustrated with your service and angered too with chat service provider as till now they haven't given any clear reason of that issue.

First day they said that it might be bug will get solved in one day.And since next time they started giving ridiculous Suggestion.Like some said , in their system , their device is showing login from another countries.Some person say that they don't store any details regarding non custodial. If they don't store or can't see, then how few person claimed that it got hacked. First how it can get hacked as never allowed any other to login .And even hacked they why hacker didn't changed login ID.And BTW, why even anyone hacked also just for 6$ .ERC fees was even more than that  otherwise I myself would have withdrawn. 

Also what kind of security system is this only for non custodial not for exchange that allow login only from password or 12 word recovery phrase.If this is for security purposes than how people account are still getting hacked.
In exchange any person can change password and login easily just by sending code on email. This also prevent hacking. Infact exchange login method is more secure and easy to login.

Why can't you allow me to login just by email

**Comment by plondon** [comment]
> but I believe strongly now that is some system issue only as first it shown some error 

What is "some error"?

**Comment by plondon** [comment]
You say that the wallet reports "wrong password". If there was such a bug that encryption/decryption didn't work, _nobody_ would be able to login. So, we can't reproduce this error. There's just not enough information. You say 6$ is lost. Maybe we can reimburse you of these funds. But there's not much else we can do w/o steps to reproduce this issue...

**Comment by abc1abc2abc3** [comment]
nobody would be able to login

Actually I think it affects few people only.May be other people don't report this issue or is neglected as on LinkedIn and Facebook group also I seen such complaints. Anyway I am attaching few links also of people having same issues:

https://bitcoin.stackexchange.com/questions/70573/blockchain-info-says-password-is-incorrect-and-wont-allow-me-to-access-my-btc
https://bitcointalk.org/index.php?topic=1537436.0
https://amp.reddit.com/r/Bitcoin/comments/knihoh/weird_log_in_problem_in_blockchaincom_wallet/




Anyway just tell me why official live chat service provider provided different opinions like some say logins were from other countries like Poland while I am from India.Some said that we don't have access to non custodial. If they don't have access than why and how they verify with identity documents Also why few told that my passwords were changed and being login from other countries.How did they knew this?And when I shared the screenshots of their chats , they simply blocked me from chat for violation.May I know what my violation was? Infact they themselves are doing violation by collecting our personal information like name , dob , email sometimes screenshot of wallet or chrome console manager.Also why they have been hired first , because they never helped in any way.Just waste our time.


By the way , what's the issue in implementing login by sending otp code on linked Gmail account as Anyway this current method of login by password or 12 word is a trouble for many.As many people forget their passwords and are not educated about 12 words recovery method to login.Anyway, if this was for security purpose, they why many people accounts are getting hacked still.

I would ask finally if you can do such thing like login by sending verification code on associated email , then please say , or else I would have to stop wasting my time here also as you people can't do anything other than just promoting this blockchain website.

And regarding imbursement also I don't think,  you would be doing, as live chat also said the same thing and collecting my information and wasting my time, in last they simply blocked to chat.May be they started worried if I bring their chat screenshot to public.

**Comment by abc1abc2abc3** [comment]
Sir, please bring new feature to login via email directly or to reset password

**Comment by abc1abc2abc3** [comment]
Try to understand,  definitely there is some bug in the system. How can I forget the password after using the same password to login about 1 year .Also it was saved on Google password manager. 

Anyway, atleast if despite 2F authorization, if password gets changes as claimed by your official live chat service provider,  then this proves this is the bug.Although, I don't believe if anyone changed my pass for two wallets.As why would even anyone change also as one wallet didn't contain any amount.And second one contain 6$ usdd around but the withdrawl ERC fees in last few months was even greater then that.

Anyway, if don't want to fix this bug, or return the same amount,  atleast bring a new feature to login via email or change password via sending code on email or if not so then atleast through manual verification. 

I know I shouldn't have created multiple wallets but I used yo forget wallet id, and simply create a new one just to login but that's not my fault.

**Comment by abc1abc2abc3** [comment]
If you can bring a feature to login via cloud,  than why can't bring a new feature to login via email.
BTW, how this new feature with help,  as in blockchain app doesn't have such option of scanning QR code 
![Screenshot_20210929-131504_Chrome](https://user-images.githubusercontent.com/83293968/135225385-7e7285cc-b050-450f-8773-a1eb49bd3298.jpg)

**Comment by abc1abc2abc3** [comment]
I am talking about first feature.
![Screenshot_20210929-131504_Chrome](https://user-images.githubusercontent.com/83293968/135251111-79bfa71c-d5e3-43f8-9e06-ae630ee90e02.jpg)

**Comment by abc1abc2abc3** [comment]
I am taking about first feature

![Screenshot_20210929-155255_Chrome](https://user-images.githubusercontent.com/83293968/135251320-09f53027-0d4b-4c0c-ae71-a44263a6e4d0.jpg)

**Comment by plondon** [comment]
<img width="677" alt="Screen Shot 2021-09-30 at 12 02 06 PM" src="https://user-images.githubusercontent.com/5640772/135490665-e92d21eb-b14c-48ed-bc0f-b8beccfacb17.png">

"Login by Email or Wallet ID"

**Comment by plondon** [comment]
You can't reset password w/o logging in because we don't have your password.

**Comment by abc1abc2abc3** [comment]
I am not saying you to reset password.I am just asking if you can bring a new feature to reset password via sending otp code to linked Gmail as you recently brought a new feature to reset password by cloud backup.

 As most of the website has this feature to reset password than why can't a blockchain have for security purpose.And by the way where is security in blockchain if people account still getting hacked as authorisation feature not work properly. 

I know my account hasn't been hacked.It is just your officials are lying to escape from working. And I can show you their chats also.

**Comment by abc1abc2abc3** [comment]
Hi Plondon, can you bring this method to reset password by sending code on email in the similar way blockchain exchange allows to reset password by sending code on email.

Please I request you.

Also would like to know how password reset through cloud will work.Will it let me reset my password?

**Comment by abc1abc2abc3** [comment]
Please at least answer without wasting much time , why blockchain non custodial doesn't have any password reset method.If this is for security purpose then how my password got changed probably as not working now despite blockchain 2FA enabled. Where is the security?Why you have hired so many people for live chat service?As no one can help beyond what is already given on blog.Infact they collect our data each time we chat for help.And probably they themselves might have got access of my password as they once told to send screenshot of chrome console manager to check issues.That contain password also I guess.And in last they say they don't interfare with non custodial. Then why they say the same in start of chat only that they won't help as they don't have access or interfare with our non custodial wallets.

I hope I will be provided logical answer.And I will keep on asking untill I receive satisfactory answer of access to my account.

**Comment by abc1abc2abc3** [comment]
Please fix my issue or should I make a team to complain together.

**Comment by abc1abc2abc3** [comment]
Why exchange have different method of password reset and private have different method though both are blockchain product only

**Comment by abc1abc2abc3** [comment]
If you don't know how to bring password recovery method,  then ask your head but please either fix or bring this feature.

**Comment by abc1abc2abc3** [comment]
After chatting like more than  6 months,  and getting rediculous suggestion and blocked for no reason,  I am frustrated now .Now I want to login my wallet

**Comment by schnogz** [comment]
> I am not saying you to reset password.I am just asking if you can bring a new feature to reset password via sending otp code to linked Gmail as you recently brought a new feature to reset password by cloud backup.

There is no possible way for us to reset your non-custodial wallet password!  We dont store your wallet password on our servers, ever.  Therefore we literally cannot add a reset password feature for you.   

When you signup for a wallet with us, the application uses the password you created the wallet with to encrypt your entire wallet and then we store the encrypted wallet on our servers.  Given that model, we don't know anything about your wallet or its password since its encrypted using the password you chose and that password never leaves your browser.  We warn you of this when you signed up for the wallet.

![terms and service](https://user-images.githubusercontent.com/6364918/135759111-bf19bb63-2a32-462e-bc0b-4c63badb265b.png)

**Comment by dezanewoods3** [comment]
``https://travis-ci.org/github/blockchain/blockchain-wallet-v4-frontend

**Comment by abc1abc2abc3** [comment]
Given that model, we don't know anything about your wallet or its password since its encrypted using the password you chose and that password never leaves your browser. 

Never leaves means ?And how an application can store a password instead of any server.And even if then how app or website automatically logout many times.

Ok, thanks for showing warning screenshot .Agree that it is my fault that I ignored that message about 12 word recovery method.But with this, I would like to say, I didn't had any need of that as I haven't forgotten the password. And if this is true than other reason is that got compromised. 

If compromised then it proves that your security system is either faulty or your officials got to know my password as they used to ask our details any time they start live chat and once they also collected screenshot of chrome console tool.

If they don't interfere and we're unable to help in any way then why they used to collect my personal each time I chat. Was it to hack?I sometimes think they themselves might have hacked.

Also why they used to escalate and used to tell to contact next day.Also they asked to submit screenshot and documents and suggest to create another wallet. Some said to create another wallet with new email so that they would send my fund to that but they didn't do.What was the need of doing all these time wasting formalities.?They wasted like more then 3 months.
Have you answer of this?Why they didn't cleared this on first day of chat that they won't help in any way.

And in last they blocked me which made me irritate more.If I want then I can make viral of their supports chat screenshots.

**Comment by schnogz** [comment]
>Never leaves means ?And how an application can store a password instead of any server.And even if then how app or website automatically logout many times.
When you enter your password, the password is never sent to our servers. The web app uses the password to try and decrypt the payload that was sent from our servers. If the password is correct, the wallet gets decrypted and you are logged in.  If the password is wrong, you are not able to login.  

The entire wallet is open source (thats what this github repo is).  If you do not believe what we are saying, I implore you to inspect all network activity made from the application via browser dev tools (to ensure the password is never sent anywhere) and also audit all of the code yourself.

**Comment by abc1abc2abc3** [comment]
I don't know coding.And if there is no issue in recognizing the password then if means password got compromised due to fault in your authentication system. As with this feature any time anyone login , a mail is sent immediately but I wasn't mailed from any other location.

Also your chat support staff irritated a lot by wasting so much time by asking same security questions again and again and giving random rediciculous advice.

**Comment by schnogz** [comment]
> means password got compromised due to fault in your authentication system
Again we dont store passwords on our servers. So please explain to me how you think our system could have been compromised such that someone stole your password or changed it?

What most likely happened is you got phished and someone took over your account without your knowledge.

**Comment by abc1abc2abc3** [comment]
I hope you how authorisation feature work that is when any person try to login through different browser,device or location, a mail is sent with associated email account asking to click for login approval.Here, any person can detect if someone attempting to login from other location ,phone etc and won't click thus preventing hacking of account.I am talking about this feature.Why I didn't received such mail if my account was attempted from other person.

Also you didn't answered about why you have hired soany people for live support to waste our time.And why they asked me to submit screenshot of my account with wallet id and chrome console tool which probably also store the password
