### ISSUE TITLE
Separate exchange wallet from private key wallet.

### ISSUE THREAD

**Issue by ghost** [blockchain/blockchain-wallet-v4-frontend#3749]
I'm a user at blockchain.com wallet since 2019. I needed a web wallet to store my cryptos securely. At that time, Blockchain.com wallet were the best option for me

But now with a lot of new features added and it could be problem
Especially, I think it's a problem that the Exchange wallet and the private key wallet are in the same place
I propose to separate the exchange wallet from the private key wallet.

**Comment by schnogz** [comment]
what do you mean by separate?  The non-custodial wallet (private key wallet) and your custodial accounts are seperated.

**Comment by wowowooooo** [comment]
How about separate the custodial account features to other repositories
Can you check if it has no any security vulnerabilities from thousands of code lines?
