### ISSUE TITLE
Why is my blockchain keeps telling me oops something went wrong? 

### ISSUE THREAD

**Issue by Oshio01** [blockchain/blockchain-wallet-v4-frontend#3798]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
2. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by schnogz** [comment]
looks like you are trying to send from your custodial account (i.e. a withdrawal). do you have another pending withdrawal?

**Comment by Oshio01** [comment]
There's no pending withdrawal but it says pending withdrawal 


Sent from Yahoo Mail for iPhone


On Monday, November 1, 2021, 1:37 PM, Andrew Schneider ***@***.***> wrote:




looks like you are trying to send from your custodial account (i.e. a withdrawal). do you have another pending withdrawal?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fayaxo** [comment]
same issue with me !! have you resolved it if so how? and when i switch to “send” it does the same thing too :/

**Comment by shaubrel** [comment]
@fayaxo 
did you get access to your blockchain wallet problem, If not I can restore your wallet for you, contact me: anywalletrecovery@gmail.com

**Comment by doge2021** [comment]
> same issue with me !! have you resolved it if so how? and when i switch to “send” it does the same thing too :/

i guess you used their trading account? if in privatekey wallet, can try to decrypt it manually and move to other wallets.
