### ISSUE TITLE
![IMG_2735](https://user-images.githubusercontent.com/93393349/139469972-b2cc46e8-f6a0-4ce9-b1b8-1e591744e604.PNG)

### ISSUE THREAD

**Issue by hammadha24** [blockchain/blockchain-wallet-v4-frontend#3821]
![IMG_2735](https://user-images.githubusercontent.com/93393349/139469972-b2cc46e8-f6a0-4ce9-b1b8-1e591744e604.PNG)
![tempImager7rfmH](https://user-images.githubusercontent.com/93393349/139470049-84caafef-afdb-4a20-8557-219b66829e5d.gif)

Here are the screenshot of what my blockchain is saying.

_Originally posted by @Oshio01 in https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/3798#issuecomment-954881129_

**Comment by Donone19** [comment]
Honorments to big ups all of you nice work
