### ISSUE TITLE
SERGEY SAPRYGIN

### ISSUE THREAD

**Issue by 1b3634f6-9166-46d7-a43a-51d575159cf0** [blockchain/blockchain-wallet-v4-frontend#3827]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
2. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by 1b3634f6-9166-46d7-a43a-51d575159cf0** [comment]
cannot be public https://www.londonstockexchange.com/exchange/portfolio/charts.html#/portfolio/717962
body {
    margin: 0;
    font-size: .875rem;
    font-weight: 400;
    color: #16202C;
    text-align: left;
}font-family: sans-serif;
    line-height: 1.15;
font-size: .875rem;

почта mishaki111400@gmail.com

**Comment by 1b3634f6-9166-46d7-a43a-51d575159cf0** [comment]
эта страница https://www.londonstockexchange.com/exchange/portfolio/charts.html#/portfolio/717962 должа быть востановлена  в полном обьёме

**Comment by 0384223** [comment]
Hola Seveyr que es lo te te yendo que mandar ,el justificante de ingreso
no tengo nada de Coindesk que fue la empresa que me debo a Blickchain  de
esta cuenta no tengo capturas de pantalla yendo correos electrónicos y
WhatsApp, deme túi que  más puedo buscar
Saludos Amalia
