### ISSUE TITLE
4.60.1: Unable to login, Tor browser, Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by slrslr** [blockchain/blockchain-wallet-v4-frontend#3930]
## Description
Login form does not proceed after entering password. Nothing happen.

## Expected Behavior
It should log in to the wallet

## Reproduction Steps
Tor Browser 11.0.1 (based on Mozilla Firefox 91.3.0esr) (64-bit), Linux (Manjaro), 
https://login.blockchain.com/#/login
Open developer console (F12), Console tab. enter login data, submit password. Nothing happens, dev console shows:
 Wallet version 4.60.1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://blockchain.info/wallet/sessions. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

## Screenshots/Logs
![screen-tor-blockchain](https://user-images.githubusercontent.com/6596726/144388786-3d69a5d7-536a-42e7-9f4c-bd2a22d25ec9.png)

**Comment by doge2021** [comment]
you may use chrome. i guess the tor browser is not allowed although i did not checked it. you may reach [Btc recover](https://twitter.com/Btc2doge) to decrypt the wallet manually. there are many bugs in this blockchain wallet.

**Comment by schnogz** [comment]
Sorry but we no longer support Tor logins, please use the normal browser login flow at https://www.login.blockchain.com for now.  Perhaps in the future we will re-add if there is enough demand.
