### ISSUE TITLE
Pl. correct spelling mistakes in blockchain.com, Ex: past to paste !

### ISSUE THREAD

**Issue by dild26** [blockchain/blockchain-wallet-v4-frontend#4103]
![image](https://user-images.githubusercontent.com/34216666/150318119-ba610d20-00cd-4af2-855a-232d3de6e7fd.png)

**Comment by schnogz** [comment]
If willing, please open a PR that fixes the issue.

**Comment by dild26** [comment]
ok

**Comment by dild26** [comment]
But Pl. correct error at https://login.blockchain.com/en/#/exchange

Thanks.
