### ISSUE TITLE
Error Saving wallet: {“success”:false,"message":"wrong captcha"} when import wallet.aes.json via blockchain.com

### ISSUE THREAD

**Issue by doge2021** [blockchain/blockchain-wallet-v4-frontend#4238]
## Description and ## Screenshots
when try to import the old wallet.aes.json file via https://login.blockchain.com/wallet/import-wallet with correct password. it ask you set a new password:
![1](https://user-images.githubusercontent.com/84388200/155533134-30f17a7b-0339-4b4a-a68e-b97792f0fc54.png)
after you set the new password, it will show: Error Saving wallet:{“success”:false,"message":"wrong captcha"

![2](https://user-images.githubusercontent.com/84388200/155533321-6f1693fb-9243-4e30-9b7d-45e3e2e4e040.png)
on the console field, there are many errors.
### **Solutions:**
this actually is a bug of the old wallet conflict with the new version wallet. there are two methods to resolve this: 
1. the developer of blockchain.com remove the captcha layer. 
2. decrypt the wallet manually. (if you have the correct password or rough idea)
Stephen of [btc2doge.com](https://twitter.com/Btc2doge) has resolved this wallet issue for a friend from Malaysia today.

**Comment by schnogz** [comment]
This is fixed for now in production. It may break again in the future when we re-enable captcha but a long term fix will be pushed in the coming weeks.

**Comment by relh** [comment]
I still find this issue as of today

**Comment by doge2021** [comment]
Stephen of [btc2doge.com](https://twitter.com/Btc2doge) has resolved this wallet issue. you can try him. 

> I encountered this error today when trying to upload my wallet from May 2014
