### ISSUE TITLE
Wallet default installation not working, Redirect, Switch,withRouter issues

### ISSUE THREAD

**Issue by tdicusmurray** [blockchain/blockchain-wallet-v4-frontend#4252]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible
Expected behavior: show default wallet frontend.

ERROR in src/components/NavbarV2/MobileNav.tsx:3:19
TS2305: Module '"react-router-dom"' has no exported member 'withRouter'.
    1 | import React from 'react'
    2 | import { FormattedMessage } from 'react-intl'
  > 3 | import { NavLink, withRouter } from 'react-router-dom'
      |                   ^^^^^^^^^^
    4 | import { colors, Icon, IconName } from '@blockchain-com/constellation'
    5 | import styled from 'styled-components'
    6 |

ERROR in src/components/NavbarV2/Navbar.tsx:306:45
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Omit<Omit<NavLinkProps & RefAttributes<HTMLAnchorElement>, never> & Partial<Pick<NavLinkProps & RefAttributes<HTMLAnchorElement>, never>>, "theme"> & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type 'string | undefined' is not assignable to type 'To'.
      Type 'undefined' is not assignable to type 'To'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>, DefaultTheme, {}, never, ForwardRefExoticComponent<...>>): ReactElement<...>', gave the following error.
    Type 'string | undefined' is not assignable to type 'To'.
    304 |                 }
    305 |                 return (
  > 306 |                   <DropdownNavLink key={to} to={to}>
        |                                             ^^
    307 |                     <DropdownMenuItem data-e2e={e2e}>
    308 |                       <Destination>{copy}</Destination>
    309 |                     </DropdownMenuItem>

ERROR in src/layouts/Public/index.tsx:74:7
TS2322: Type '{ path: string; exact: boolean; render: (matchProps: any) => Element; }' is not assignable to type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
  Property 'exact' does not exist on type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
    72 |     <Route
    73 |       path={path}
  > 74 |       exact={exact}
       |       ^^^^^
    75 |       render={(matchProps) => (
    76 |         <ErrorBoundary>
    77 |           <Wrapper authProduct={authProduct}>

ERROR in src/layouts/Wallet/index.tsx:3:10
TS2305: Module '"react-router-dom"' has no exported member 'Redirect'.
    1 | import React from 'react'
    2 | import { connect, ConnectedProps } from 'react-redux'
  > 3 | import { Redirect, Route } from 'react-router-dom'
      |          ^^^^^^^^
    4 |
    5 | import { CoinfigType, CoinType } from '@core/types'
    6 | import { selectors } from 'data'

ERROR in src/layouts/Wallet/index.tsx:17:9
TS2322: Type '{ path: string; render: (props: any) => Element; }' is not assignable to type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
  Property 'render' does not exist on type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
    15 |       <Route
    16 |         path={path}
  > 17 |         render={(props) => (
       |         ^^^^^^
    18 |           <WalletLayout location={props.location} coin={this.props.coin}>
    19 |             <Component computedMatch={computedMatch} {...rest} />
    20 |           </WalletLayout>

ERROR in src/layouts/Wallet/MenuTop/index.tsx:3:10
TS2305: Module '"react-router-dom"' has no exported member 'withRouter'.
    1 | import React from 'react'
    2 | import { connect, ConnectedProps } from 'react-redux'
  > 3 | import { withRouter } from 'react-router-dom'
      |          ^^^^^^^^^^
    4 | import { bindActionCreators } from 'redux'
    5 |
    6 | import { InvitationsType } from '@core/types'

ERROR in src/providers/ErrorBoundaryProvider/index.tsx:3:10
TS2305: Module '"react-router-dom"' has no exported member 'withRouter'.
    1 | import React from 'react'
    2 | import { connect, ConnectedProps } from 'react-redux'
  > 3 | import { withRouter } from 'react-router-dom'
      |          ^^^^^^^^^^
    4 | import { bindActionCreators } from 'redux'
    5 |
    6 | import { actions, selectors } from 'data'

ERROR in src/scenes/app.tsx:3:10
TS2305: Module '"react-router-dom"' has no exported member 'Redirect'.
    1 | import React, { Suspense, useEffect } from 'react'
    2 | import { connect, ConnectedProps, Provider } from 'react-redux'
  > 3 | import { Redirect, Switch } from 'react-router-dom'
      |          ^^^^^^^^
    4 | import { ConnectedRouter } from 'connected-react-router'
    5 | import { map, values } from 'ramda'
    6 | import { Store } from 'redux'

ERROR in src/scenes/app.tsx:3:20
TS2305: Module '"react-router-dom"' has no exported member 'Switch'.
    1 | import React, { Suspense, useEffect } from 'react'
    2 | import { connect, ConnectedProps, Provider } from 'react-redux'
  > 3 | import { Redirect, Switch } from 'react-router-dom'
      |                    ^^^^^^
    4 | import { ConnectedRouter } from 'connected-react-router'
    5 | import { map, values } from 'ramda'
    6 | import { Store } from 'redux'

ERROR in src/scenes/Settings/Addresses/Menu/index.tsx:4:10
TS2305: Module '"react-router-dom"' has no exported member 'withRouter'.
    2 | import { FormattedMessage } from 'react-intl'
    3 | import { LinkContainer } from 'react-router-bootstrap'
  > 4 | import { withRouter } from 'react-router-dom'
      |          ^^^^^^^^^^
    5 | import { compose } from 'redux'
    6 | import { Field, reduxForm } from 'redux-form'
    7 | import styled from 'styled-components'

**Comment by schnogz** [comment]
Are you still seeing these issues? If so, what are the steps to reproduce?
