### ISSUE TITLE
Verification link expired

### ISSUE THREAD

**Issue by YourGgift** [blockchain/blockchain-wallet-v4-frontend#4353]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
2. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Expired verification email link sent to my registered email

## Expected Behavior
I would love the link to enable me upload further identification information so my account can be verified 

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.
![42D9F176-7B48-4777-8BF4-EFFA88BCAB3C](https://user-images.githubusercontent.com/101754213/158696770-4e2d665b-592b-4564-afe5-ffd4e9e15895.png)

## Additional Information
Add any addition information that might be useful to our team. Email address is ggokonkwor99@gmail.com

**Comment by schnogz** [comment]
Please reach out to our support team directly for this request.

**Comment by YourGgift** [comment]
I’ve reached out to the blockchain support team for weeks now but I’ve not been replied
