### ISSUE TITLE
I AM UNABLE TO TRANSFER BTC FROM MY TRADING ACCOUNT TO ANOTHER BITCOIN WALLET

### ISSUE THREAD

**Issue by Lukman0211** [blockchain/blockchain-wallet-v4-frontend#6298]
Hey this is ALABI LUKMAN FROM NIGERIA, AFRICA. There was a time blockchain introduced trading account and Defi account. I transferred $500 to my trading account while I leave the rest in my Defi account and the money added up to $1k plus. Rush down to a day before yesterday i tried to transfer my money to Defi account and it keeps saying I haven’t been authorized to use fiat and my account limit to swap coins has been approved. We all know you can’t transfer money to your trading account if you haven’t been approved. Please I want you to rectify the issue because that’s all my life savings I don’t really have money in my Defi account. Thanks 
![IMG_0223](https://github.com/blockchain/blockchain-wallet-v4-frontend/assets/160808370/098c899e-a4f6-4c05-b408-b4cfd754949a)
![IMG_0222](https://github.com/blockchain/blockchain-wallet-v4-frontend/assets/160808370/5335e2b8-e534-4f6d-a4c9-585f600fa748)
![IMG_0221](https://github.com/blockchain/blockchain-wallet-v4-frontend/assets/160808370/ae2f7dee-68e0-48a6-beb8-30c82718d832)

**Comment by Tangee69** [comment]
> Hey this is ALABI LUKMAN FROM NIGERIA, AFRICA. There was a time blockchain introduced trading account and Defi account. I transferred $500 to my trading account while I leave the rest in my Defi account and the money added up to $1k plus. Rush down to a day before yesterday i tried to transfer my money to Defi account and it keeps saying I haven’t been authorized to use fiat and my account limit to swap coins has been approved. We all know you can’t transfer money to your trading account if you haven’t been approved. Please I want you to rectify the issue because that’s all my life savings I don’t really have money in my Defi account. Thanks 
> ![IMG_0223](https://github.com/blockchain/blockchain-wallet-v4-frontend/assets/160808370/098c899e-a4f6-4c05-b408-b4cfd754949a)
> ![IMG_0222](https://github.com/blockchain/blockchain-wallet-v4-frontend/assets/160808370/5335e2b8-e534-4f6d-a4c9-585f600fa748)
> ![IMG_0221](https://github.com/blockchain/blockchain-wallet-v4-frontend/assets/160808370/ae2f7dee-68e0-48a6-beb8-30c82718d832)
> 

Showme****

**Comment by Tangee69** [comment]
Show me**__**

**Comment by Lukman0211** [comment]
Show you what?

**Comment by CTucker-BC** [comment]
@Lukman0211 Please contact support if you need further assistance - https://support.blockchain.com/hc/en-us
