### ISSUE TITLE
Assets 

### ISSUE THREAD

**Issue by Devante7** [blockchain/blockchain-wallet-v4-frontend#6389]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
2. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by Tangee69** [comment]
> # 🐛Bug Report 🐛
> _**Do**_
> 
> 1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
> 2. Provide as much information as possible
> 
> _**Don't**_
> 
> 1. Leave this form blank
> 2. Provide personal information
> 3. Provide your GUID, password, or email
> 
> _Failure to follow the do's and don'ts will result in us closing the issue without further dialogue_
> 
> ## Description
> Provide a clear and concise description of the issue.
> 
> ## Expected Behavior
> Explain what you would expect to happen.
> 
> ## Reproduction Steps
> Enter detailed steps to reproduce the issue.
> 
> ## Screenshots/Logs
> If available, please provide any relevant screenshots or logs.
> 
> ## Additional Information
> Add any addition information that might be useful to our team.

I don't know where to send accept to my coinbase account I need help desperately I'm stuck and cold please help me I need help desperately

**Comment by Tangee69** [comment]
I have coinbase wallet and meta wallet need help desperately I am stuck in cold no money can't retrieve my assets please help

**Comment by CTucker-BC** [comment]
@Tangee69 Please open a support ticket on the website at https://support.blockchain.com/hc/en-us
