### ISSUE TITLE
Critical: Impossible to login to the wallet

### ISSUE THREAD

**Issue by Bytemasterz** [blockchain/blockchain-wallet-v4-frontend#6400]
Hi,
Impossible to login to blockchain.com wallet (in browser using chrome), it's loading indefinitely, the login form never appears.
Same problem for 3 friends.

I've those 2 errors:
`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src https://login.blockchain.com https://wallet-frontend.prod.blockchain.info https://wallet-frontend-pre-release.prod.blockchain.info`

and 

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src-elem https://login.blockchain.com https://wallet-frontend.prod.blockchain.info https://wallet-frontend-pre-release.prod.blockchain.info 'nonce-`

**Comment by Sentini14** [comment]
Private key I need it

***@***.***

**Comment by workingabalone** [comment]
Hello @Bytemasterz  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by CTucker-BC** [comment]
Hello @Bytemasterz thank you for reporting this issue, can you please provide some additional information? For example, are you able to tell us the `x-blockchain-cp-f` response header for the document request?

If you need further assistance, please contact support at https://support.blockchain.com/hc/en-us
