### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by miketwenty1** [blockchain/blockchain-wallet-v4-frontend#6409]
I'm unsure which repo or where to ask this.

I would like to know if it's possible to use your public API to download block metadata while omitting the transaction array for the rawblock api endpoint.

Please let me know, thanks!

**Comment by CTucker-BC** [comment]
Hello, here is the link to the documentation for our public APIs; Unfortunately, the feature you're requesting does not seem to be supported at this time: https://www.blockchain.com/explorer/api

**Comment by miketwenty1** [comment]
@CTucker-BC is there a place to make a feature request?
