### ISSUE TITLE
3 child repos do not have package locks

### ISSUE THREAD

**Issue by kristovatlas** [blockchain/blockchain-wallet-v4-frontend#710]
# 🐛 Bug Report 🐛

## Description
No `package-lock.json` file is present in the following 3 sub-repos:
* https://github.com/blockchain/blockchain-wallet-v4-frontend/tree/development/packages/blockchain-info-components
* https://github.com/blockchain/blockchain-wallet-v4-frontend/tree/development/packages/blockchain-wallet-v4-frontend
* https://github.com/blockchain/blockchain-wallet-v4-frontend/tree/development/packages/blockchain-wallet-v4

Our build process starts with `yarn bootstrap` from the parent repo directory. The parent repo directory has its own `package-lock.json` file, but it doesn't appear this will be respected in the 3 sub-repo's node modules during building.

## Reproduction Steps
This is outside of the normal building process, but if you believe that lerna is using npm to build the sub-repos, then you can recreate this using `npm install` from the `blockchain-info-components directory`. `yarn` doesn't provide any warnings.

## Additional Information
* https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5
* https://docs.npmjs.com/files/package-lock.json

**Comment by kristovatlas** [comment]
Same issue for the other 2 sub-repos.

After talking with @schnogz, there's no obvious quick fix.

Although we use `yarn` to build, we're not using its locking system. `yarn bootstrap` calls lerna to run the installs, using npm in turn. Therefore, the top-level package-lock.json file will be respected, but it doesn't appear that it will be applied to the 3 sub-repos with their own `package.json` files.

Resolution: There may be a way in lerna to generate the child lock files. The dev team is also considering getting rid of lerna and using npm's workspaces functionality, which should simply the package locking situation.

**Comment by tony-blockchain** [comment]
1. We have to switch to yarn workspaces, which improves build time, by saving time downloading common modules
2. I'd migrate to yarn.lock and using yarn as installer, as in my experience it proved to be much more stable and well designed. Npm has changed their lock behaviour twice already:
- First time they've built from package-lock
- Then(npm v5) they started updating package-lock during install (wth?)
- Now they introduced `npm ci` which builds from package-lock

**Comment by tony-blockchain** [comment]
Here's the original workspaces issue related to child yarn.locks
https://github.com/yarnpkg/yarn/issues/5428

First comment cites yarn blog to explain that while using package separately through npm `yarn.lock`/`package-lock.json` is irrelevant because the package is already built.
And build is still performed in monorepo.

BTW there are only 6 dependencies in the whole project that are not shared.

**Comment by schnogz** [comment]
We have now completely migrated off of Lerna and into Yarn workspaces.  As @tony-blockchain pointed out above, the `yarn.lock` file in the root of the repo will lock dependencies for all sub-packages.

Marking closed.
