### ISSUE TITLE
Complete Update Dropdown Work

### ISSUE THREAD

**Issue by plondon** [blockchain/blockchain-wallet-v4-frontend#843]
# 🐛 Bug Report 🐛

## Description
Dropdowns are not ideal to interact with

## Screenshots/Logs
<img width="580" alt="screen shot 2018-08-03 at 17 13 34" src="https://user-images.githubusercontent.com/5640772/43645204-34d756ae-96ff-11e8-8719-9356bc4f08aa.png">

## Additional Information
Ongoing work here: https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/837

**Comment by vadimmartin** [comment]
Hello. Explain to me please where my bitcoins from the purse with the points of protection included are gone?

**Comment by plondon** [comment]
Hi @vadimmartin if you are having an issue with your wallet non code related please reach out to support.blockchain.com.

**Comment by plondon** [comment]
There are a few issues at least from what I can see blocking https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/837 from being merged.

1. Send BTC/BCH/ETH output dropdown logic. The interaction no longer works as intended.
<img width="578" alt="screen shot 2018-08-07 at 12 45 47 pm" src="https://user-images.githubusercontent.com/5640772/43790184-d89738a2-9a3f-11e8-9cd6-d40371d08435.png">

2. Exchange no longer works when there is more than one btc/bch account
<img width="836" alt="screen shot 2018-08-07 at 12 47 00 pm" src="https://user-images.githubusercontent.com/5640772/43790231-000d4692-9a40-11e8-8f0a-55e271427131.png">

3. Some small styling changes. Background should be white, cursor pointer, no border-radius (?)

**Comment by mchlcrtz** [comment]
Thank you for the feedback. 

Could you clarify further on the send BTC/BCH/ETH interaction? I am running yarn start on the development branch and the interaction seems to be in line with recent changes to the fixDropdowns branch. 

Also, how should I run locally? I am unable to re-create the error on the exchange route

<img width="1440" alt="screen shot 2018-08-08 at 2 57 48 pm" src="https://user-images.githubusercontent.com/34140729/43858238-8827a29e-9b1b-11e8-8df4-85c79fde8f00.png">

Thank you

**Comment by plondon** [comment]
@mchlcrtz check out the difference between dev and fixDropdowns:

dev: https://gyazo.com/875cc5c3e4ed09d5fbff6e1fd63abbf7
fixDropdowns: https://gyazo.com/5e6a31981954226730581fe18278d395

In regards to exchange, what happens if you add another BTC account (in settings) then go to exchange and pick a state.

**Comment by mchlcrtz** [comment]
My mistake. I see that when there are multiple BTC accounts, the template header does not render correctly and I did not account for the to dropdown.

**Comment by mchlcrtz** [comment]
Hi @plondon, apologies on the delay. I had my hands full last week. I see that the changes merged to development have updated headers in exchange. Might there be any additional work that needs to be done? Perhaps the icons?

**Comment by plondon** [comment]
Hey @mchlcrtz thanks I'll close this issue then. I actually opened an issue with react-select so we can customize the dropdown. See: https://github.com/JedWatson/react-select/issues/2947
