### ISSUE TITLE
Hello. Explain to me please where my bitcoins from the purse with the points of protection included are gone?

### ISSUE THREAD

**Issue by vadimmartin** [blockchain/blockchain-wallet-v4-frontend#845]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.
Hello. Explain to me please where my bitcoins from the purse with the points of protection included are gone?

**Comment by vadimmartin** [comment]
Hello. Explain to me please where my bitcoins from the purse with the points of protection included are gone?

**Comment by plondon** [comment]
Please reach out to support.blockchain.com or provide more info.
