### ISSUE TITLE
Figure out react-highcharts csp

### ISSUE THREAD

**Issue by plondon** [blockchain/blockchain-wallet-v4-frontend#881]
# 🐛 Bug Report 🐛

## Description
Currently the wallet displays multiple errors when react-highcharts tries to inject a style due to our strict csp, this should be cleaner. Consider looking into the r-h library and seeing if we can add webpack_nonce support, if not see issue below.

## Expected Behavior
No console warnings/errors

## Reproduction Steps
Create wallet and open the console

## Additional Information
https://github.com/highcharts/highcharts/issues/6884

**Comment by 915030705** [comment]
> #  Bug Report 
> ## Description
> Currently the wallet displays multiple errors when react-highcharts tries to inject a style due to our strict csp, this should be cleaner. Consider looking into the r-h library and seeing if we can add webpack_nonce support, if not see issue below.
> 
> ## Expected Behavior
> No console warnings/errors
> 
> ## Reproduction Steps
> Create wallet and open the console
> 
> ## Additional Information
> [highcharts/highcharts#6884](https://github.com/highcharts/highcharts/issues/6884)

**Comment by Sopon1234** [comment]
https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/881#issue-351266402

**Comment by ma2356748** [comment]
اريد ان اجني المال  ولاكن لا اعلم الطريقه المثاليه
