### ISSUE TITLE
https://blockchain.info/payment_request?address=1FvfmA6zgEzFLvQnuDMv8pjKaGJiUqt668&amount=0.004&message=Fy

### ISSUE THREAD

**Issue by xoxo555** [blockchain/blockchain-wallet-v4-frontend#893]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
Thanks for using the payment request feature, but please send this link to someone who owes you money, not our developers. :)
