### ISSUE TITLE
Cloning project fails on Windows

### ISSUE THREAD

**Issue by schnogz** [blockchain/blockchain-wallet-v4-frontend#921]
# 🐛 Bug Report 🐛

## Description
Cloning new project, and most Git commands, on Windows machines does not work.

## Expected Behavior
Git should work.

## Reproduction Steps
Clone project onto a Windows machine.

## Screenshots/Logs
![capture](https://user-images.githubusercontent.com/6364918/44619352-9b383b00-a84a-11e8-9875-d10c47897a02.PNG)

## Additional Information
As per the error above, there is a file named `{ }` in `packages/blockchain-wallet-v4-frontend/src/assets/locales/` which is breaking Windows. Seems like it is not needed... @plondon

**Comment by plondon** [comment]
Sorry, mustve been auto generated at one point when setting up translation manager. Removing https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/983
