### ISSUE TITLE
Lost sub-addresses

### ISSUE THREAD

**Issue by samguy26** [blockchain/blockchain-wallet-v4-frontend#946]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

I created 20 Bitcoin Wallet, and 15 sub-bitcoin addresses on each wallet total of 300 bitcoin address, after I week I lost more than half of the sub-bitcoin address, how to retrieve this?

thnx,

**Comment by plondon** [comment]
What do you mean by you lost them?
