### ISSUE TITLE
Backend source

### ISSUE THREAD

**Issue by speculees** [blockchain/blockchain-wallet-v4-frontend#957]
Quick question.
Is backend hosted at blockchain.[info | com] for this project open source as well?
If so can you please provide a link to it?
If no, will it be available sometime in near future, and would you recommend reverse engineering backend form here, or is there an alternative here?

**Comment by plondon** [comment]
@speculees I believe all the endpoints we hit are publicly accessible via a few different urls (api.blockchain.info, blockchain.info, etc). These are not open source though.

It's possible some endpoints are only accessible from only whitelisted requests, like metadata I think.

**Comment by speculees** [comment]
@plondon Ah I see. Thank you for quick response.

**Comment by plondon** [comment]
Sure, if you're building your own wallet lmk if you get stuck anywhere, our devs and myself are happy to help out.

**Comment by speculees** [comment]
So, it seems that the current implementation of this wallet does address derivation using only the xpub. So, it sends this data to the server, the server derives the address list from that and all is good.
However, all of our other wallets use hardened key derivation. This means that the xpub cannot be used for this purpose since you also need the xpriv to find valid addresses. @plondon How would you recommend I approach this issue. I see that HDWallet supports this IE:

`export const deriveAccountNodeAtIndex = (seedHex, index, network) => {
  let seed = BIP39.mnemonicToSeed(BIP39.entropyToMnemonic(seedHex))
  let masterNode = Bitcoin.HDNode.fromSeedBuffer(seed, network)
  return masterNode.deriveHardened(44).deriveHardened(0).deriveHardened(index)
}`

can this func be used for this purpose, or should I try to override getData function at
/packages/blockchain-wallet-v4-frontend/src/modals/RequestBitcoin/FirstStep/selectors.js
and just derive it there?
