### ISSUE TITLE
my deposit on my auto bitcoin builder not recieve

### ISSUE THREAD

**Issue by Nimref** [blockchain/blockchain-wallet-v4-frontend#965]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by plondon** [comment]
I don't think this has anything to do with the blockchain.com wallet. Closing
