### ISSUE TITLE
RECEBI UM VALOR DE 0,005715BT no dia 08/09/2018 as 12:38Pm e no dia seguinte esse mesmo valor foi enviada para o end: 1HoAHFhq42Z8CubsK6PNVCQKGeFc3Bju8o  as  6:24Am. Mas não reconheço esse envio e nem recebi notificação nenhuma. preciso resolver fico no aguardo.

### ISSUE THREAD

**Issue by edvancassio** [blockchain/blockchain-wallet-v4-frontend#968]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.
![1btc](https://user-images.githubusercontent.com/43153332/45325889-8802bc00-b528-11e8-8cbd-83c7ce9ae881.JPG)

**Comment by plondon** [comment]
Please file a ticket with our support team. support.blockchain.com
