### ISSUE TITLE
Deposit not received 

### ISSUE THREAD

**Issue by Onyxpify** [blockchain/blockchain-wallet-v4-frontend#991]
# 🐛 Deposit issue🐛

Someone sent bitcoin worth of $854 to my blockchain wallet,  the transaction now have 101 Confirmations, it was sent to me since yesterday, yet up till now the bitcoin has not reflected in my wallet.  Here is the transaction  ID https://www.blockchain.com/btc/tx/bdc7555a7fac2847d4bd7c5d902597e3a4614dec2d325856a85e0aeea1274642

**Comment by Onyxpify** [comment]
Why closing this, up till now I have not received this payment please check my address  https://www.blockchain.com/btc/address/16jF5DgPp4mcbi495GJc7qYUxo1dbUd9ww

You won't see that amount in my wallet. 

Please credit me

**Comment by carolinesenco** [comment]
![Screenshot_20190819-002443_aFan](https://user-images.githubusercontent.com/54257034/63239238-5013f680-c218-11e9-9ffc-117e17dc641d.jpg)
