### ISSUE TITLE
Instead of showing balance it's showing me error in my wallet.

### ISSUE THREAD

**Issue by blockmine1** [blockchain/blockchain-wallet-v4-frontend#998]
# 🐛 Bug Report 🐛

## Description

my fund is not showing in my wallet showing 0 balance in account while i have good balance. 
http://prntscr.com/kwehsb

See this screenshot, when i click on wallets & Addresses button it's not showing any record it's showing error why? where my all record gone? i want back that all record.

http://prntscr.com/kwt56y

Me and my friends get the same issue in 1 week. i thing new design of blockchain.com wallet is not capable for unlimited transactions, once we have too much daily transaction it's show this error in account. 
 

## Expected Behavior

While if any wallet have upto lac wallet addresses infect unlimited wallet address, wallet should be load in speed. but current version of blockchain is not ready for this work,
 
## Reproduction Steps
I Think so that, blockchain should revert there design to previous version until all these issues resolve and new fast and good capacity design create,

Team should look into this issue asap!

**Comment by plondon** [comment]
We think users facing this issue may have imported an address that makes the balance/transaction request fail. https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/995 is attempting to solve the issue. We are testing this today

**Comment by plondon** [comment]
Have you ever imported an address, public key or private key to your wallet?

**Comment by blockmine1** [comment]
No i haven't imported any thing. i just created few wallet addresses in one blockchain.com wallet. and i receive payment through blockchain api, i receive many payments daily. 

I just think that because of too many transaction your site is showing this error. blockchain script code can't get load of too many transaction in one wallet. it's capacity is not enough.

**Comment by plondon** [comment]
If you can find the error in the network tab (probably from multiaddr), that would help

**Comment by blockmine1** [comment]
http://prntscr.com/kx8mzt

i am getting this error on network tab please check screen shot

**Comment by plondon** [comment]
Thanks for the screenshot, these are the responses for latestblock, which are successful.

Please:
1. have the network tab open when you login
2. filter by multiaddr
3. check response for multiaddr

**Comment by plondon** [comment]
Well this is not an issue with the new wallet but seems like you've hit the multiaddr max limit for addresses. You will most likely need to archive 258 addresses, and I would recommend using the hd wallet instead of importing addresses

**Comment by blockmine1** [comment]
But to achive addresses it must show addresses in my wallet right? but it is not showing any record just showing errors. http://prntscr.com/ky2p9r

you can see screenshot and tell me proper solution.

**Comment by plondon** [comment]
We will work on a fix for this

**Comment by blockmine1** [comment]
OK i have also submitted support ticket request please must check that also. it will helps you too find exact problem.  

REQUEST #625093

**Comment by blockmine1** [comment]
Also please tell me how long does it will take to resolve this issue?

**Comment by plondon** [comment]
We will release the fix on thursday

**Comment by blockmine1** [comment]
OK thanks, please tell me what if i use recover fund option to recover my missing fund from my existing wallet? does it will recover all fund if i use recover fund option and use backup phase phares? 

https://login.blockchain.com/#/recover

does this option will set my again back to normal? because it will generate new wallet id for my existing wallet right?

**Comment by plondon** [comment]
Recover will recover the hd wallet, not your imported addresses, of which you have many :)

**Comment by blockmine1** [comment]
Does generating address using blockchain api also know as imported address? 

I never used import bitcoin address button, 

for example i  just created new wallet to explain you that how i was using my wallet. 

http://prntscr.com/ky4229

see this screenshot it will show you that i generated wallet like this. in one blockchain account i used multiple wallets. 

I never used import bitcoin address option please see example screenshot.
http://prntscr.com/ky43kw

but also note that i was using my that wallet in my site by using receiving payments api of blockchain.

if the address api generates called imported addresses or not?

**Comment by plondon** [comment]
Better not to post them publicly, I can check them there if you post them in the ticket. Thanks

**Comment by blockmine1** [comment]
yes sure please check them there in my ticket

**Comment by blockmine1** [comment]
did you checked my ticket REQUEST #625093 i just posted all xpubs there.?

**Comment by blockmine1** [comment]
I have replied to ticket again please check.

**Comment by blockmine1** [comment]
https://prnt.sc/ky90hw

my account is still not showing my wallet addresses you can see in screenshot. please fix it asap! why this issue is not being fix yet.?

**Comment by plondon** [comment]
https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/998#issuecomment-423985362

**Comment by blockmine1** [comment]
You mean i have to wait 2 more days?

**Comment by plondon** [comment]
Thursday is 3 days away. Or you can run the project locally on `release/4.2.x` branch. Otherwise yes, 3 days, on Thursday.

**Comment by blockmine1** [comment]
you can run the project locally on release/4.2.x 

can you guide me how can i run this project locally ?

**Comment by plondon** [comment]
https://github.com/blockchain/blockchain-wallet-v4-frontend#local-development

You will need to `git checkout release/4.2.x` after you clone the repository.

**Comment by blockmine1** [comment]
OK i will wait 3 days i hope my account issue will be fixed then. because it's very important for me.

Thanks

**Comment by plondon** [comment]
4.2.12 has been released so I will close this issue and resolve the rest in your support ticket

**Comment by kamsoflash** [comment]
good day . please i have same problem now . i cant find my fund in my wallet
